### ISSUE TITLE
Finalize J2V8 3.1

### ISSUE THREAD

**Issue by irbull** [eclipsesource/J2V8#113]

**Comment by noear** [comment]
什么时候，可以在jcenter下载啊？现在3.1.0-SNAPSHOT下载不了（在中国区）

**Comment by irbull** [comment]
This translates to: What time, you can download the jcenter ah? 3.1.0-SNAPSHOT not download now ( in China region )

Currently 3.1.0-SNAPSHOT is available from Maven Central. I've tested this North America and Europe. I don't know about China.  Directly downloads are at [here](https://oss.sonatype.org/content/repositories/snapshots/com/eclipsesource/j2v8/j2v8/3.1.0-SNAPSHOT/)

**Comment by noear** [comment]
刚才给的这个网址可以打开。希望尽快也能在jcenter下载（以前都是可以下的）；还有希望也能出jar版本

**Comment by irbull** [comment]
J2V8 3.1 has been pushed to maven central. Android builds are available with the follow pom dependency:
```
<dependency>
  <groupId>com.eclipsesource.j2v8</groupId>
  <artifactId>j2v8</artifactId>
  <version>3.1.0</version>
  <type>aar</type>
</dependency>
```
It can also be accessed in a gradle build as follows:
```
compile 'com.eclipsesource.j2v8:j2v8:3.1.0@aar'
```

**Comment by noear** [comment]
非常感谢。可以下载了：）

**Comment by liziNo1** [comment]
> 非常感谢。可以下载了：）

有没有最新的包上传下，我下不了
