### ISSUE TITLE
Failing tests when building from source (Linux only)

### ISSUE THREAD

**Issue by DavidRigglemanININ** [eclipsesource/J2V8#116]
I'm successfully able to build from source and the tests all pass in my Mac OSX environment. However, when trying to be able to build from source in Linux, I'm running into some problems. The build phase is fine, but when the test phase of Maven runs, I get a few failing tests and then lots of console warnings about "V8 runtimes not properly released". I'm guessing the warnings may be coming from the failing tests. The tests in particular that are failing are those around enabling debugging support in V8Test.java. I did a little digging and it looks like the test is failing because inside of the assert for debug enabled, there is an IOException for connection refused. I'm thinking maybe it's some timing issue. I'm also running my Linux environment in a VM, so it's possible that has some impact. Looking at the git history, I see you disabled the debug tests on November 2nd and then shortly reenabled them later. Did you run into a similar problem? If so, is there a fix? Thanks!

**Comment by irbull** [comment]
Try disabling the debug tests -- this will all be changing very soon
anyways. If one test fails (and a runtime is left in memory) then many
other tests will fail. Are you running from master?

On Thu, Dec 3, 2015 at 12:38 PM, David Riggleman <notifications@github.com>
wrote:

> I'm successfully able to build from source and the tests all pass in my
> Mac OSX environment. However, when trying to be able to build from source
> in Linux, I'm running into some problems. The build phase is fine, but when
> the test phase of Maven runs, I get a few failing tests and then lots of
> console warnings about "V8 runtimes not properly released". I'm guessing
> the warnings may be coming from the failing tests. The tests in particular
> that are failing are those around enabling debugging support in
> V8Test.java. I did a little digging and it looks like the test is failing
> because inside of the assert for debug enabled, there is an IOException for
> connection refused. I'm thinking maybe it's some timing issue. I'm also
> running my Linux environment in a VM, so it's possible that has some
> impact. Looking at the git history, I see you disabled the debug tests on
> November 2nd and then shortly reenabled them later. Did you run into a
> similar problem? If so, is there a fix? Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipsesource/J2V8/issues/116>.
>



-- 
R. Ian Bull | EclipseSource Victoria | +1 250 477 7484
http://eclipsesource.com | http://twitter.com/eclipsesource

**Comment by DavidRigglemanININ** [comment]
Yeah, I'm running from a fresh copy of master. Disabling those tests do seem to work so if that is the right solution, then I'm ok doing that. I just didn't want to make sure first it wasn't a problem with my environment

**Comment by irbull** [comment]
I think your right, I had a similar problem. Those tests aren't very good
(they are actually testing the proxy that we need to run debug messages).
The entire debug story is changing (has changed with newer versions of V8)
and we have a plan to adapt. The debug stuff is all deprecated to make way
for a new API. If those tests fail, that means nothing about the quality of
J2V8 core.

On Thu, Dec 3, 2015 at 12:54 PM, David Riggleman <notifications@github.com>
wrote:

> Yeah, I'm running from a fresh copy of master. Disabling those tests do
> seem to work so if that is the right solution, then I'm ok doing that. I
> just didn't want to make sure first it wasn't a problem with my environment
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipsesource/J2V8/issues/116#issuecomment-161781652>.
>



-- 
R. Ian Bull | EclipseSource Victoria | +1 250 477 7484
http://eclipsesource.com | http://twitter.com/eclipsesource

**Comment by DavidRigglemanININ** [comment]
Thanks.
