### ISSUE TITLE
Build j2v8 from source

### ISSUE THREAD

**Issue by pathikdevani** [eclipsesource/J2V8#117]
explain how to build j2v8 from source. i want build for android,Linux and windows system.

i already try below methods
 1) docker build 
 2) visual studio 13 & 15 both
 3) android studio gradle

can't get success..

**Comment by matiwinnetou** [comment]
This is already done I think, there is a new build system

**Comment by irbull** [comment]
A new build system exists. We are limiting support to only Android (see #441), but others are free to build J2V8 for other platforms. We need to review our build docs. That's covered in #40. I'm closing this issue.
