### ISSUE TITLE
classes.jar (in j2v8-3.1.0.aar) include a so file (libj2v8_linux_x86_64.so)!

### ISSUE THREAD

**Issue by ctyytc** [eclipsesource/J2V8#118]
After I downloaded the j2v8-3.1.0.aar from [page](http://search.maven.org/#artifactdetails%7Ccom.eclipsesource.j2v8%7Cj2v8%7C3.1.0%7Caar.asc), I found that classes.jar (in j2v8-3.1.0.aar) include a so file (libj2v8_linux_x86_64.so).
I think this is a issue of deploy.

**Comment by irbull** [comment]
Thanks for reporting this. I will spin a 3.1.1 today to address this issue.

**Comment by irbull** [comment]
Yes, you're right. Our deployment script had a bug in it. I've fixed the script in b404e50911b047920c6e80b9dc716b339d688513. I've released 3.1.1 which is much smaller now. This should be available on Maven central shortly.

**Comment by ctyytc** [comment]
Excellent!
