### ISSUE TITLE
Failure to 3.1.2 will always load the DLL for Windows

### ISSUE THREAD

**Issue by yososs** [eclipsesource/J2V8#120]
file name of j2v8_win32_x86.jar and j2v8_win32_x86_64.jar have replaced. To fail to dll load, V8.createV8Runtime () will always fail.

**Comment by irbull** [comment]
Can you try again. I was having some deployment problems. I just pushed
3.1.6 (took me a few tries), but I think I have it working. If not, I'll
need to fire up a Windows VM and figure out what's going on.

Thanks!

On Wed, Dec 9, 2015 at 2:42 PM, yosbits <notifications@github.com> wrote:

> file name of j2v8_win32_x86.jar and j2v8_win32_x86_64.jar have replaced.
> To fail to dll load, V8.createV8Runtime () will always fail.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipsesource/J2V8/issues/120>.
>



-- 
R. Ian Bull | EclipseSource Victoria | +1 250 477 7484
http://eclipsesource.com | http://twitter.com/eclipsesource

**Comment by irbull** [comment]
I've tried 3.1.6 on a 64 bit windows VM and it appears to work. Please re-open if you are having problems.

**Comment by yososs** [comment]
I tried in j2v8 3.1.2 of the latest for Windows that can be acquired in the maven.
Since it is failing in the initialization of the V8, it and try to expand the jar file,

j2v8_win32_x86_64-3.1.2.jar--------------------64bit
+ Libj2v8_win32_x86.dll ------------------------- 32bit 

j2v8_win32_x86-3.1.2.jar -------------------------32bit
+ Libj2v8_win32_x86_64.dll --------------------- 64bit

Included are dll file has been replaced in the 32bit and 64bit.

In 3.1.6 Can you believe that this problem has been fixed?

**Comment by irbull** [comment]
Yes, I believe this is fixed in 3.1.6. If you could double check, that
would be greatly appreciated.

On Wed, Dec 9, 2015 at 3:46 PM, yosbits <notifications@github.com> wrote:

> I tried in j2v8 3.1.2 of the latest for Windows that can be acquired in
> the maven.
> Since it is failing in the initialization of the V8, it and try to expand
> the jar file,
>
> j2v8_win32_x86_64-3.1.2.jar--------------------64bit
>
>    - Libj2v8_win32_x86.dll ------------------------- 32bit
>
> j2v8_win32_x86-3.1.2.jar -------------------------32bit
>
>    - Libj2v8_win32_x86_64.dll --------------------- 64bit
>
> Included are dll file has been replaced in the 32bit and 64bit.
>
> In 3.1.6 Can you believe that this problem has been fixed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipsesource/J2V8/issues/120#issuecomment-163439284>.
>



-- 
R. Ian Bull | EclipseSource Victoria | +1 250 477 7484
http://eclipsesource.com | http://twitter.com/eclipsesource

**Comment by yososs** [comment]
Where can I get 3.1.6?

**Comment by irbull** [comment]
It should be in maven central (same place you got 3.1.2).

<dependency>
  <groupId>com.eclipsesource.j2v8</groupId>
  <artifactId>j2v8_win32_x86_64</artifactId>
  <version>3.1.6</version>
</dependency>

https://oss.sonatype.org/service/local/repositories/releases/content/com/eclipsesource/j2v8/j2v8_win32_x86_64/3.1.6/j2v8_win32_x86_64-3.1.6.jar

On Wed, Dec 9, 2015 at 3:58 PM, yosbits <notifications@github.com> wrote:

> Where can I get 3.1.6?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipsesource/J2V8/issues/120#issuecomment-163441200>.
>



-- 
R. Ian Bull | EclipseSource Victoria | +1 250 477 7484
http://eclipsesource.com | http://twitter.com/eclipsesource

**Comment by yososs** [comment]
In 3.1.6, we were sure that this problem has been fixed.

Thank you.
