### ISSUE TITLE
Inconsistent module metadata

### ISSUE THREAD

**Issue by michel-kraemer** [eclipsesource/J2V8#126]
When I try to add a dependency to J2V8 in my Gradle build file I get the following error message:

```
> Could not resolve com.eclipsesource.j2v8:j2v8_linux_x86_64:3.1.6.
   > inconsistent module metadata found. Descriptor: com.eclipsesource.j2v8:j2v8_linux_arm64:3.1.6 Errors: bad module name: expected='j2v8_linux_x86_64' found='j2v8_linux_arm64'
```

My Gradle dependency looks like this:

``` gradle
dependencies {
    compile 'com.eclipsesource.j2v8:j2v8_linux_x86_64:3.1.6'
}
```

The last working version that I found is 3.1.1. By the way, 3.1.6 works fine under Windows.

Cheers,
Michel

**Comment by piotrtomiak** [comment]
This is caused by incorrect arch property in the pom.xml file of the linux build:
```xml
<properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <os>linux</os>
    <ws>gtk</ws>
    <arch>arm64</arch>
  </properties>
 
  <groupId>com.eclipsesource.j2v8</groupId>
  <artifactId>j2v8_linux_${arch}</artifactId>
  <version>3.1.6</version>
  <packaging>bundle</packaging>
```
The arch parameter should be "x86_64" and not "arm". @irbull is it possible for you to update pom.xml or release 3.1.7 with corrected metadata?

**Comment by irbull** [comment]
Ah crap. Sorry about that. My build server is currently in a state of flux
right now as I try to get V8 4.x built so I can migrate to that. However, I
will get a fix out for this with 3.1.7.

Thanks!

On Wed, Feb 17, 2016 at 7:58 AM, Piotr Tomiak <notifications@github.com>
wrote:

> This is caused by incorrect arch property in the pom.xml file of the linux
> build:
>
> <properties>
>     <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
>     <os>linux</os>
>     <ws>gtk</ws>
>     <arch>arm64</arch>
>   </properties>
>
>   <groupId>com.eclipsesource.j2v8</groupId>
>   <artifactId>j2v8_linux_${arch}</artifactId>
>   <version>3.1.6</version>
>   <packaging>bundle</packaging>
>
> The arch parameter should be "x86_64" and not "arm". @irbull
> <https://github.com/irbull> is it possible for you to update pom.xml or
> release 3.1.7 with corrected metadata?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipsesource/J2V8/issues/126#issuecomment-185269992>.
>



-- 
R. Ian Bull | EclipseSource Victoria | +1 250 477 7484
http://eclipsesource.com | http://twitter.com/eclipsesource

**Comment by joost-de-vries** [comment]
Any update on this?
I can imagine that it's hard to publish a library for multiple platforms. 
Is it an idea to use travis to build and publish for all supported platforms anything that's pushed to a 3.x branch or 4.x branch?

**Comment by w4-sjcho** [comment]
Any updates on this issue?
