### ISSUE TITLE
release() vs terminateExecution() java.lang.IllegalStateException: * Object(s) still exist in runtime

### ISSUE THREAD

**Issue by PathikDevani** [eclipsesource/J2V8#127]
i am working on android project. I am using android service that run in background 24*7 hour. i want create v8 runtime and after work done close j2v8 complete and again after some time create v8 runtime. 

create j2v8 rutime
```java
V8 runtime = V8.createV8Runtime(context.getApplicationInfo().dataDir);
```

after compete my work close rutime complete
```java
if(runtime != null){
	runtime.release();
}
```

at that time j2v8 exception occur
```java
java.lang.IllegalStateException: 8 Object(s) still exist in runtime
```

how to terminate v8 runtime completely  forcefully ?
how to release all object?
release() vs terminateExecution()

i am using v3.1.0
releaseResources() release all object?
https://github.com/eclipsesource/J2V8/blob/master/src/main/java/com/eclipsesource/v8/V8.java#L300

what is best way to close runtime?

**Comment by irbull** [comment]
This means that you did not release all the V8Objects in the system. If you are shutting down the system and don't care (shutting down the JVM) then you can call `runtime.release(false);` and it won't perform the memory check. However, this means *you are leaking resources*. See [http://eclipsesource.com/blogs/getting-started-with-j2v8/](http://eclipsesource.com/blogs/getting-started-with-j2v8/) for more information on managing native handles.

**Comment by vijayakumar52** [comment]
Hi!
Is there any API available to release all the objects from runtime in a single shot?
