### ISSUE TITLE
j2v8 on Linux 2.6 kernel ?

### ISSUE THREAD

**Issue by webclimber** [eclipsesource/J2V8#128]
Hi there, has anyone been able to run on linux 2.6 ?

I tried version 3.1.1 and got:

Caused by: java.lang.UnsatisfiedLinkError: Could not load J2V8 library. Reasons: 
no j2v8_linux_x86_64 in java.library.path
/home/geobuildci/libj2v8_linux_x86_64.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/geobuildci/libj2v8_linux_x86_64.so)

with 3.1.6 I get

inconsistent module metadata found. Descriptor: com.eclipsesource.j2v8:j2v8_linux_arm64:3.1.6 Errors: bad module name: expected='j2v8_linux_x86_64' found='j2v8_linux_arm64'

My build.gradle contains:

// V8 Integration
compile "com.eclipsesource.j2v8:j2v8:${J2V8Version}"
compile "com.eclipsesource.j2v8:j2v8_macosx_x86_64:${J2V8Version}"
compile "com.eclipsesource.j2v8:j2v8_linux_x86_64:${J2V8Version}"
any suggestions on this will be welcomed

I am testing on

Linux version 2.6.32-279.19.1.el6.x86_64 (mockbuild@ca-build44.us.oracle.com) (gcc version 4.4.6 20120305 (Red Hat 4.4.6-4) (GCC) ) #1 SMP Tue Dec 18 15:04:44 PST 2012

**Comment by piotrtomiak** [comment]
> Caused by: java.lang.UnsatisfiedLinkError: Could not load J2V8 library. Reasons:
> no j2v8_linux_x86_64 in java.library.path
> /home/geobuildci/libj2v8_linux_x86_64.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/geobuildci/libj2v8_linux_x86_64.so)

Looks like your linux system is missing GLibc 2.14. Try installing newer version using your package manager, e.g. for ubuntu: http://askubuntu.com/questions/421642/libc-so-6-version-glibc-2-14-not-found

**Comment by piotrtomiak** [comment]
> inconsistent module metadata found. Descriptor: com.eclipsesource.j2v8:j2v8_linux_arm64:3.1.6 Errors: bad module name: expected='j2v8_linux_x86_64' found='j2v8_linux_arm64'

That's Issue #126

**Comment by irbull** [comment]
Unfortunately we cannot support all these platforms. To help move the project forward, we will only be supporting builds for Android. Others are free to build and support other platforms. I think it's better to be honest about the state of the project than to just leave these issues opened. Please see #441.
