### ISSUE TITLE
3.1.6 on maven for 32bit linux missing

### ISSUE THREAD

**Issue by bergi9** [eclipsesource/J2V8#129]
Could someone compile it and publish it on maven for 32bit linux? Thanks.

**Comment by piotrtomiak** [comment]
I can try to do that. But before I start, @irbull are there any reasons why you haven't got the 32-bit build out? Something is not working or you just haven't tried?

**Comment by piotrtomiak** [comment]
@irbull I've managed to create x86 version of plugin. I wasn't sure, which version of V8 you've used, but I saw 3.26 somewhere, so I've used tip of that branch. Here is approx. script which will create the output.
```bash
mkdir j2v8-build
cd j2v8-build
git clone https://github.com/eclipsesource/J2V8.git
git clone https://chromium.googlesource.com/chromium/tools/depot_tools.git
export PATH=`pwd`/depot_tools:"$PATH"
fetch v8
cd v8
git checkout branch-heads/3.26
gclient sync
make -j10 ia32.release werror=no i18nsupport=off
cd ../J2V8
mvn compile
cd target/classes
javah com.eclipsesource.v8.V8
cp com_eclipsesource_v8_V8.h ../../jni/com_eclipsesource_v8_V8Impl.h
cd ../../jni
gcc -m32 -march=i386 -fPIC -lstdc++ -Iinclude ../../v8/out/ia32.release/obj.target/tools/gyp/libv8_{base,nosnapshot}.ia32.a -I ../../v8/include -I /usr/java/jdk1.6.0_38/include -I /usr/java/jdk1.6.0_38/include/linux -shared -o libj2v8_linux_x86.so -Wl,--whole-archive ../../v8/out/ia32.release/obj.target/tools/gyp/libv8_{base,nosnapshot}.ia32.a -Wl,--no-whole-archive com_eclipsesource_v8_V8Impl.cpp
```

**Comment by piotrtomiak** [comment]
Also, I had to make one change in LibraryLoader#getArchSuffix():
```
static String getArchSuffix() {
        String arch = System.getProperty("os.arch");
-         if (arch.equals("i686")) {
+        if (arch.equals("i686") || arch.equals("i386")) {
            return "x86";
        } else if (arch.equals("amd64")) {
```
I am going to use this plugin in my project for now, however it would be cool if others could make a usage of it. Please let me know whether I can help with publishing it somehow.

**Comment by irbull** [comment]
We will only be actively building/support Android builds. Others are free to create builds for other platforms, but I don't have the cycles to manage/support that. See #441.
