### ISSUE TITLE
register custom Java Object

### ISSUE THREAD

**Issue by lxp270** [eclipsesource/J2V8#131]
I want to extend custom js Object, i.e "var person = new Person(); person.name = 'Lili'; person.say()";
Java class
class Person {
   String name;
   public void say(){
          systerm.io.out.print(name);
   }
}
please help me, Thanks a lot.

**Comment by irbull** [comment]
You cannot 'extend' a Java object in JS with J2V8. However, you can register Java methods and call them from JS. See [http://eclipsesource.com/blogs/2015/06/06/registering-java-callbacks-with-j2v8/](http://eclipsesource.com/blogs/2015/06/06/registering-java-callbacks-with-j2v8/) for details.
