### ISSUE TITLE
the time about V8.createV8Runtime

### ISSUE THREAD

**Issue by fifiand1** [eclipsesource/J2V8#132]
V8 v8 = V8.createV8Runtime();

This code will cost 200-400ms on my Android device when I was initialize the UI. My app have to create 5 runtimes at least.It cost too much time for app. Is there any other way to load the runtime or avoid?

**Comment by irbull** [comment]
You can keep the runtimes around once they are created, so this is a one time cost. This is the cost to initialize V8, so it cannot be avoided.

**Comment by fifiand1** [comment]
so I should create a runtime-objects-pool to manage...

**Comment by irbull** [comment]
Also, check the timing on subsequent V8Runtimes (the first one is likely the most expensive).

As for a object-pool, this may help. However, you may need to clear any state in the runtime. There is no API for that (I guess you could loop through all global JS variables and remove them). If you find a V8 API for reseting an Isolate (the V8 term for Runtime) then I can expose the API in Java.

**Comment by fifiand1** [comment]
Thank you for the answer.
I tried to log the time each Runtime created.They are almost same with the first one.
