### ISSUE TITLE
java.lang.IllegalArgumentException: Invalid key

### ISSUE THREAD

**Issue by aleRocci** [eclipsesource/J2V8#133]
Hi, 
I'm received an "java.lang.IllegalArgumentException" when I've invoked the method https://docs.oracle.com/javase/7/docs/api/javax/script/ScriptEngineFactory.html#getParameter(java.lang.String) with value "THREADING".
This behavior don't respects the Java API.

Stacktrace:
Exception in thread "main" java.lang.IllegalArgumentException: Invalid key
    at lu.flier.script.V8ScriptEngineFactory.getParameter(Native Method)

**Comment by irbull** [comment]
I don't think this is related to the J2V8 project. The referenced APIs are from Oracle and `lu.flier.script`, neither of which are affiliated with this project.
