### ISSUE TITLE
Dynamically loading 32bits and 64bits J2V8 in Windows

### ISSUE THREAD

**Issue by kennygitchen** [eclipsesource/J2V8#134]
hi, 
Is there a way to load 32bits or 64bits of J2V8 depending on the environment?

I would like to just include both 32bits and 64bits of J2V8 in one application build for deployment and let the, for example LibraryLoader.loadLibrary() to decide which versions of J2V8 to load.

cheers, Kenny

**Comment by bergi9** [comment]
The LibraryLoader already decide which architecture to load. Just need to extract the .dll of other architecture and place them into one J2V8.jar. For me i have extract all .dll and .so files and put them into one .jar of J2V8, now i have "multiplattform support".

**Comment by irbull** [comment]
In order to help move this project forward, we will be reducing the scope and only supporting Android. Others are free to build/support other platforms, but I don't have the cycles. Please see #441 for more information.
