### ISSUE TITLE
Way to inspect runtime memory usage.

### ISSUE THREAD

**Issue by Gonzih** [eclipsesource/J2V8#135]
Hello,

First of all I must say thank you for the such solid implementation of v8 bindings for jvm.
Great stuff!

I looked at the source briefly but was unable to find answer to the following question: What is the way to inspect runtime internals (memory footprint, maybe amount of objects in memory). Is it possible to do anything like that without attaching debugger to the runtime? Or is debugger the way to go?

Thanks!

**Comment by DavidRigglemanININ** [comment]
Hey @Gonzih , I've got a PR up (https://github.com/eclipsesource/J2V8/pull/114) that you might want to check out that gives you the ability to do CPU profiling in addition to memory profiling. However, this may only work with the 3.X range of V8 versions. I'm not sure if there are any plans to incorporate my PR into this repo as it's been sitting idle for quite some time and it looks like the 4.X range of V8 versions is in progress.
