### ISSUE TITLE
java.lang.UnsatisfiedLinkError: com.eclipsesource.v8.V8._setFlags

### ISSUE THREAD

**Issue by DavidRigglemanININ** [eclipsesource/J2V8#140]
I understand that 4.0 is not necessarily ready for release yet (my primary intent was to see if V8 4.X series offers better performance), but I figured I'd mention an issue I ran into when trying to build and use what's currently in master. 

Minus the debugging stuff, should code currently in master be compatible with current releases? The error I'm currently seeing is the following:

```
Exception in thread "Thread-1" java.lang.UnsatisfiedLinkError: com.eclipsesource.v8.V8._setFlags(Ljava/lang/String;)V
    at com.eclipsesource.v8.V8._setFlags(Native Method)
    at com.eclipsesource.v8.V8.createV8Runtime(V8.java:148)
```

**Comment by irbull** [comment]
Yes, your code should _generally_ compile and run on the 4.x stream. I say _generally_ because I removed the debug support and a few deprecated method (mostly because they had a typo in them, and there was a new method with the correct name). Maybe when I merged the streams I missed the setFlags functionality. I'll take a look at this.

Thanks for bringing this up!

**Comment by irbull** [comment]
Sorry, I misunderstood this. What have you tried here? Are you using a 4.x JAR with a 3.x native library? There are some new JNI Native Bridge methods that have been added. You need to ensure you are using a 4.x native library.

**Comment by DavidRigglemanININ** [comment]
No, I used the exact same version of V8 that you currently have specified in the version file (4.10.253)

**Comment by DavidRigglemanININ** [comment]
Here's what my build script looks like
g++ -fPIC -shared $BUILD_OPTIONS \
    -o $OUTPUT_LIB \
    -I"$V8_PATH" \
    -I"$V8_PATH/include" \
    -I"$JAVA_HOME/include" \
    -I"$JAVA_HOME/include/$JAVA_OS_INCLUDE_DIR" \
    com_eclipsesource_v8_V8Impl.cpp \
    $V8_BUILD/libv8_libbase.a \
    $V8_BUILD/libv8_libplatform.a \
    $V8_BUILD/libv8_base.a \
    $V8_BUILD/libv8_nosnapshot.a \
    -std=c++11

**Comment by irbull** [comment]
That's strange. That's pretty much my build script (I have the ICU stuff there, but I doubt that's causing this). The missing JNI method (setFlags) looks like it's in master [here](https://github.com/eclipsesource/J2V8/blob/master/jni/com_eclipsesource_v8_V8Impl.cpp) line 256. It was introduced with this commit https://github.com/eclipsesource/J2V8/commit/6451567ac93e1fba7335f167bd42eb8e57af18a8 Can you ensure you have that?

**Comment by DavidRigglemanININ** [comment]
This is odd. It doesn't seem like it's an issue linking to V8 but instead an issue linking with the com_eclipsesource_v8_V8Impl.cpp file. I double checked and I do see the setFlags declaration in the CPP file.

**Comment by DavidRigglemanININ** [comment]
So I modified my build script to be exactly the same as yours (minus the ICU stuff) and it built fine the same way as before. However, that didn't help. So I created a standalone Java project and manually referenced the built jar and had an extremely simple test
`import com.eclipsesource.v8.V8;

public class Main {

    public static void main(String[] args) {
        V8 v8 = V8.createV8Runtime(null);
        System.out.println("It worked");
    }
}
`
And the result was the same as before with the following exception:
Exception in thread "main" java.lang.UnsatisfiedLinkError: com.eclipsesource.v8.V8._setFlags(Ljava/lang/String;)V
	at com.eclipsesource.v8.V8._setFlags(Native Method)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:148)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:122)

**Comment by DavidRigglemanININ** [comment]
Attaching problem jar in case that is helpful
[j2v8_macosx_x86_64-4.0.0-SNAPSHOT.jar.zip](https://github.com/eclipsesource/J2V8/files/193715/j2v8_macosx_x86_64-4.0.0-SNAPSHOT.jar.zip)

**Comment by mithung** [comment]
Hi ,

I am getting below error. 

Exception in thread "main" java.lang.IllegalStateException: J2V8 native library not loaded (j2v8-macosx-x86_64/j2v8-macosx-x86_64)
	at com.eclipsesource.v8.V8.checkNativeLibraryLoaded(V8.java:257)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:153)
	at com.eclipsesource.v8.V8.createV8Runtime(V8.java:129)

**Comment by irbull** [comment]
This is a very old version of J2V8. I'm closing this issue. If this is still a problem with a newer version of J2V8, please feel free to reopen.
