### ISSUE TITLE
What is the need of release()?

### ISSUE THREAD

**Issue by cirilla** [eclipsesource/J2V8#147]
Hi

I'm building a library, part of it I have a multiple calls to JS code.
The problem is that I don't know when to call to release because I don't know when the end user
will stop using the JS logic.
in my library there is no 'release' function, and I don't want to create new runtime and then release it, every time the end user will call to the function that requires JS code execution.

if I will create a runtime and won't ever call to release() what will happen to the application?

Thanks

**Comment by irbull** [comment]
Releasing objects in Java will not release them in JavaScript. You need to release objects when you no longer need them in Java. If you created an object you need to release it (unless it is the object being returned to V8). Furthermore, if you receive an object from a call to V8 (such as `executeScript` or `get`) you need to release that.

**Comment by ysyyork** [comment]
@irbull Hi, Thanks for this great library. But btw is there one function that can force release all the resources within the current context?
