### ISSUE TITLE
node-inspector debuger support

### ISSUE THREAD

**Issue by midzelis** [eclipsesource/J2V8#148]
What would it take to support the node-inspector debugger? https://github.com/node-inspector/node-inspector

This debugger is one of the best for node, since it allows you to use the normal chrome (Blink) debugger. It also includes a console, a CPU/heap profiler, and even allows you to save modifications back to the file. 

I would love to see this debugger supported!

**Comment by irbull** [comment]
We are limiting the scope of this project to V8 on Android only. If someone would like to maintain a downstream project that includes NodeJS support, I would support that. See #441 for more information. I'm closing this as out of scope. 

For what it's worth, I think it's a great idea, but I want to be honest about what I can realistically maintain.
