### ISSUE TITLE
V8.createNodeJS missing (?)

### ISSUE THREAD

**Issue by tverbeke** [eclipsesource/J2V8#150]
The EclipseCon NA slides on Node4J p.25 (https://www.eclipsecon.org/na2016/sites/default/files/slides/EclipseCon2016.pdf) mention
```
NodeJS node = V8.createNodeJS(v8);
```
but I don't seem to find any trace of this here on Github. Can you provide a pointer / publish a branch?

**Comment by irbull** [comment]
I was finalizing the API. The code is now on GitHub (commit 6e0a28fe68f24614bb879fd6116f1dc5a29b3069). I will be creating builds for this work for Windows / Mac / Linux.
