### ISSUE TITLE
How to build native code?

### ISSUE THREAD

**Issue by midzelis** [eclipsesource/J2V8#151]
What are the instructions on how to build the native code on all the different arches? 

4.0 only has android version available on maven central. Is this the current release? Could the other arches be built for 4.0?

**Comment by irbull** [comment]
I've been working on this lately. I'm currently trying to use the node.js build to make this easier. I will update this issue when I have this work completed. Sorry for the delay.

**Comment by irbull** [comment]
Here are the build steps I use on our Jenkins server to build this for Linux:
```
export CCFLAGS="${CCFLAGS} -fPIC" 
export CXXFLAGS="${CXXFLAGS} -fPIC" 
export CPPFLAGS="${CPPFLAGS} -fPIC" 
sh ./build-node.sh
cd jni
g++ -I../node -I../node/deps/v8 -I../node/deps/v8/include -I../node/src -I /data/jenkins/tools/hudson.model.JDK/jdk-7/include/ -I /data/jenkins/tools/hudson.model.JDK/jdk-7/include/linux  com_eclipsesource_v8_V8Impl.cpp -std=c++11 -fPIC -shared -o libj2v8_linux_x86_64.so -Wl,--start-group ../node/out/Release/libnode.a ../node/out/Release/libv8_libbase.a ../node/out/Release/libv8_libplatform.a ../node/out/Release/libv8_base.a ../node/out/Release/libv8_nosnapshot.a ../node/out/Release/libuv.a ../node/out/Release/libopenssl.a ../node/out/Release/libhttp_parser.a ../node/out/Release/libgtest.a ../node/out/Release/libzlib.a ../node/out/Release/libcares.a -Wl,--end-group -lrt
```
This will first checkout and build node.js as a library. Then it will be J2V8.
After this you can do a `mvn clean verify` from the root of project to build the Java parts.

**Comment by bennylut** [comment]
Thank you very much - Building it now, will it work with node modules? (i.e., node_modules directory residing in the cwd or maybe even in the classpath?)

**Comment by irbull** [comment]
Yes, it appears to. Please file issues if you find them. I have tested some simple ones such as express using:

```
package com.eclipsesource.node;
import java.io.File;
import com.eclipsesource.v8.NodeJS;
public class Node {
    public static void main(final String[] args) throws Exception {
        NodeJS node = NodeJS.createNodeJS();
        node.require(new File("./myexpress.js"));
        while (node.isRunning()) {
            node.handleMessage();
        }
    }
}
```
In this case, `myexpress.js` was the hello world example from [1].

[1] http://expressjs.com/en/starter/hello-world.html

**Comment by bennylut** [comment]
Thanks - I successfully compiled it and will test it now. 
BTW your build command missed the jdk includes (for jni.h and such) - here is the full command set for others future reference: 
```bash
export JAVA_INCLUDE="$(dirname $(readlink -f $(which javac)))/../include"
export CCFLAGS="${CCFLAGS} -fPIC" 
export CXXFLAGS="${CXXFLAGS} -fPIC" 
export CPPFLAGS="${CPPFLAGS} -fPIC" 
sh ./build-node.sh
cd jni
g++ -I$JAVA_INCLUDE -I$JAVA_INCLUDE/linux -I../node -I../node/deps/v8 -I../node/deps/v8/include -I../node/src -I /data/jenkins/tools/hudson.model.JDK/jdk-7/include/ -I /data/jenkins/tools/hudson.model.JDK/jdk-7/include/linux  com_eclipsesource_v8_V8Impl.cpp -std=c++11 -fPIC -shared -o libj2v8_linux_x86_64.so -Wl,--start-group ../node/out/Release/libnode.a ../node/out/Release/libv8_libbase.a ../node/out/Release/libv8_libplatform.a ../node/out/Release/libv8_base.a ../node/out/Release/libv8_nosnapshot.a ../node/out/Release/libuv.a ../node/out/Release/libopenssl.a ../node/out/Release/libhttp_parser.a ../node/out/Release/libgtest.a ../node/out/Release/libzlib.a ../node/out/Release/libcares.a -Wl,--end-group -lrt
```

**Comment by irbull** [comment]
Mine had it, it was just hardcoded to `-I /data/jenkins/tools/hudson.model.JDK/jdk-7/include/` which probably only works on my jenkins server. ;) You can likely remove that part from your command.

**Comment by irbull** [comment]
BTW, if you now run `mvn clean verify`, it should run the full J2V8 test suite. Please let me know if this works. You'll be the first person (besides myself) who compiled J2V8 against node.

**Comment by bennylut** [comment]
run `mvn clean verify` and all tests passed :+1: 

BTW I was amazed to see that compressed, the whole library (including the `.so` native) took less than 5m, this means that it can actually be wrapped inside a compressed jar (and load it using native-utils's `loadLibraryFromJar` - https://github.com/adamheinrich/native-utils) for a relatively very small and self contained maven dependency ( but probably you already know it :) and it is just me that amazed that so much functionality requires only 5m..)

**Comment by irbull** [comment]
Yes, I was amazed by that too because the intermediate .so files took up over 200mb on my system, and when I tried to build all architectures for V8, it ate 20Gb (I think it was fetching a lot of other things then too). The only problem is that if you want a universal jar (other platforms) then you need each .so file.

**Comment by bennylut** [comment]
> The only problem is that if you want a universal jar (other platforms) then you need each .so file.

Right, but I think that an OS depended jar with a maven profile for each OS is a much preferred alternative - but maybe is just me...

**Comment by irbull** [comment]
I've added the build instructions for both Linux and Mac. I'll add windows instructions once I try this on a Windows machine.

**Comment by winston01** [comment]
Hi @irbull 

Can you please update README.md with the code of @bennylut from May 11 2016? It could save some effort for the newcomers (like me) trying to build on Linux.

**Comment by deprilula28** [comment]
@irbull How can I build it in windows?

**Comment by chakritw-q** [comment]
@irbull @deprilula28 
Here's my latest progress:

1. I dowloaded Node.JS 7.9.0 source into D:\Libraries\node-v7.9.0, and built it using commands:
  
`> vcbuild.bat vc2015 debug x64 dll nosign`
and
`> vcbuild.bat vc2015 release x64 dll nosign `

2. Then I called winbuild.bat script in J2V8 project folder

`> winbuild.bat`

3. Then I opened the generated j2v8.sln in MS Visual Studio 2015 and edit project settings to link with built Node.JS (release)

Configuration: Debug/x64

`VC++ Directories=$(VC_LibraryPath_x64);C:\Program Files (x86)\Windows Kits\8.1\Lib\winv6.3\um\x64;D:\Libraries\node-v7.9.0\Release;D:\Libraries\node-v7.9.0\Release\lib;D:\Libraries\node-v7.9.0\build\Release;D:\Libraries\node-v7.9.0\build\Release\lib`

`Additional Include Directories=C:\Program Files\Java\jdk1.8.0_45\include\win32;C:\Program Files\Java\jdk1.8.0_45\include;D:\Libraries\node-v7.9.0\deps\v8\include;D:\Libraries\node-v7.9.0\deps\v8\include\libplatform;D:\Libraries\node-v7.9.0;D:\Libraries\node-v7.9.0\src;%(AdditionalIncludeDirectories)`

3. I tried building j2v8 project. It failed with errors including:

`LNK2038	mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in com_eclipsesource_v8_V8Impl.obj	libj2v8	D:\Libraries\J2V8\jni\v8_base_0.lib(ic-x64.obj)`


Here is full build log:

[build-20170423_1.log.txt](https://github.com/eclipsesource/J2V8/files/949405/build-20170423_1.log.txt)

**Comment by chakritw-q** [comment]
@irbull @deprilula28 
Good news, I just changed j2v8 project configuration from Dynamic library (.dll) to Static library (.lib), and now the rebuild succeeded! We've got the file libj2v8_win32_x86_64.dll at last.

**Comment by deprilula28** [comment]
The way I ended up doing it was through maven. Thanks for the responses though!

**Comment by irbull** [comment]
We have a new build tool for the entire project. I will check/update our build instructions. I have bug #40 to track that work. Closing this as a duplicate.
