### ISSUE TITLE
Module Loader

### ISSUE THREAD

**Issue by midzelis** [eclipsesource/J2V8#152]
I'm in need of a node.js style module loader for J2V8. I'm thinking the https://github.com/requirejs/r.js would be a good starting point as it already works with nashorn/rhino. 

It seems like it would be relatively straightforward to add in the proper stubs so that it this loader could also be used by J2V8. 

What do you think of this approach, or do you already have plans to support node modules in some other way?

**Comment by midzelis** [comment]
I have a working require() module loader now. Let me know if anyone is interested.

**Comment by irbull** [comment]
Cool! I'm actually building J2V8 using node (instead of just V8 now) and I'm working on exposing some of nodes API (such as require) with J2V8. I would love to see how you did this with require.js.

**Comment by TheLarkInn** [comment]
Also feel free to checkout Webpack as a module bundler and loader.

**Comment by irbull** [comment]
The Node.js work is now available in Maven Central. http://eclipsesource.com/blogs/2016/07/20/running-node-js-on-the-jvm/ @midzelis If you have any information about how you used require(), feel free to document it here. I'm going to close this issue.

**Comment by fifiand1** [comment]
@midzelis I'm interesting about use require.js on J2V8. Would you give me any helps?
