### ISSUE TITLE
Could not load J2V8 library

### ISSUE THREAD

**Issue by fifiand1** [eclipsesource/J2V8#153]
在小米5手机上,缺少so库
Caused by: java.lang.UnsatisfiedLinkError: Could not load J2V8 library. Reasons: 
    dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.sunline.centuryclub-1/base.apk"],nativeLibraryDirectories=[/data/app/com.sunline.centuryclub-1/lib/arm, /data/app/com.sunline.centuryclub-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]] couldn't find "libj2v8_android_armv8l.so"

能否提供一个完整的(所有cpu架构,包括32位和64位)so库?

**Comment by irbull** [comment]
What device are you trying this on?

**Comment by fifiand1** [comment]
The device what I use is MI5(小米5)

**Comment by fifiand1** [comment]
I can't find arm64
Caused by: java.lang.UnsatisfiedLinkError: Could not load J2V8 library. Reasons: 
                                           	dlopen failed: "/data/app/com.example.tinytest-1/lib/arm64/libj2v8_android_armv7l.so" is 32-bit instead of 64-bit

**Comment by parahall** [comment]
The problem happens when Targeting SDK 23 only.

**Comment by irbull** [comment]
64-bit builds are now available. 

In gradle:
`implementation 'com.eclipsesource.j2v8:j2v8:5.0.103@aar'`
`implementation 'com.eclipsesource.j2v8:j2v8:4.8.4@aar'`

or in a maven pom

```
<dependency>
  <groupId>com.eclipsesource.j2v8</groupId>
  <artifactId>j2v8</artifactId>
  <version>4.8.4</version>
  <type>aar</type>
</dependency>
```
or
```
<dependency>
  <groupId>com.eclipsesource.j2v8</groupId>
  <artifactId>j2v8</artifactId>
  <version>5.0.103</version>
  <type>aar</type>
</dependency>
```
