### ISSUE TITLE
Can not create an object out of typescript evaluated code.

### ISSUE THREAD

**Issue by hay12396** [eclipsesource/J2V8#154]
Hello,

I am trying to use this great library in one of my projects.

What am i doing wrong?

**Comment by hay12396** [comment]
I have managed to create the object, but there is a bug in one of the functions.

`RipClass.prototype.setupResourceLists = function () {`
`        var allResources = this.rManager.getAllResources();`
`        for (var i = 0; i < allResources.size(); i++) {`
`            if (allResources[i].getIsText()) {`
`                this.textResources.add(allResources[i]);`
`            }`
`        }`
`    };`

When rManager is a V8Object i have created and the getAllResources() function is a JavaCallBack function:

`public V8Array getAllResources() {`
`        if(mResourceList.length() == -1)`
`            return null;`
`        return mResourceList;`
`    }`

The mResourceList is a V8Array, and i'm constructing him like this:

`V8Object v8res = new V8Object(runtime);`
`registerV8ResourceCallbacks(v8res, res);`
`mResourceList.push(v8res);`

The registerV8ResourceCallbacks just set JavaCallbacks for each V8Object.

The getAllResource function is getting called, but for some reason it returns an undefined object.

This is the Exception i receive:

> undefined:12: TypeError: undefined is not a function
        for (var i = 0; i < allResources.size(); i++) {
                                         ^
TypeError: undefined is not a function
    at RipClass.setupResourceLists (<anonymous>:12:42)
    at RipClass.onStart (<anonymous>:131:14)
com.eclipsesource.v8.V8ScriptExecutionException

**Comment by midzelis** [comment]
Looks like getAllResources() returned null. which meant that mResourceList.length() == 1. you should return an empty array when mResourceList.length() ==1.

**Comment by hay12396** [comment]
For anyone who will look for this later, for some reason, after doing a clean and rebuilt of the project the issue is gone.

**Comment by gosia-eclipsesource** [comment]
@hay12396 Great, thanks for coming back with the update.
