### ISSUE TITLE
integration of j2v8  with  tesseract library is not working on MI tab 2 device

### ISSUE THREAD

**Issue by yogeshDube** [eclipsesource/J2V8#155]
case 1: I have added libj2v8_android_x86_64.so library in folder x86 and its working fine.

case 2: If I added Tesseract lib(OCR)  in android project, Project working fine.

Case 3 : When I **integrate these two lib in an single project, It give following error in MI tab 2.**
But it works mostly devices like-Saamsung Note 3,4 , ASUS phone, etc.

`dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.example.testtab-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.testtab-2/lib/x86_64, /vendor/lib64, /system/lib64]]] couldn't find "libj2v8_android_x86_64.so"
at com.eclipsesource.v8.LibraryLoader.loadLibrary(LibraryLoader.java:71)`

**Comment by irbull** [comment]
Can you try adding it in the x86_64 directory? You placed it in the x86 directory. On Android you can load 64bit binaries from 32 bit builds, but only if all libs are 32 bit.

**Comment by yogeshDube** [comment]
yes I have tried to add it in x86_64 directory. But still its giving me following error:

```
Caused by: java.lang.UnsatisfiedLinkError: Could not load J2V8 library. Reasons: 
dlopen failed: "/data/app/com.paramatrix.conflux.ui.android.app-1/lib/x86_64/libj2v8_android_x86_64.so" is 32-bit instead of 64-bit.


![libs-dirstructure](https://cloud.githubusercontent.com/assets/19221385/15172817/e8565d76-1775-11e6-9816-e1e67ec320a7.png)

```

**Comment by irbull** [comment]
Oh sorry, yes this is on _Android_. We are currently not building x64 bit binaries for Android. Is there a 32 bit version of Tesseract you can use?

**Comment by yogeshDube** [comment]
yes I have used both the 32 and 64 bit version of tesseract but problem remains same.
So is you have any plan to build  x64 bit binaries for Android?

**Comment by yogeshDube** [comment]
can you please tell me...can I build j2v8 library by ndk?
