### ISSUE TITLE
Deliver 4.x stream to Maven Central

### ISSUE THREAD

**Issue by AcaudalAoudad** [eclipsesource/J2V8#158]
I'm new to using this project, but so far it's been amazing coming from Rhino, but I'm having an issue with unit testing.

I started by using a compile import:

`compile 'com.eclipsesource.j2v8:j2v8:4.1.0@aar'`

This works for the application, but testing failed with:

`java.lang.IllegalStateException: J2V8 native library not loaded.`
`Caused by: java.lang.UnsatisfiedLinkError: Could not load J2V8 library. Reasons: 
	no j2v8_macosx_x86_64 in java.library.path`

So I added a test-only dependency with the explicit import for OS X via:

`testCompile 'com.eclipsesource.j2v8:j2v8_macosx_x86_64:3.1.6' `

And this worked, but the problem is I can't take advantage of 4.x features with that dependency, and there doesn't seem to be an OS X specific 4.0 import I can use.

Using the following doesn't seem to work either (I get the same problem with being unable to load the native library):

`testCompile 'com.eclipsesource.j2v8:j2v8:4.1.0'`

Is there a way I can get the OS X library loaded?

**Comment by irbull** [comment]
I am now building MacOS native libs on Travis-ci and publishing them [here](https://github.com/eclipsesource/J2V8/releases). If you download the .dylib and add it to your `-Djava.library.path` during your tests, this should work.

**Comment by AcaudalAoudad** [comment]
Thanks, setting that up got it to find the correct native library, but now I'm getting an error when it attempts to load:

`java.lang.IllegalStateException: J2V8 native library not loaded.`
`...`
`Caused by: java.lang.NoSuchMethodError: disposeMethodID`

Does that mean I grabbed an incompatible version of the library from your link?

**Comment by irbull** [comment]
Interesting. Did you grab 4.1 from Maven (the one for Android) and use that with the latest .dylib file? This should _in theory_ work. disposeMethodID was added in e375fbb021871503b07b32e534990c06362377db which should be in 4.1.0.

**Comment by AcaudalAoudad** [comment]
You're absolutely right, sorry it was my mistake. I had attempted a fix that involved changing the `testCompile` dependency to 4.0 earlier in the day, but didn't discard the changes until after I tried the latest library in the link. 

I think I might use the library built from the 4.1 commit to make sure that tests aren't passing (or failing) on my PC (which uses the library from the link) that wouldn't on the device (which uses the library in the Maven build), is that a valid concern?

**Comment by irbull** [comment]
The library in Maven central is built from the 4.1 commit, but if you feel more comfortable use the native library and build the Java stuff from the commit yourself. For the most part, if things get up and running you should be in good shape -- unless V8 starts failing, but the tests (and J2V8 for that matter) can't really help you here.

**Comment by irbull** [comment]
4.x is now available in Maven central for all supported platforms. http://eclipsesource.com/blogs/2016/07/20/announcing-j2v8-4/
