### ISSUE TITLE
The constructor V8Object(V8,Object) does not use the given object

### ISSUE THREAD

**Issue by bennylut** [eclipsesource/J2V8#161]
the code for this constructor is: 

```java
public V8Object(final V8 v8, final Object data) {
        super(v8);
        if (v8 != null) {
            this.v8.checkThread();
            objectHandle = initialize(this.v8.getV8RuntimePtr(), data);
        }
    }
```
but the code for the initialize method is:
```java
protected long initialize(final long runtimePtr, final Object data) {
        long objectHandle = v8.initNewV8Object(runtimePtr);
        v8.addObjRef();
        released = false;
        return objectHandle;
    }
```

Does this method was intended to  copy the given object to the NodeJS side? If so, if you planed doing so using reflection I can contribute a working code if you like.

UPDATE: 
> I can contribute a working code if you like

I now see that I have a problem with primitives with this code - I didn't find any way to create a primitive V8Value from the java side (I can encode the whole object creation as a script and run it - this what I will do for now..)

**Comment by irbull** [comment]
This constructor should have been protected. It's used internally to pass some context for other types of Objects (in particular V8Functions). I will make this method protected.

As for the idea of using reflection, this is worth a try. There are some utility methods for converting Maps / Lists to V8Objects / V8Arrays. We could do something similar for Strings (JSON Strings) or generic objects using reflection. 

The idea of the J2V8 core is just the JNI bindings to V8. Utility methods and other helpers should live outside the core. See the package `com.eclipsesource.v8.utils`.

**Comment by bennylut** [comment]
>This constructor should have been protected. It's used internally to pass some context for other types of Objects (in particular V8Functions). I will make this method protected.

I see, thank you for the clerification

> As for the idea of using reflection, this is worth a try. There are some utility methods for converting Maps / Lists to V8Objects / V8Arrays. We could do something similar for Strings (JSON Strings) or generic objects using reflection.

What do you suggest to be the preferred course of action when passing objects to NodeJS? 
1. serialize the objects into json on the java side and then pass them to the `JSON.parse` method on the js side? (this is what I am currently does)
2. serialize the java object directly into V8Object - in that case I still does not know how one can create a primitive V8Object (e.g., a number or a string) without resorting to script execution. Using scripts to create primitive objects will cause many small objects to be copied back and forth through the jni bridge and probably hurt performance.
3. other option?
