### ISSUE TITLE
Native library crashes VM when passed a receiver that's been released

### ISSUE THREAD

**Issue by Mizumi** [eclipsesource/J2V8#166]
Hello! First off, I just want to say that J2V8 is a super awesome library. ;D 

While I was adding V8 support to one of my frameworks, I got hit in the face by a few VM crashes caused by J2V8. After some debugging, it appears that when invoking a V8Function using a receiver  that has already been released, the native library causes the entire Java VM to crash. The following snippet executed inside a JUnit test consistently demonstrated this behavior on my OS X system:

    V8 v8 = V8.createV8Runtime();
    V8Object object = v8.executeObjectScript("var x = { a: function() { return 10; } }; x;");
    V8Function function = (V8Function) object.get("a");
    object.release();
    function.call(object, new V8Array(v8));

It's easy enough to check if the object has already been released before passing it into the function call, but there was no documentation and no errors that indicated that this check should be done. Did I miss something in the docs, or is this a new issue?

**Comment by irbull** [comment]
First let me say thank-you for this excellent bug report! 

No, a JVM crash is never the correct behaviour. We typically check `isDisposed` before an object is used but it appears that it was missed in this case. I will fix this.

Thanks again for the snippet!

**Comment by Mizumi** [comment]
Glad to hear this report was helpful; thanks so much for taking the time to work on this!
