### ISSUE TITLE
Using Require.js with J2V8

### ISSUE THREAD

**Issue by renaudpawlak** [eclipsesource/J2V8#167]
I am trying to use a Require.js module with J2V8.

What I do is the following:

```java
V8 evalJsRuntime = V8.createV8Runtime();
StringBuilder bundle = new StringBuilder();
bundle.append(FileUtils.readFileToString(new File("lib/require.js")) + "\n"); // latest version
bundle.append("requirejs(['path/to/my/module.js'] , function(module) {});" + "\n");
evalJsRuntime.executeScript(bundle.toString());
```

However when I run this code, nothing happens. It seems that the ``requirejs`` call is simply void. It is weird because when I mispell the module name on purpose, nothing happens either, yet require.js should complain that the file does not exist.

I have tried exactly the same code loaded on Chrome in a web page and it works fine...

Any clue about what can happen? Is it my version or V8? Or should I evaluate some lib first? BTW, do you know how to make V8 ES6 compatible in this context?

Thanks in advance.

**Comment by fdummert** [comment]
Just to make sure: you tried it with r.js, did you (require.js itself is for browsers only)?

**Comment by renaudpawlak** [comment]
I think I did, but actually I don't remember what happened. In any case, I guess that the best way for me would be to use the Node.js features of J2V8, (and then I don't need Require.js anymore). However, I cannot figure out how to use J2V8 version 4+ without recompiling it all (hence my question #168).

**Comment by irbull** [comment]
See #152, it appears to be working. check your working directory, is "lib/require.js" relative the current working directory?
