### ISSUE TITLE
V8Array is null (4.1.0)

### ISSUE THREAD

**Issue by activetheory** [eclipsesource/J2V8#173]
Hi, 

Thanks so much for the awesome library. I had everything working with version 3.1.6, but when I updated to 4.1.0 the app crashed because V8Arrays coming through were null.

I've isolated to some very simple code:

`var array = new Float32Array(5);
for (var i = 0; i < 5; i++) array[i] = i / 1000;
testArray(array);`

`public void testArray(V8Array array) {
     int len = array.length();
}`

This would crash with:
`FATAL EXCEPTION: GLThread 778
                                                                      Process: net.activetheory.gles2, PID: 6686
                                                                      undefined:77: Attempt to invoke virtual method 'int com.eclipsesource.v8.V8Array.length()' on a null object reference
                                                                      testArray(array);`

Thanks in advance!

**Comment by irbull** [comment]
Reproducible test case:
```
  @Test
    public void testInvokeCallbackWithTypeArrayAsParameter() {
        class MyCallback {
            public int testArray(final V8Array array) {
                return array.length();
            }
        }
        MyCallback callback = new MyCallback();
        v8.registerJavaMethod(callback, "testArray", "testArray", new Class[] { V8Array.class });

        int result = v8.executeIntegerScript("\n"
                + "var array = new Float32Array(5);\n"
                + "for (var i = 0; i < 5; i++) \n"
                + "  array[i] = i / 1000; "
                + "testArray(array);");

        assertEquals(5, result);
    }
```
Thank-you for this bug report. I'm looking at it now.
