### ISSUE TITLE
Can't build for Ubuntu 16.04

### ISSUE THREAD

**Issue by adpolican** [eclipsesource/J2V8#176]
Ran the code for linux installation as a bash script, keep getting errors.

```
make[1]: Leaving directory '/home/andrew/REUIOT/J2V8/node/out'
ln -fs out/Release/node node
cp: cannot stat '/data/jenkins/node': No such file or directory
com_eclipsesource_v8_V8Impl.cpp:11:17: fatal error: jni.h: No such file or directory
compilation terminated.
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------

[INFO] Total time: 0.059 s
[INFO] Finished at: 2016-06-24T15:49:40-05:00
[INFO] Final Memory: 11M/40M

[INFO] ------------------------------------------------------------------------

[ERROR] The goal you specified requires a project to execute but there is no POM in this directory (/home/andrew/REUIOT/J2V8/jni). Please verify you invoked Maven from the correct directory. -> [Help 1]

[ERROR] 

[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.

[ERROR] Re-run Maven using the -X switch to enable full debug logging.

[ERROR] 

[ERROR] For more information about the errors and possible solutions, please read the following articles:

[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MissingProjectException

Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

```

**Comment by winston01** [comment]
See issue #151 for the solution of '/data/jenkins/node': No such file or directory : 
https://github.com/eclipsesource/J2V8/issues/151#issuecomment-218306914

**Comment by rdemirkoparan** [comment]
remove line "cp -r /data/jenkins/node ." and try again. 

Please check below commands, it should work for you..

export CCFLAGS="${CCFLAGS} -fPIC"
export CXXFLAGS="${CXXFLAGS} -fPIC"
export CPPFLAGS="${CPPFLAGS} -fPIC"
sh ./build-node.sh
cd jni
g++ -I../node -I../node/deps/v8 -I../node/deps/v8/include -I../node/src -I /usr/jdk1.7/include/ -I /usr/jdk1.7/include/linux  com_eclipsesource_v8_V8Impl.cpp -std=c++11 -fPIC -shared -o libj2v8_linux_x86_64.so -Wl,--whole-archive ../node/out/Release/libnode.a  -Wl,--no-whole-archive -Wl,--start-group ../node/out/Release/libv8_libbase.a ../node/out/Release/libv8_libplatform.a ../node/out/Release/libv8_base.a ../node/out/Release/libv8_nosnapshot.a ../node/out/Release/libuv.a ../node/out/Release/libopenssl.a ../node/out/Release/libhttp_parser.a ../node/out/Release/libgtest.a ../node/out/Release/libzlib.a ../node/out/Release/libcares.a -Wl,--end-group -lrt -D NODE_COMPATIBLE=1

**Comment by irbull** [comment]
The build scripts have changed significantly since this bug was opened. I will be updating the build instructions (see #40).
