### ISSUE TITLE
Whats up with the releases? 

### ISSUE THREAD

**Issue by midzelis** [eclipsesource/J2V8#184]
Why do you have so many releases (on github)? And why are they named untagged-LONGNUMBER but that is actually a tag? 

Also, can I make a request that you use actual 'git tags' every time you make a major version, so that I can easily get back to that code if I have to? 

Thanks!

**Comment by irbull** [comment]
Regarding the [releases](https://github.com/eclipsesource/J2V8/releases), yeah that sucks. They are the binaries built by travis-ci. I couldn't find any other way to sync the binaries back here and I wanted to give people a chance to download the native libs. If you have any suggestions, please let me know.

I will start tagging real releases. You should be able to find the commits that say "release x.y" (where I change the pom file to the actual release), but yes, tags are better.
