### ISSUE TITLE
Jasmine and Bluebird JS scripts not working after upgrading from 3.1 to 4.5

### ISSUE THREAD

**Issue by DavidRigglemanININ** [eclipsesource/J2V8#186]
If J2V8 3.1, we had to add the following line to our code prior to loading the JS files (done via executeVoidScript): 
`v8.add("window", v8); // makes bluebird and jasmine happy`

Due to some potential memory leak issues, I was looking to upgrade to 4.5. However, upon doing so, I now get errors with bluebird complaining that "window.document is not defined" and jasmine complains with the following error: 
```
ReferenceError: jasmineRequire is not defined
window.jasmineRequire = window.jasmineRequire || {};
```

Does the migration from 3.1 to 4.5 require additional changes I'm not aware of and is not fully backwards compatible?

**Comment by irbull** [comment]
No, there should not be additional changes required. I guess you are trying to register 'window' as the name of the global scope. Can you try setting the global alias when you create the runtime. `V8.createV8Runtime("window")`. This isn't new to 4.5, but maybe something in V8 has changed between 3.x and 4.x in how they reference global objects.

**Comment by DavidRigglemanININ** [comment]
That solved the problem. Thanks!
