### ISSUE TITLE
Android平台，现在使用哪个包是最合适的？？？

### ISSUE THREAD

**Issue by noear** [eclipsesource/J2V8#191]
我之前使用的是：
compile 'com.eclipsesource.j2v8:j2v8:3.1.6@aar'

现在要是使用：
compile 'com.eclipsesource.j2v8:j2v8:4.5.0@aar'
包，太大了。。。

有没有小巧一些；适合Android的？？

**Comment by krudos** [comment]
https://mvnrepository.com/artifact/com.eclipsesource.j2v8/j2v8

**Comment by ximencx** [comment]
@noear  活捉多多猫作者~~插件基于j2v8做的么？

**Comment by irbull** [comment]
Google translate tells me: "Live catching a lot of cat authors ~ ~ plug-in based on j2v8?" I'm not sure that's correct. Sorry, but I have to close this.

**Comment by ximencx** [comment]
no thanks，it is translated means i meet person named a lot cat on their。google
translate is humerus 😂😂
