### ISSUE TITLE
Extract FloatBuffer from V8Array.getBytes

### ISSUE THREAD

**Issue by activetheory** [eclipsesource/J2V8#192]
Hi,

Just updated to 4.5 and it's great -- thanks so much for the work on this project.

My use case is that I am passing a Float32Array from JavaScript to Java which is immediately uploaded to OpenGL with `bindBufferData`.

My previous solution was to iterate `array.getDoubles` and manually cast to `float` in a new array. Since 4.0+ has new Typed Array features, I feel like there is a way I'm missing to get the data from the incoming `V8Array` and turn it into the necessary `FloatBuffer` for OpenGL.

This is where my understanding reaches its end but this approach is accepted by OpenGL, but the data is wrong and rendering incorrectly:

```
int len = array.length();
int size = len * 4;
ByteBuffer bb = ByteBuffer.allocateDirect(size);
bb.order(ByteOrder.nativeOrder());
bb.put(array.getBytes(0, len));
bb.position(0);

FloatBuffer fb = bb.asFloatBuffer();
```

Thanks in advance.

**Comment by mpost** [comment]
J2v8 will get even better support for TypedArrays and ArrayBuffers with the upcoming 4.5.1 release. There will be concrete types for each typed array so your example will change to:

```java
Float32Array float32Array = // retrieved via V8ObjectUtil
ByteBuffer buffer = float32Array.getByteBuffer();
```

@irbull will be able to provide even more insights.

**Comment by irbull** [comment]
With J2V8 4.6 you can now access the the backing byte buffer used for TypedArrays:
```
    @Test
    public void testAccessArrayBuffer_Float32rrayView() {
        V8ArrayBuffer buffer = (V8ArrayBuffer) v8.executeScript("var buf = new ArrayBuffer(4); var floats = new Float32Array(buf); floats[0] = 7.7; buf");

        FloatBuffer floatBuffer = buffer.getBackingStore().asFloatBuffer();

        assertEquals(1, floatBuffer.limit());
        assertEquals(7.7, floatBuffer.get(0), 0.00001);
        buffer.release();
    }
```
In this case, you are creating an ArrayBuffer in JavaScript and then accessing the values directly in Java.
