### ISSUE TITLE
SIGILL crash

### ISSUE THREAD

**Issue by krudos** [eclipsesource/J2V8#197]
i am getting a 
A/libc: Fatal signal 4 (SIGILL) at 0x00001194 (code=0), thread 4500

but only on a intel android device

**Comment by irbull** [comment]
Are you getting this consistently? Does J2V8 work at all on that device? Can you provide any information about when this happens and what device this is?

**Comment by krudos** [comment]
it happen consistenly when i call twice a method that concat some strings, the second time its crash. j2v8 its working, only with that function crash.  the device is a AOU U107 with  intel atom z3735g procesor android 4.4.4 with 1 gb ram . other functions doesnt give problems. let me see if i can extract the function. so you can try it

**Comment by strongrex2001** [comment]
I have got the same problem too when I call a Java Method.

**Comment by irbull** [comment]
@strongrex2001 Can you create a short code example that demonstrates the problem?

**Comment by strongrex2001** [comment]
Javascript:
function callback(id)
{
for (var i=0; i<32; i++) NewProjAng(0, 270, GetProj(id, POS_Y), i * 360 / 32, 2);
}

where NewProjAng and GetProj are two java functions as js functions, the function NewProjAng is to create an object on the stage and GetProj is to get some infomation of an object on the stage.

I call the callback function using v8.executeVoidScript("callback(10);"). I see a new object on the stage (but only one) and it crashed.

And by the way, calling java functions from javascript seems much slower than calling javascript ones..

**Comment by strongrex2001** [comment]
It only occurs on PC-android simulators. It never occurs on my cell phone.
I think maybe it's because I don't have x86 version of another library I use, and I am using the armeabi version of all the libraries.

**Comment by irbull** [comment]
Yes, if you must have all the same arch for all the libs. We've had this problem before with armeabi and armeabi-v7.

Regarding the slowness, you're right. I've noticed it's about 4x slower to call from JavaScript to Java than from Java to JavaScript. This is the JNI overhead the Just In Time compiler optimizations. For very tight loops, try and batch you calls. I'm going to close this, because I don't think there is much J2V8 can do about the crash.
