### ISSUE TITLE
How to monitor JS variable change?

### ISSUE THREAD

**Issue by LiuHongtao** [eclipsesource/J2V8#199]
There is the example code:

Java:

```
v8.add("foo", 123);
```

JavaScript:

```
log(foo);// 123
foo = 456;
log(foo);// 456
```

I want to get `456` when it's assigned to `foo` in Java side and do some processing.

The actual use case is `ctx.lineWidth = 15;`. When this code were executed, I can do `paint.setStrokeWidth(15)` in Java.

**Comment by activetheory** [comment]
I'm not sure if this functionality exists within J2V8, but a way to make this work is to implement the `lineWidth` as a [getter](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/get) in JavaScript, then inside of that call a native J2V8 method binding.

**Comment by irbull** [comment]
Yes, there is no J2V8 support for this. You would have to implement this in JS yourself.

**Comment by LiuHongtao** [comment]
thx guys for reply
