### ISSUE TITLE
A java application crashes when an exception happened in a some deferred section (e.g. setTimeout or process.nextTick)

### ISSUE THREAD

**Issue by BanderasPRO** [eclipsesource/J2V8#205]
Hello! I think that my case is a possible bug. 
This code interrupts a Java application immediately after nodejs invokes a callback function of setTimeout which throw an exception.

`// It is an example, in real case it can be a some erorr in a code.`
`nodeJS = NodeJS.createNodeJS();`
`try {
    nodeJS.getRuntime().executeVoidScript("setTimeout(function(){throw 'Error'}, 1000);"); 
} catch (Exception e) {
    e.printStackTrace();
}`

The application is interrupted with message:
`undefined:1`
`setTimeout(function(){throw 'Error'}, 10000);`
`^`
`Error`
`Process finished with exit code 1`

Another example shows that exceptions are not a cause of interruption of an application always and it is a 'normal' case.

`nodeJS = NodeJS.createNodeJS();`
`try {
    nodeJS.getRuntime().executeVoidScript("throw 'Error'");
} catch (Exception e) {
    e.printStackTrace();
}`

In this case we see the only a error message in console but the application still works.

`Exception in thread "Thread-2" undefined:1: Error`
`throw 'Error'`
`^`
`com.eclipsesource.v8.V8ScriptExecutionException
    at com.eclipsesource.v8.V8._executeScript(Native Method)
    at com.eclipsesource.v8.V8.executeScript(V8.java:940)
    at com.eclipsesource.v8.V8.executeScript(V8.java:595)
    at com.eclipsesource.v8.V8.executeObjectScript(V8.java:625)
    at com.eclipsesource.v8.V8.executeObjectScript(V8.java:608)
    at org.efc.origamiapp.v8.V8Environment.run(V8Environment.java:383)`

Also, i've described my case in [StackOverflow](http://stackoverflow.com/questions/40057984/a-java-application-crashes-when-an-exception-happened-in-a-some-deferred-section). Thank you guys for your great job !

**Comment by rdemirkoparan** [comment]
Take a look at this link, maybe helps..
https://nodejs.org/docs/v0.4.7/api/process.html#event_uncaughtException_

**Comment by BanderasPRO** [comment]
@rdemirkoparan you absolutely right, this is the best and correct solution. 
```
process.on('unhandledRejection', (err) => {
    console.error('Unhandled promise rejection',err);
});
process.on('uncaughtException', (err) => {
    console.error('Uncaught exception',err);
});
```

**Comment by rdemirkoparan** [comment]
@BanderasPRO please note that this is crude mechanism and should not your permanent solution!
check latest documentation for warning section : https://nodejs.org/api/process.html#process_event_uncaughtexception
