### ISSUE TITLE
JVM warning on linux

### ISSUE THREAD

**Issue by jknack** [eclipsesource/J2V8#206]
Hi @irbull 

Just to let you know JVM print this warning while loading the lib on linux:

```
Java HotSpot(TM) 64-Bit Server VM warning: You have loaded library /home/edgar/libj2v8_linux_x86_64.so which might have disabled stack guard. The VM will try to fix the stack guard now.
It's highly recommended that you fix the library with 'execstack -c <libfile>', or link it with '-z noexecstack'.
```

Everything works as expected but will be nice if the warning goes away.

Thanks.

**Comment by ewized** [comment]
@irbull Just wondering on any updates of this?

**Comment by rdemirkoparan** [comment]
try this;
export LD_LIBRARY_PATH = $LD_LIBRARY_PATH:/myj2v8nativepath/libj2v8_linux_x86_64.so

**Comment by irbull** [comment]
This has been fixed in master with the latest build scripts. Thanks!
