### ISSUE TITLE
Incorrect typecasting of Long value

### ISSUE THREAD

**Issue by BanderasPRO** [eclipsesource/J2V8#208]
com.eclipsesource.v8.utils.V8ObjectUtils#setValue has double typecasting for Long type: 

```
if (value instanceof Long) {
    result.add(key, (int) (long) (Long) value);
}
```

I use this type for Date type exchange. After this way of typecasting the number 1477486236000 transforms to 17486176. Of course the date was incorrect.
I can't guess a reason of that double conversion but i commented the (int) part and i did not see any errors or warnings.

**Comment by irbull** [comment]
I'm not sure we can map the full range of Java long to JavaScript numbers, but we can certainly do better than this. Fix coming. Thanks for reporting this @BanderasPRO.
