### ISSUE TITLE
setTimeout from NodeJS does not work

### ISSUE THREAD

**Issue by Haringat** [eclipsesource/J2V8#209]
I tried the following snippet in a NodeJS environment and in J2V8 NodeJS:
```JavaScript
"use strict";
setTimeout(() => {
    console.log("callback called!");
},0);
console.log("synchronous");
```
In my local node installation the output was what I would expect:
```
synchronous
callback called!
```
In J2V8 though, the output was just this:
```
synchronous
```
OS: Linux x64
J2V8 version: 4.6.0

**Comment by TonyRice** [comment]
Without looking directly at the code I do believe that you may need to implement these functions yourself. If I figure something out I will post back here!

**Comment by Haringat** [comment]
Well, I thought so, but still it is irritating that the function is there, but doesn't work as expected. It would probably be better to remove it from the environment to hint people at the fact that they have to implement it themselves.
BTW: If you are still looking for something working, here is what I wrote (it has some dependency on Minecraft but those can be removed without touching the rest of the code):
https://github.com/Haringat/OpenJsComputers/blob/master/src/main/java/com/github/haringat/oc/v8/eventloop/EventLoop.java

**Comment by irbull** [comment]
It seems like many of the NodeJS things never worked properly. We are reducing the scope of this project to V8 on Android. If someone wants to build a downstream project that builds and maintains NodeJS support, I would be happy to help them set that up. Unfortunately, I don't have the cycles do that though and I think it's better to be honest about the work I can do. Please see #441 for more information.

**Comment by huhuang03** [comment]
as https://github.com/eclipsesource/J2V8/issues/406 say. I can't figure out how to not release the object...
