### ISSUE TITLE
Support for x86 is missing

### ISSUE THREAD

**Issue by jonek** [eclipsesource/J2V8#21]
We should also build for x86, not only for armeabi.

In the long run we should be able to support "Multiple APKs" for tabris.js. This is explained here: http://developer.android.com/google/play/publishing/multiple-apks.html

The NDK does support x86 as listed und "Android platform compatibility" here:
http://developer.android.com/tools/sdk/ndk/index.html#overview

**Comment by irbull** [comment]
Android x86 support is now available in 2.0-SNAPSHOT.
