### ISSUE TITLE
UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Nims72** [eclipsesource/J2V8#214]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.shutterfly.develop-1/base.apk"],nativeLibraryDirectories=[/data/app/com.shutterfly.develop-1/lib/arm64, /data/app/com.shutterfly.develop-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]] couldn't find "libj2v8.so"

I am getting this when trying to run J2V8 in an existing project, I do not have this problem when creating from an empty project. 
J2V8 was imported into both projects with:
compile 'com.eclipsesource.j2v8:j2v8:4.5.0@aar

Adding the workaround with abiFilters mentioned here:
https://github.com/eclipsesource/J2V8/issues/174
does work.

From the https://github.com/eclipsesource/J2V8/issues/174 - I am unsure if this has been fixed.

Would really like to understand how to solve these issues.

**Comment by irbull** [comment]
We have much newer versions of the `aar` now and we haven't seen this issue recently. Closing.
