### ISSUE TITLE
Roadmap - V8 Upgrade to version 5.x

### ISSUE THREAD

**Issue by diervo** [eclipsesource/J2V8#215]
Is there a roadmap or a timeline for upgrading to version 5.x of V8?

We are very interested to use this at Salesforce, and we would love to contribute, so if you guys are not planning to work on it, we might be able to help.

Would love to have a meeting with @irbull and team to discuss. Could you drop me an email (is on my public git profile), I couldn't find yours.

**Comment by geowarin** [comment]
See #230

**Comment by irbull** [comment]
PR 230 has been merged, and it now builds on node 6.1 and V8 5. I am now working on Node 7. I'm going to close this issue as the version 5 commit is merged. Thanks @diervo for opening and @geowarin for the PR.
