### ISSUE TITLE
Still seeing java.lang.UnsupportedOperationException: StartNodeJS Not Supported

### ISSUE THREAD

**Issue by xiaolin-cheng** [eclipsesource/J2V8#216]
Hello,

I am not sure if I am missing anything for Android. I added dependency for j2v8 in build.gradle:
    compile 'com.eclipsesource.j2v8:j2v8:4.6.0@aar' 
from jcenter. 

Simple Javascript ran fine with raw v8object and runtime, but when I tried to test with nodejs:
       NodeJS nodeJS = NodeJS.createNodeJS();
        nodeJS.release();
java.lang.UnsupportedOperationException: StartNodeJS Not Supported was thrown out.

I would assume the issue has been fixed from issue #157 and nodejs is built in aar by default:
https://github.com/eclipsesource/J2V8/issues/157

Am I missing anything or running Android Studio on Mac to build the app could be a problem?

Thanks.

**Comment by irbull** [comment]
The node wrappers are not available on Android, they are only available on the Desktop platforms (windows, mac, linux). This is the expected behaviour until we have node binaries for Android.

**Comment by twhit093** [comment]
@irbull will node wrapper support be added for Android?
