### ISSUE TITLE
Exception thrown from a JavaVoidCallback terminates the whole JVM process

### ISSUE THREAD

**Issue by peter-gergely-horvath** [eclipsesource/J2V8#217]
Any exception thrown from a JavaCallback/JavaVoidCallback causes the JVM to exit.

Consider the following sample:

```
public class J2V8Example {

    public static void main(String[] args) throws Exception {

        String script = " foobar(); ";

        Path tempFile = scriptToTempFile(script);

        JavaVoidCallback testCallback = (receiver, parameters) -> {
            throw new IllegalStateException("This simulates an error");
        };

        NodeJS theNodeJs = NodeJS.createNodeJS();
        theNodeJs.getRuntime().registerJavaMethod(testCallback, "foobar");

        try {
            theNodeJs.exec(tempFile.toFile());

            while (theNodeJs.isRunning()) {
                theNodeJs.handleMessage();
            }
        } catch (Exception ex) {
            System.err.println("Caught Exception: ");
            ex.printStackTrace();
        } catch (Throwable t) {
            System.err.println("Caught Throwable: ");
            t.printStackTrace();
        }
    }

    private static Path scriptToTempFile(String script) throws IOException {
        Path tempFile = Files.createTempFile("J2V8Example", ".tmp");
        Files.write(tempFile, script.getBytes("UTF-8"),
                StandardOpenOption.WRITE,
                StandardOpenOption.TRUNCATE_EXISTING);
        return tempFile;
    }
}
```
Instead of printing "Caught Exception: " or "Caught Throwable: " and the stack trace, this sample immediately terminates the *WHOLE JVM PROCESS* with an error message similar to the one below:

```
node.js:376
        callback();
        ^
/tmp/J2V8Example7781710029960180303.tmp:1: This simulates an error
```

**Comment by plg1971** [comment]
THANK YOU!!  : - )

**Comment by plg1971** [comment]
Thanks

**Comment by irbull** [comment]
Sorry, I missed this bug report. Crashing the VM is *never* the right behaviour. I will take a look. Thanks for reporting.

**Comment by midzelis** [comment]
@irbull not sure if you saw, but this is another JVM crash bug: https://github.com/eclipsesource/J2V8/issues/202

**Comment by rdemirkoparan** [comment]
Hello, @irbull any update on this issue?

**Comment by TonyRice** [comment]
I am attempting to debug this issue.

**Comment by irbull** [comment]
Unfortunately, I'm not able to support NodeJS with J2V8 and for the project to continue, I need to scope the work and be honest about what I can support. Please see #441. If someone else would like to extend J2V8 in a downstream project to support NodeJS, I would be happy to help them get started.

I'm tagging this as `NodeJS` in case someone wants to address these issues in a downstream project, but I'm going to close this as out of scope.
