### ISSUE TITLE
Can j2v8 call electron?

### ISSUE THREAD

**Issue by nedtwigg** [eclipsesource/J2V8#218]
Is it possible to use j2v8 to call into electron?

e.g. could it run [this script](https://github.com/electron/electron-quick-start/blob/master/main.js)?

**Comment by irbull** [comment]
I looked into this today. Unfortunately both electron and J2V8 bundle a version of V8 within each. Electron is really a browser window bundled with V8 whereas J2V8 is a JVM library bundled with V8. We would need a J2Electron for this to work.

I think the J2V8 library could serve a good starting point for such a library, but that is out of scope for J2V8 itself.

I do think J2Electron would be a really cool project though ;)
