### ISSUE TITLE
How to I run NPM cli and pass arguments to it?

### ISSUE THREAD

**Issue by manju-reddys** [eclipsesource/J2V8#219]
Hi,

I have tried to run NPM cli and pass arguments but I couldn't find a way to pass cli arguments. Below is the sample code:

```
private static void startNpm(File file) {
        String fileName = file.getPath() + File.separator + "package" + File.separator + "bin" + File.separator + "npm-cli.js";
        NodeJS node = NodeJS.createNodeJS(new File(fileName));
        V8Function fun = new V8Function(node.getRuntime(), (V8Object receiver, V8Array parameters) -> {
            V8Object obj = parameters.getObject("npm");
            System.out.println(node.getRuntime().executeJSFunction("npm", "start"));
            return null;
        });
        
        while(node.isRunning()) {
            node.handleMessage();
        }
        fun.release();
        node.release();
    }
```
The output is always below:

> where <command> is one of:
>     access, adduser, bin, bugs, c, cache, completion, config,
>     ddp, dedupe, deprecate, dist-tag, docs, edit, explore, get,
>     help, help-search, i, init, install, install-test, it, link,
>     list, ln, login, logout, ls, outdated, owner, pack, ping,
>     prefix, prune, publish, rb, rebuild, repo, restart, root,
>     run, run-script, s, se, search, set, shrinkwrap, star,
>     stars, start, stop, t, team, test, tst, un, uninstall,
>     unpublish, unstar, up, update, v, version, view, whoami
> 
> npm <cmd> -h     quick help on <cmd>
> npm -l           display full usage info
> npm help <term>  search for help on <term>
> npm help npm     involved overview
> 
> Specify configs in the ini-formatted file:
>     C:\Users\Kushan\.npmrc
> or on the command line via: npm <command> --key value
> Config info can be viewed via: npm help config
> 
> npm@4.0.3 C:\Manju\games\filess\package

Thats because we are passing the function arguments but not the cli arguments, please help me here.

**Comment by manju-reddys** [comment]
I managed to get it worked finally :)... I will write blog on this end of 2016!

**Comment by jsimomaa** [comment]
@manju-reddys 

How did you get the above to work? Is the blog readable somewhere? Thanks
