### ISSUE TITLE
请增加arm64-v8a 的 libj2v8.so

### ISSUE THREAD

**Issue by noear** [eclipsesource/J2V8#222]
不然，与其它有 arm64-v8a 支持的库一起，就出问题了。

**Comment by matiwinnetou** [comment]
Ale przecież to nie jest żadna filozofia pisać w takim języku, który tylko garstka ludzi zrozumie.

**Comment by BlueSky-YJS** [comment]
目前为啥没有全平台的支持库呢,找不到arm64-v8a的so呀?各位.在哪儿能找到吗?

**Comment by irbull** [comment]
I think this is asking for 64-bit support. Closing as a duplicate of #384.

**Comment by flydarker** [comment]
> 

你找到arm64的了吗？没有的话估计只有自己拉源码编译了
