### ISSUE TITLE
I create the v8 library from Google v8 code, how do I integrate this into J2V8?

### ISSUE THREAD

**Issue by dzungductran** [eclipsesource/J2V8#225]
The v8 libraries are:

dtran:~/v8$ find out.gn -name "*.a"
out.gn/arm.release/clang_x86_v8_arm/obj/third_party/icu/libicui18n.a
out.gn/arm.release/clang_x86_v8_arm/obj/third_party/icu/libicuuc.a
out.gn/arm.release/clang_x86_v8_arm/obj/libv8_libplatform.a
out.gn/arm.release/clang_x86_v8_arm/obj/libv8_libbase.a
out.gn/arm.release/obj/build/config/sanitizers/liboptions_sources.a
out.gn/arm.release/obj/testing/gtest/libgtest.a
out.gn/arm.release/obj/testing/gmock/libgmock_main.a
out.gn/arm.release/obj/testing/gmock/libgmock.a

How do I include this into Android studio gradle build?

**Comment by irbull** [comment]
Take a look at the docker file we used to build on Linux and Android (https://github.com/eclipsesource/J2V8/blob/master/docker/Dockerfile.linux). You need to compile `com_eclipsesource_v8_V8Impl.cpp` and link against those libraries.
