### ISSUE TITLE
How to call a java function from a javascipt using J2v8  in android

### ISSUE THREAD

**Issue by vimalMoorthy** [eclipsesource/J2V8#226]
Am new to J2v8 . I want to call a java function which is in MainActivity.java  from a javascript file. The javascript file is in assets folder of the project.

Example:
MainActivity.java

//My function

`public void display()
{
String a="hello";
System.out.println(a); //display in android Log
}
`

If am having  javascript file named test.js under assets folder of an Android project. Is it possible to call the display() function from MainActivity.java to the javascript file test.js using J2v8. 

If not , is there any other way to do that? I really need help!!!!

thank you in advance!!!

**Comment by irbull** [comment]
You need to register the Java method with J2V8. See http://eclipsesource.com/blogs/2015/06/06/registering-java-callbacks-with-j2v8/ for information.
