### ISSUE TITLE
Where can i find instructions to build on windows?

### ISSUE THREAD

**Issue by muthu90ec** [eclipsesource/J2V8#227]

**Comment by irbull** [comment]
Sorry, I'm off-line without much computer access this week. But basically you need to load the solution file (.sln) in visual studio and build the J2V8 native libs. Then you can place these in the `src/main/resources/` directory and run the maven build.

**Comment by muthu90ec** [comment]
Thank you

**Comment by winston01** [comment]
For those newbies arriving here later: you have to update the <LibraryPath> in jni/j2v8.vcxproj to your local values, either in Visual Studio in project properties -> VC++ Directories -> Library Directories or manually in the file.

**Comment by TonyRice** [comment]
Someone probably should update that within the README. Who would be the maintainer for this project?

**Comment by irbull** [comment]
Feel free to submit a PR with the updates to the README. I don't actually
use the windows builds, and I can't remember the details.

**Comment by irbull** [comment]
We will be updating the build instructions. See #40. However, we are also limiting the scope of this project o Android. The windows build files will stay, but they will not be supported (unless someone else can do it, as I don't even have a Windows computer to test on).
