### ISSUE TITLE
Unresolved externals when building with NODE_COMPATIBLE=1

### ISSUE THREAD

**Issue by drywolf** [eclipsesource/J2V8#229]
Hi,

I'm trying to build on Windows with `NODE_COMPATIBLE=1` set in the compiler options, but then I get the following unresolved functions showing up in the linker. Is there anything special that I need to do when building Node.js to be able to import those functions from it ?

I'm building on Windows 10 with VS 2015.

	unresolved external symbol _register_async_wrap referenced in function Java_com_eclipsesource_v8_V8__1startNodeJS
	unresolved external symbol _register_cares_wrap referenced in function Java_com_eclipsesource_v8_V8__1startNodeJS
	unresolved external symbol _register_fs_event_wrap referenced in function Java_com_eclipsesource_v8_V8__1startNodeJS
	unresolved external symbol _register_js_stream referenced in function Java_com_eclipsesource_v8_V8__1startNodeJS
	unresolved external symbol _register_buffer referenced in function Java_com_eclipsesource_v8_V8__1startNodeJS
	unresolved external symbol _register_contextify referenced in function Java_com_eclipsesource_v8_V8__1startNodeJS
	unresolved external symbol _register_crypto referenced in function Java_com_eclipsesource_v8_V8__1startNodeJS
	unresolved external symbol _register_fs referenced in function Java_com_eclipsesource_v8_V8__1startNodeJS
	unresolved external symbol _register_http_parser referenced in function Java_com_eclipsesource_v8_V8__1startNodeJS
	unresolved external symbol _register_os referenced in function Java_com_eclipsesource_v8_V8__1startNodeJS
	unresolved external symbol _register_util referenced in function Java_com_eclipsesource_v8_V8__1startNodeJS
	unresolved external symbol _register_v8 referenced in function Java_com_eclipsesource_v8_V8__1startNodeJS
	unresolved external symbol _register_zlib referenced in function Java_com_eclipsesource_v8_V8__1startNodeJS
	unresolved external symbol _register_pipe_wrap referenced in function Java_com_eclipsesource_v8_V8__1startNodeJS
	unresolved external symbol _register_process_wrap referenced in function Java_com_eclipsesource_v8_V8__1startNodeJS
	unresolved external symbol _register_signal_wrap referenced in function Java_com_eclipsesource_v8_V8__1startNodeJS
	unresolved external symbol _register_spawn_sync referenced in function Java_com_eclipsesource_v8_V8__1startNodeJS
	unresolved external symbol _register_stream_wrap referenced in function Java_com_eclipsesource_v8_V8__1startNodeJS
	unresolved external symbol _register_tcp_wrap referenced in function Java_com_eclipsesource_v8_V8__1startNodeJS
	unresolved external symbol _register_timer_wrap referenced in function Java_com_eclipsesource_v8_V8__1startNodeJS
	unresolved external symbol _register_tls_wrap referenced in function Java_com_eclipsesource_v8_V8__1startNodeJS
	unresolved external symbol _register_tty_wrap referenced in function Java_com_eclipsesource_v8_V8__1startNodeJS
	unresolved external symbol _register_udp_wrap referenced in function Java_com_eclipsesource_v8_V8__1startNodeJS
	unresolved external symbol _register_uv referenced in function Java_com_eclipsesource_v8_V8__1startNodeJS

**Comment by drywolf** [comment]
I figured it out.
For anyone else trying to build on Windows:

- clone the node.js repo from github
- checkout the tag 4.6.0 (or the version that matches the J2V8 release you want to build)
- change configuration line 187 in vcbuild.bat by adding **--enable-static** at the end of the arguments
`python configure %configure_flags% %enable_vtune_profiling% --dest-cpu=%target_arch% --tag=%TAG% --enable-static`
- build the node.js static libs by running e.g. `vcbuild x64 release`

**Comment by irbull** [comment]
Thank-you for documenting that here. I completely forgot that I had to do that. I found the hint on https://github.com/electron/node/issues/4

**Comment by TonyRice** [comment]
I followed this and I'm still having some trouble. Is this dependent on a specific version of node?

**Comment by TonyRice** [comment]
I actually ended up figuring it out. You can easily accomplish this without any change to node.h by some parameters when using vcbuild.bat. I did end up changing my local vcbuild.bat to include a parameter for enable-static

**Comment by TonyRice** [comment]
My changes will hopefully be in the master node vcbuild.bat soon (https://github.com/nodejs/node/pull/12764)
