### ISSUE TITLE
Unable to kill node js engine

### ISSUE THREAD

**Issue by MichaelQinLin** [eclipsesource/J2V8#231]
I set a timeout in java to kill node js, i have tried methods .release() .getRuntime().release(), the node js simply cannot get killed. I still get response after some period of time.

**Comment by irbull** [comment]
Can you post a short snippet of how you have setup and run your node code? I assumed that by no longer processing the message loop, you wouldn't get anything back from node.

**Comment by MichaelQinLin** [comment]
```java
scope = new MemoryManager(nodeJS.getRuntime());
String scriptToExecute = pathToScripts + File.separator + scriptName + ".js";
V8Object plugin = nodeJS.require(new File(scriptToExecute));
V8Function metadataCallback = new V8Function(nodeJS.getRuntime(), new JavaCallback() {
                       public Object invoke(V8Object receiver, V8Array parameters) {
				//get response here via parameters
				return parameters;
			}
		});
// input to getMetadata function
V8Array metadataPara = new V8Array(nodeJS.getRuntime());
metadataPara.push(resourceType);
metadataPara.push(metadataCallback); // callback function
plugin.executeFunction("getMetadata", metadataPara);
scope.release();
```

Hi @irbull my code is like this. The problem I can only execute one script with the engine created, which means i have to create multiple engines for multiple scripts. The engine cannot get released.

**Comment by irbull** [comment]
You can use `nodeJS.getRuntime().release()`. This can even be called from another thread. For example, here is a small node.js app that runs an infinite loop. Another thread calls `terminate` after 10 seconds.
```
final NodeJS nodeJS = NodeJS.createNodeJS();
		new Thread(new Runnable() {

			@Override
			public void run() {
				try {
					Thread.sleep(10000);
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
				System.out.println("Shutting down");
				nodeJS.getRuntime().terminateExecution();
			}
		}).start();
		try {
			nodeJS.require(new File("nodejs/infinite.js"));
		} catch (RuntimeException e) {
		} finally {
			nodeJS.release();
		}
```

**Comment by Flamenco** [comment]
@irbull In your example, you reference ```nodeJS.getRuntime().release()```, but your example uses ```nodeJS.release()``` and ```nodeJS.getRuntime().terminateExecution();```

I am trying to shutdown a node based web server.  Could you please clarify the best way to do so?
