### ISSUE TITLE
Is there a way to get node version via a static method call?

### ISSUE THREAD

**Issue by muthu90ec** [eclipsesource/J2V8#233]
I see there is a way to get the v8 version like,
V8.getV8Version()

Is there a way to get node version in a similar way?

**Comment by midzelis** [comment]
Just use the built in object process. See https://nodejs.org/api/process.html#process_process_versions

**Comment by irbull** [comment]
I added getVersion to `NodeJS.java` aafa6541b62be390d32d8b182d5d862fce9521a6
