### ISSUE TITLE
How are kill -9 or ctrl -c handled?

### ISSUE THREAD

**Issue by muthu90ec** [eclipsesource/J2V8#234]
The documentation says "JNI / C++ which sits in the middle is completely unmanaged', 

which will require to run V8Object.release() , how can i ensure V8Object is released on ctrl c command/ JVM shutdown?

**Comment by irbull** [comment]
On shutdown it's not a problem because the VM and V8 will both terminate. The unmanaged memory we mention in the docs is the handles from Java to V8, but on shutdown these are all gone and the OS will recover the entire memory from the program.
