### ISSUE TITLE
compiling J2V8 on mac

### ISSUE THREAD

**Issue by GusCaplan** [eclipsesource/J2V8#235]
when i run the build i am getting this:
![](https://i.gus.host/QlIbP6)

Does anyone know how i might fix this?

EDIT
i am running macOS Sierra 10.12.1 Beta (16B2338c)

EDIT 2
i did some digging and found this
```
Undefined symbols for architecture x86_64:
  "v8_inspector::V8Inspector::create(v8::Isolate*, v8_inspector::V8InspectorClient*)"
```

**Comment by theido** [comment]
did you solved this one ?

**Comment by GusCaplan** [comment]
@theido yes but i don't remember how at this point 😆
