### ISSUE TITLE
Updating major versions of node

### ISSUE THREAD

**Issue by devsnek** [eclipsesource/J2V8#237]
continuation from #230

**Comment by KnownUnown** [comment]
So, my fork isn't completely ready - it builds but as mentioned by @winston01 @ #230, tests fail. Additionally, there really are no clear instructions for building. todo:

- [ ] Add build instructions
- [ ] Add build Dockerfile(s)
- [ ] Fix unit tests - I'd guess it has something to do with [this](https://github.com/eclipsesource/J2V8/blob/master/src/test/java/com/eclipsesource/v8/V8Test.java#L64)

Haven't even built a binary for x86_64 yet, but it should be relatively painless.
For reference, my repo is [here](https://github.com/KnownUnown/J2V8).

**Comment by GusCaplan** [comment]
those functions are registered with the decorator, so you can just change the name and content (e.g. starts with 5) or even remove it entirely, and it won't be a problem

**Comment by GusCaplan** [comment]
cc @irbull please notice this

**Comment by GusCaplan** [comment]
@KnownUnown I am admittedly not too good with c++, but if you could look into upgrading to node v8 that would be cool.

**Comment by KnownUnown** [comment]
After some head banging...
![image](https://cloud.githubusercontent.com/assets/3821575/24443286/a9b2d22a-1427-11e7-8259-1b42a9b78f5c.png)
Didn't initially upgrade it with desktop platforms in mind (using J2V8 with Node on Android personally). Changes are pushed to my fork, @GusCaplan @irbull :)

**Comment by KnownUnown** [comment]
Before anyone asks -- I found it necessary to patch Node itself (or at least it's GYPfiles) to get it to build for Android. The patch in question is [here](https://gist.github.com/KnownUnown/05a3f9c0ae89aeb3b1113bc7b1a00b97).

**Comment by KnownUnown** [comment]
Sure @irbull! I managed to get most of the test suite passing by modifying expected values, but I don't have much knowledge of the V8 debugger and wasn't able to figure out what was wrong with FrameTest (NullPointer on line 104). I'll submit the pull regardless.

**Comment by GusCaplan** [comment]
I was thinking we could also put together a Makefile instead of having 30 scripts in the root of the project, what with `node-build.sh` and `node_build.sh`. It gets rather confusing.

**Comment by irbull** [comment]
+1 to that. Funny how this project is starting to grow up :)
