### ISSUE TITLE
Parse Object as parameter

### ISSUE THREAD

**Issue by liz3** [eclipsesource/J2V8#243]
First i have to say that this is an awesome project and so simple to use!
But i have a problem.

I am calling:
`v8.executeVoidFunction("name", params);`
But in the V8Array for the arguments, how can i parse a java object to it?
I made some google searches without success.
Or is it just not possible?

Kind Regards,

Liz3

**Comment by irbull** [comment]
Thanks for the kind words. You can push V8Objects to the params array:
```
V8Array params = new V8Array(v8);
params.push(someV8Object);
v8.executeVoidFunction("name", params);
```

Your best bet for most of these things is the test cases:
https://github.com/eclipsesource/J2V8/blob/master/src/test/java/com/eclipsesource/v8/V8JSFunctionCallTest.java
