### ISSUE TITLE
Unable to capture the output from a NodeJS.exec() run

### ISSUE THREAD

**Issue by swaechter** [eclipsesource/J2V8#246]
I would like to run a JavaScript script with NodeJS (J2V8 versiom 4.6.0 Linux x64) and capture the output, so I can reuse it for logging/later (In my case I would like to perform a server side rendering of Angular via Java/J2V8).

From what I was able to see the class NodeJs doesn't support logging at all and redirecting the Java System.out and System.err to an own buffer doesn't work: My application output is visible, but all JavaScript output (For example made with console.log) isn't visible.

I really need to get the output. What can I do?

Code to replicate the problem:

```
NodeJS nodejs = NodeJS.createNodeJS();
nodejs.exec(new File("<path-to-file.js>"));
while (nodejs.isRunning()) {
	nodejs.handleMessage();
}
// Somehow the output that is produced by handling the messages/events
nodejs.release();
```

PS: It's really great to see what J2V8 can do!

**Comment by irbull** [comment]
This is a fascinating request. I don't know if it's possible to capture
this output, or if node just uses cout / printf? Do you, with node, can you
direct the output somewhere else (other than using pipes and redirects)?

**Comment by midzelis** [comment]
I've done this. I'm on my phone right now, but tonight or tommorow morning I can post a snippet. My technique uses JavaScript only, no messing around in c code.

**Comment by swaechter** [comment]
At the moment I see now way how to pipe/redirect the output externally. But I came up with the solution  to register a normal Java method through V8 and use this function in JavaScript for logging (The Java counterpart logs to System.*).

For me that's possible because I can change all JavaScript code, but for other people that can't change their code @midzelis solution might be a better one.

**Comment by midzelis** [comment]
Oops, forgot to update this... 

I override certain base node.js runtime, specifically, the io stream itself. 

sample code

`var Writable = require('stream').Writable;
var wsout = Writable();
wsout._write = function (chunk, enc, next) {
    J2V8.print(chunk, enc);
    next();
};
var wserr = Writable();
wserr._write = function (chunk, enc, next) {
    J2V8.printErr(new Error().stack, chunk, enc);
    next();
};
Object.defineProperty(process, 'stdout', {
    configurable: true,
    enumerable: true,
    get: function() { return wsout }
});
Object.defineProperty(process, 'stderr', {
    configurable: true,
    enumerable: true,
    get: function() { return wserr }
});

var Readable = require('stream').Readable;
var rs = Readable();
Object.defineProperty(process, 'stdin', {
    configurable: true,
    enumerable: true,
    get: function() { return rs }
});
`
where J2V8 is the JS-side of a Java Object.... the java object has these functions...

`	public void print(Object chunk, String encoding) {
		System.out(chunk.toString());
	}

        public void printErr(String stack, Object chunk, String encoding) {
			System.out.println(chunk.toString());
			System.out.println(new Exception("Error from NodeJS"));
	}
`
