### ISSUE TITLE
Android API 19 min

### ISSUE THREAD

**Issue by rsommerard** [eclipsesource/J2V8#247]
Hi,

What is the reason of the minimum version required (API19) for Android?

--Romain

**Comment by irbull** [comment]
The PR that I received set this. I've actually reverted it to 17, but noticed I haven't pushed that yet (although I think the -SNAPSHOT was built to target API17). We actually Targeted API15 and I'd be happy to set it back. Do you know any reason why it should be higher? I would rather keep it as low as possible.

**Comment by rsommerard** [comment]
No, I don't know any reason why it should be higher.

I target the API15, so I compiled it without apparent error that is why I ask 😃.

Notice that I have not run it yet, I just compiled it.

**Comment by irbull** [comment]
I have pulled this back to API 15. I will be rolling out a new snapshot with this in the next few days.
