### ISSUE TITLE
Adding a null V8Object value on V8Object causes crash

### ISSUE THREAD

**Issue by mpost** [eclipsesource/J2V8#25]
Something like

<pre lang="java">
v8Object.add("key", null);
</pre>

causes an NPE internally. This case should be handled more graceful.

**Comment by irbull** [comment]
There is a method v8Object.addUndefined(key). We currently treat undefined and null as the same, which is wrong. I will be fixing this as part of issue #22

**Comment by irbull** [comment]
Actually, there are a few issues here:
 - new V8Object(v8).add("foo", (String) null);
 - new V8Object(v8).add("foo", (V8Object) null);
 - new V8Object(v8).add("foo", (V8Array) null);

These all fail in different ways.

**Comment by irbull** [comment]
You can now set null (or undefined) on V8Objects and V8Arrays. See commit b06d84df33207cf8b23c369c20003fff889df495
