### ISSUE TITLE
JavaCallback that return Java Object

### ISSUE THREAD

**Issue by rsommerard** [eclipsesource/J2V8#251]
I search to get a Java Instance created through a javascript script.

In the script below, I just setup a Java callback for each method to the javascript "foo" object.
```java
class Bar {}

public class Foo {
    public Object bar() {
        return new Bar();
    }
}

String setup = "function pony() { return foo.bar(); }";
String script = "pony();";

V8 runtime = V8.createV8Runtime();

Foo foo = new Foo();

V8Object obj = new V8Object(runtime);
Method[] methods = foo.getClass().getDeclaredMethods();
for (Method m : methods) {
    obj.registerJavaMethod(foo, m.getName(), m.getName(), m.getParameterTypes());
}
runtime.add("foo", obj);
obj.release();

runtime.executeScript(setup);
runtime.executeScript(script);
```

When I run this, the second executeScript throw an exception because returning Java Object is not authorized according to this from `V8.java::checkResult(Object)`

Is it possible to get a Java Object from a Callback like exposed in my example?

**Comment by irbull** [comment]
No, because V8 has no idea what a Java Object is. This is failing when you try to pass `bar` back to V8. The only thing V8 can load is V8 Types (subclasses of `Value` (https://github.com/v8/v8/blob/master/include/v8.h#L2741)). The Java class `V8Object` maps to this. You'd have to do the same thing and instead of returning `Bar` return a `V8Object`.

**Comment by irbull** [comment]
For example, if changed `Foo` as follows:
```
class Foo {
	public Object bar() {
        return new V8Object(runtime);
	}
}
```
This should work.

**Comment by monalisasaha79** [comment]
Hi,

Thanks for the example. I have 2 problems here.
1. How I can pass the runtime instance to the V8Object in return from the bar method. I am getting following error.

Invalid V8 thread access
com.eclipsesource.v8.V8ScriptExecutionException
        at com.eclipsesource.v8.V8._executeFunction(Native Method)
        at com.eclipsesource.v8.V8.executeFunction(V8.java:996)
        at com.eclipsesource.v8.V8Object.executeObjectFunction(V8Object.java:334)
        at com.skaale.moduleo.repository.DocumentRepository.execute(DocumentRepository.java:360)
        at com.skaale.moduleo.actor.Worker.onReceive(Worker.java:31)
        at akka.actor.UntypedActor$$anonfun$receive$1.applyOrElse(UntypedActor.scala:165)
        at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
        at akka.actor.UntypedActor.aroundReceive(UntypedActor.scala:95)
        at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
        at akka.actor.ActorCell.invoke(ActorCell.scala:495)
        at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
        at akka.dispatch.Mailbox.run(Mailbox.scala:224)
        at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.lang.Error: Invalid V8 thread access
        at com.eclipsesource.v8.V8Locker.checkThread(V8Locker.java:56)
        at com.eclipsesource.v8.V8.checkThread(V8.java:676)
        at com.eclipsesource.v8.V8Object.<init>(V8Object.java:43)
        at com.eclipsesource.v8.V8Object.<init>(V8Object.java:37)
        at com.eclipsesource.v8.utils.V8ObjectUtils.toV8Object(V8ObjectUtils.java:345)
        at com.eclipsesource.v8.utils.V8ObjectUtils.toV8Object(V8ObjectUtils.java:179)
        at com.skaale.moduleo.repository.DocumentRepository.getBehaviour(DocumentRepository.java:473)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.eclipsesource.v8.V8.callObjectJavaMethod(V8.java:745)

If I pass a new runtime, my java enviornment is crashing.
public V8Object getBehaviour (String key){
		Map<String, Object> behaviour = new HashMap<String, Object>();
		behaviour.put("show", true);
		behaviour.put("readonly", true);
		System.out.println ("**************************************************************************** ");
		return V8ObjectUtils.toV8Object(V8.createV8Runtime(), behaviour);
	}
****************************************************************************
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x1cb7ae08, pid=7964, tid=0x00000e10
#
# JRE version: Java(TM) SE Runtime Environment (8.0_121-b13) (build 1.8.0_121-b13)
# Java VM: Java HotSpot(TM) Client VM (25.121-b13 mixed mode, sharing windows-x86 )
# Problematic frame:
# C  [libj2v8_win32_x86.dll+0x16ae08]
#
# Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
#
# An error report file with more information is saved as:
# C:\Arindam\personal\skaale-server\hs_err_pid7964.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#

2. How do I release the V8Object once it has been returned to my script.

Could you please a complete sample on this.

Thanks,
Monalisa

**Comment by monalisasaha79** [comment]
Sorry about the font, it has happened due to the # keyword

**Comment by monalisasaha79** [comment]
I managed to resolved it.
1. I created a class

import java.util.HashMap;
import java.util.Map;
import com.eclipsesource.v8.V8;
import com.eclipsesource.v8.V8Object;
import com.eclipsesource.v8.utils.V8ObjectUtils;

public class ModelOperation {
	private V8 engine;
	private Map<String, Object> model;
	public ModelOperation(V8 engine) {
		this.engine = engine;
	}
	
	public void register (V8Object model){
		this.model = V8ObjectUtils.toMap(model);
	}
	
	public V8Object getBehaviour(String key) {
		
		Map<String, Object> behaviour = new HashMap<String, Object>();
		behaviour.put("show", true);
		behaviour.put("readonly", true);
        return V8ObjectUtils.toV8Object(engine, behaviour);
    }
}

2. Register the class function for callback
// Registering Model Operation functions
			ModelOperation schema = new ModelOperation (engine);
			Method[] methods = schema.getClass().getDeclaredMethods();
			for (Method m : methods) {
			    engine.registerJavaMethod(schema, m.getName(), m.getName(), m.getParameterTypes());
			}
			// End

3. Finally call the java function from javascript
var behaviour = getBehaviour ("Hello Monalisa");

4. In case to exception handling, I have throwing Nullpoiner exception from the class method, to catch in javascript
if (model==null) throw new NullPointerException("Please register the model");

try{
        var behaviour = getBehaviour ("Hello Monalisa");
    } catch (e){
        callPlugin ("print", e);
    }

This works fine.

**Comment by sahnvn** [comment]
//I want to use the returned java object (ActiveSheet) here. What should I do?? Please Help.
        class ActiveSheet {			
			private V8 engine;
			ActiveSheet(V8 engine) {
				this.engine = engine;
			}
			
			public V8Object getRange() {
				Map<String, Object> rangeObject = new HashMap<String, Object>();
				rangeObject.put("range", new Range());
				return V8ObjectUtils.toV8Object(engine, rangeObject);
			}
		}
		
		class ActiveWorkbook {
			private V8 engine;
			private Map<String, Object> model;
			public ActiveWorkbook(V8 engine) {
				this.engine = engine;
			}
						
			public V8Object getSheet() {
				Map<String, Object> sheet = new HashMap<String, Object>();
				sheet.put("sheet", new ActiveSheet(this.engine));
				return V8ObjectUtils.toV8Object(engine, sheet);
			}
		}
			
		
		V8 engine = V8.createV8Runtime();
		ActiveWorkbook schema = new ActiveWorkbook (engine);
		Method[] methods = schema.getClass().getDeclaredMethods();
		for (Method m : methods) {
			engine.registerJavaMethod(schema, m.getName(), m.getName(), m.getParameterTypes());
		}	
		
		ActiveSheet schema1 = new ActiveSheet (engine);
		Method[] methods1 = schema1.getClass().getDeclaredMethods();
		for (Method m : methods1) {
			engine.registerJavaMethod(schema1, m.getName(), m.getName(), m.getParameterTypes());
		}	
		
		String script = "var sheet = ActiveWorkbook.getSheet(\"Sheet1\");"
				+ "var range = sheet.getRange()";
		engine.executeScript(script);

**Comment by sahnvn** [comment]
> I managed to resolved it.
> 
> 1. I created a class
> 
> import java.util.HashMap;
> import java.util.Map;
> import com.eclipsesource.v8.V8;
> import com.eclipsesource.v8.V8Object;
> import com.eclipsesource.v8.utils.V8ObjectUtils;
> 
> public class ModelOperation {
> private V8 engine;
> private Map<String, Object> model;
> public ModelOperation(V8 engine) {
> this.engine = engine;
> }
> 
> ```
> public void register (V8Object model){
> 	this.model = V8ObjectUtils.toMap(model);
> }
> 
> public V8Object getBehaviour(String key) {
> 	
> 	Map<String, Object> behaviour = new HashMap<String, Object>();
> 	behaviour.put("show", true);
> 	behaviour.put("readonly", true);
>     return V8ObjectUtils.toV8Object(engine, behaviour);
> }
> ```
> 
> }
> 
> 1. Register the class function for callback
>    // Registering Model Operation functions
>    ModelOperation schema = new ModelOperation (engine);
>    Method[] methods = schema.getClass().getDeclaredMethods();
>    for (Method m : methods) {
>    engine.registerJavaMethod(schema, m.getName(), m.getName(), m.getParameterTypes());
>    }
>    // End
> 2. Finally call the java function from javascript
>    var behaviour = getBehaviour ("Hello Monalisa");
> 3. In case to exception handling, I have throwing Nullpoiner exception from the class method, to catch in javascript
>    if (model==null) throw new NullPointerException("Please register the model");
> 
> try{
> var behaviour = getBehaviour ("Hello Monalisa");
> } catch (e){
> callPlugin ("print", e);
> }
> 
> This works fine.

Hi,,

public V8Object getBehaviour(String key) {
	
	Map<String, Object> behaviour = new HashMap<String, Object>();
	behaviour.put("Obj", new MyClass());
    return V8ObjectUtils.toV8Object(engine, behaviour);
}
Here, How can I use MyClass Object and perform operations on that? Please assist.

**Comment by carl1990** [comment]
mark
