### ISSUE TITLE
How can I manage object lifetime with j2V8

### ISSUE THREAD

**Issue by jellychen** [eclipsesource/J2V8#254]
I receive a V8Object,  then I save it as java class member. then JavaScript call this object function,
And set some V8Function callback.

If I release this object,  I can not release the it's own callback object.  Because maybe javascript hold  this object, If I release it's own data

**Comment by irbull** [comment]
You can release a V8Object from Java even JavaScript still holds a reference to it. Release just releases the Java handle to that object. You should release a V8Object when Java no longer needs access to it. 

Also, if a V8Object is actually contained (held) by another JavaScript object, you can alway get it back.
```
V8Object foo = new V8Object(v8);
V8Object bar = new V8Object(v8);
foo.add("bar", bar);
bar.release(); // <--- note: I have release bar.
bar = foo.get("bar"); // <---note: I got bar back.
```
