### ISSUE TITLE
Object is Wrong ?

### ISSUE THREAD

**Issue by jellychen** [eclipsesource/J2V8#255]
`
class A extends V8Object {
};

V8Object create() {
    return new A(******)
}

void a_java_function_called_from_js(V8Object obt) {
    if (obt instanceof A) {
        return; 
    }
}

// javascript
var d = create();
a_java_function_called_from_js(d);

? why this

`

**Comment by irbull** [comment]
JavaScript and V8 no nothing about Java objects. You must only pass V8Objects (or primitives) to V8.

**Comment by jellychen** [comment]
How Can I export a Java class to javascript ?

**Comment by irbull** [comment]
You cannot "export" a Java class, but you can register Java methods to be called, or bind Java methods to JavaScript functions. If it's a data class that you're interested in, look at V8ObjectUtils, there are methods there for converting JavaObjects to V8Objects.

**Comment by jellychen** [comment]
But I want use javascript to build my dom tree.  different elements maybe different java class.

If I can not convert V8Object to my java class, so how can I ?
