### ISSUE TITLE
Build process on mac (and in general)

### ISSUE THREAD

**Issue by cabbage** [eclipsesource/J2V8#256]
Hi,
the node modules I use depend on newer node versions (they use a lot of destructuring) therefore I wanted to build J2V8 from source with a newer node.

I am really confused on the process. I tried maven where all the tests failed with the same `IllegalState J2V8 native library not loaded` error. 

The gradle file is apparently only for Android (?). 

`buildJ2V8_mac.sh` failed with files missing from the compiled node:
```
clang: error: no such file or directory: '../node/out/Release/libstandalone_inspector.a'
clang: error: no such file or directory: '../node/out/Release/libicui18n.a'
clang: error: no such file or directory: '../node/out/Release/libicuucx.a'
clang: error: no such file or directory: '../node/out/Release/libicudata.a'
clang: error: no such file or directory: '../node/out/Release/libicustubdata.a'
```

Can anyone point me in the right direction? I haven't built anything with JNI so this is kinda new for me.

Cheers!

**Comment by irbull** [comment]
Sorry, I had some local build scripts I use that I had not pushed to GitHub.

For mac, you should be able to now run `sh ./build-node` and `sh ./buildJ2V8_macos.sh`.

**Comment by cabbage** [comment]
Thank you very much! It really helped a lot!

I'm able to build it, but when I want to use it in my project I get the `IllegalState J2V8 native library not loaded` error there now. I feel really dumb.
