### ISSUE TITLE
Getting Started or Hello-world Example required

### ISSUE THREAD

**Issue by AlexTrotsenko** [eclipsesource/J2V8#26]
J2V8 project looks very interesting. We have faced with problem, that Rhino on Android works very slow. 

But in order to start it would be nice to have any kind of example or how-to documentation.

For example:
1) Simple example referring standard API :
https://code.google.com/p/jav8/
2) Simple example of using not standard API:
https://github.com/nostra13/Android-Universal-Image-Loader
3) More sophisticated documentation
https://developers.google.com/v8/embed?csw=1
https://developers.google.com/v8/get_started

**Comment by irbull** [comment]
I've created a getting started guide http://eclipsesource.com/blogs/getting-started-with-j2v8/ and put links to several other tutorials / links in the README file.

**Comment by jeacott1** [comment]
helloworld really should be fixed so that it works out of the box.

 hello.concat(world).length(); //this throws an exception.
 hello.concat(world).length;//this is what it should look like.

its a small point, but somewhat off putting when trying this project for the first time.
