### ISSUE TITLE
Cannot find j2v8 4.7.0 with windows build jar in search.maven.org

### ISSUE THREAD

**Issue by djx314** [eclipsesource/J2V8#263]
I am glad to see j2v8 4.7.0 is out, but in <search.maven.org> I can't find winodws version for j2v8 for days. Anything wrong?

**Comment by matiwinnetou** [comment]
👍 I also cannot find the one for osx

**Comment by irbull** [comment]
See #261 for details. I don't have the capacity to support all platforms myself. We are working on improving the build to make this easier, but it's taking a lot of time. I'm going to close this issue, and we can track tis in #261.
