### ISSUE TITLE
static lock in the j2v8?

### ISSUE THREAD

**Issue by matiwinnetou** [eclipsesource/J2V8#274]
We are trying to write a new page with server side rendering using j2v8 and ReactJS.

It works kinda ok so far (including leaving it overnight with some scalability tests) but not as well we we will need. We are using a V8 pool with Apache commons so each thread from tomcat is accessing instance from the pool. Currently pool is maximally expanding to 20 items. We are only using V8 without NodeJS. What we found is the following.

On one concurrent user the page renders very fast, 20 ms and page is relatively complex (data model + UI), on 10 concurrent users suddenly (after pool heats up) everything slows down dramatically. From 20 ms per user to 500 ms.

After digging more and more I found this to be expensive an operation:

```
Object modelAttributes = V8ObjectUtils.getV8Result(v8, model);
```

This map that is passed from backend is a bit complex and nested but not too much, I could post it as well. It is really slow to convert this Java map to j2v8 V8 object map. Is it possible that there is some sort of static variable shared between V8 instances on the native level that is doing blocking?

**Comment by matiwinnetou** [comment]
Any help here would be appreciated. Perhaps multiple V8 should not be created per one JVM? Most projects I see where j2v8 is used are to mobile development (android), like tabris.js where perhaps one J2V8 for the whole runtime is totally fine.

**Comment by matiwinnetou** [comment]
Despite the fact that my OSX has 4 * 2 = 8 threads I see CPU resource utilization for this JVM process at around up to 200%, which means that others threads are sitting on hands.

**Comment by matiwinnetou** [comment]
```
ab -c 10 -n 10 http://localhost:8181/fahrzeuge/einfache-suche
```

**Comment by matiwinnetou** [comment]
one concurrent users looks really impressive:
```
Every 2.0s: ab -c 1 -n 1000 http://localhost:36061/fahrzeuge/einfache-suche                                                                                                                                                                             Tue Jun 13 17:49:12 2017
This is ApacheBench, Version 2.3 <$Revision: 1604373 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Completed 600 requests
Completed 700 requests
Completed 800 requests
Completed 900 requests
Completed 1000 requests
Finished 1000 requests


Server Software:        Apache-Coyote/1.1
Server Hostname:        localhost
Server Port:            36061

Document Path:          /fahrzeuge/einfache-suche
Document Length:        27846 bytes

Concurrency Level:      1
Time taken for tests:   25.139 seconds
Complete requests:      1000
Failed requests:        0
Total transferred:      28553000 bytes
HTML transferred:       27846000 bytes
Requests per second:    39.78 [#/sec] (mean)
Time per request:       25.139 [ms] (mean)
Time per request:       25.139 [ms] (mean, across all concurrent requests)
Transfer rate:          1109.17 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.0      0       0
Processing:    16   25  11.3     19     102
Waiting:       15   24  10.2     19     100
Total:         16   25  11.3     20     103

Percentage of the requests served within a certain time (ms)
  50%     20
  66%     24
  75%     32
  80%     34
  90%     40
  95%     48
  98%     56
  99%     66
 100%    103 (longest request)
```

**Comment by irbull** [comment]
Thanks for all this information.
`Object modelAttributes = V8ObjectUtils.getV8Result(v8, model);` is certainly an expensive operation as it's doing a deep copy, but I wouldn't expect J2V8 to scale poorly with multiple V8 runtimes. Each runtime is just a memory address in the native side, I looking quickly back through the code, I don't see anything shared between them other than some locking code when the runtime is created (to help ensure we only load one version of the library). 

Yesterday I noticed some code when functions are registered that give the GC a chance to run for up to 1 second, this seems overkill and I will remove that, but I don't think that's related to `getV8Result`.

**Comment by irbull** [comment]
I've got some good news (which I know, is rare). I can (A) reproduce this, and (B) I found the problem, and (C) I think I know how to fix it.

Here is a snippet that demonstrates the problem:
```
 @Test
    public void performanceTest() throws InterruptedException {
        Map<String, Object> child1 = new HashMap<String, Object>();
        Map<String, Object> child2 = new HashMap<String, Object>();
        child1.put("name", "tim");
        child2.put("name", "sue");
        List<Object> children = new ArrayList<Object>();
        children.add(child1);
        children.add(child2);
        Map<String, Object> job = new HashMap<String, Object>();
        job.put("title", "manager");
        job.put("years", 7);
        final Map<String, Object> person = new HashMap<String, Object>();
        person.put("first", "bob");
        person.put("last", "smith");
        person.put("job", job);
        person.put("children", children);

        long start = System.currentTimeMillis();
        int THREADS = 1;
        V8Thread threads[] = new V8Thread[THREADS];
        for (int j = 0; j < THREADS; j++) {
            threads[j] = new V8Thread(new V8Runnable() {

                @Override
                public void run(final V8 runtime) {
                    for (int i = 0; i < 10000; i++) {
                        V8Object v8Result = (V8Object) V8ObjectUtils.getV8Result(runtime, person);
                        v8Result.release();
                    }
                }
            });
            threads[j].start();
        }
        for (V8Thread v8Thread : threads) {
            v8Thread.join();
        }
        long end = System.currentTimeMillis();
        System.out.println("total time " + (end - start));
    }
```
As you change the value of `THREADS` the total running time does not increase linearly as expected.

The *problem* is how we acquire the `Locker` in the native code on every V8 call. We acquire and release the Locker each time, and I guess there is some shared state in here. However, there is no need to acquire the `Locker` each time. In fact, we have a J2V8 concept of a `Locker` too, which is independent of the V8 one. If we tie these two together, you'd only take a hit when you actually released the Locker.

I have prototyped removing this, and not only does it help the situation where we have multiple threads, it also improves performance of a single threaded app too. I have a few other things in my workspace to finish off first, but I'll try to get this in before I cut the next release.

Thanks again for this excellent bug report.

**Comment by matiwinnetou** [comment]
@irbull WOW Ian this is amazing news. Such improvements can make it more and more feasible to use this amazing project for server side rendering of ReactJS on JVM. If there is something I can do to help you to get this out let me know please. As a side note is there is any reason why J2V8 4.7.1 was released on maven central only for linux but not osx?

**Comment by irbull** [comment]
See #261. I just don't have the capacity to release all the platforms. It's currently a lot of manual steps (manually startup up machines, running builds, testing, etc...).  Having said that, there is some work in creating builds using VMs for different platforms. If we get that done, then I can release on all platforms that we have the builds for. I managed to get Linux and Android working so far. 

As for this particular issue, it's going better than I expected. I will have a SNAPSHOT for Linux and Android ready today.

**Comment by irbull** [comment]
@matiwinnetou Can you test this? I have pushed a SNAPSHOT to maven central. To check that you have the right version `V8#getSCMRevision` should return `c6d11fb82e70e363e8b974a9a4b16dadcd502755`.

**Comment by matiwinnetou** [comment]
Sure I will test this today. Thank you for SNAPSHOT from maven central

**Comment by matiwinnetou** [comment]
Actually it is not easy to test this for me, I don't know how to work with AAR files:

https://oss.sonatype.org/content/repositories/snapshots/com/eclipsesource/j2v8/j2v8/4.8.0-SNAPSHOT/

**Comment by matiwinnetou** [comment]
I think I found this:
https://oss.sonatype.org/content/repositories/snapshots/com/eclipsesource/j2v8/j2v8_linux_x86_64/4.8.0-SNAPSHOT/

**Comment by matiwinnetou** [comment]
So far it is quite bad but maybe bugs are in my code. One request worked and then when object is in pool releasing maybe doesn't work...

**Comment by matiwinnetou** [comment]
```

**Comment by matiwinnetou** [comment]
I am digging into this. A simple scenario of creating v8 on each request and tearing it up works, although it is way to slow for us (that is why we need pooling)

**Comment by matiwinnetou** [comment]
I can see that the problems I am already having in 4.7.1, I wanted to study all changes now from 4.6.0 to 4.7.1 to understand what is happening but then I ran into git push -f issue and master history was lost...

**Comment by matiwinnetou** [comment]
OK, with 4.7.1 I checked and it works (no locking problems) but so far 4.8.0-SNAPSHOT doesn't work very well. I need to run more checks again. At least I know that the issues are not introduces in j2v8 4.7.1 on linux. Yesterday my tests that I ran and reported were against both j2v8 4.6.0 on osx and linux (results almost the same).

I need to continue and check more j2v8 linux 4.8.0-SNAPSHOT, perhaps there are other changes that could affect this other than the ones made yesterday.

**Comment by irbull** [comment]
Hum. The change yesterday should not have affected the Java threads in any way, it just twiddled the Native lock whenever the Java lock was invoked. So if you are seeing deadlock issues in Java it must be from something else that was introduced. I merged a PR yesterday that checked if locks were released in CheckThread (https://github.com/eclipsesource/J2V8/commit/c371c99a561450d1dc8efa55d38bd457a21031ac). I don't think it's related, but anything is fair game.

**Comment by irbull** [comment]
I've looked at this a bit closer, and I didn't realize that acquiring the native lock causes the system to wait (I thought it would fast fail if the lock could not be acquired). This means that yesterdays change could cause a deadlock.

Having said that, J2V8 tries to fast fail if the lock cannot be acquired. But it appears it's not doing this properly in some case. Any help you can give as to what threads have locks, would be great appreciated.

**Comment by irbull** [comment]
Found it. See #277

**Comment by matiwinnetou** [comment]
+1 thank you for your support. As said I hope you can push SNAPSHOT to sonatype for testing.

**Comment by irbull** [comment]
Yep, I will do that. It's still early here for me (I'm on the west coast of
Canada).

**Comment by irbull** [comment]
SNAPSHOT available.

**Comment by matiwinnetou** [comment]
There was indeed issue with my locks and concurrency. I fixed those issues and now on 4.8.0 SNAPSHOT 

```

**Comment by matiwinnetou** [comment]
However on our integration system we have only one CPU! I cannot prove that this is them not lack of CPU... I will try to check on this tomorrow - on 8 core system)

**Comment by matiwinnetou** [comment]
![image](https://user-images.githubusercontent.com/335933/27190076-9aac3582-51f3-11e7-819c-cc19f23384fa.png)

**Comment by matiwinnetou** [comment]
one CPU 100% utilization.

**Comment by irbull** [comment]
> one CPU 100% utilization?

Is that good? I don't know what your app does, so I don't know if tis is expected. Also, what about the performance? In the previous run, you had 1000 tests, but this on you only had 100.

**Comment by matiwinnetou** [comment]
Yes this is good I am expecting this. Rendering of templates is expensive operation (CPU bound) and our integration systems are on low resources.

Last time I was testing on OSX with 4.6.0. Now I cannot (SNAPSHOT only on linux). I spoke with SiteOps (our support) and I will get tomorrow 4-8 processors on this machine tomorrow. I will keep you posted. Test has been now running for 1 hour and without any locks, deadlocks errors, etc. It will ran for the whole night though. Looks so far good but more tests are needed and reporting - if it really improves performance.

**Comment by matiwinnetou** [comment]
Nice to have friends in SiteOps, I got 8 cpus and 4 GB ram even in the evening (Berlin GMT+1 timezone) 

Results look that they are much improved. Results are worse than out SOY templates (google) but this was expected.

Clearly a lot of processors are used so I am sure processors are used.

```
Summary:
  Total:        0.8970 secs
  Slowest:      0.2035 secs
  Fastest:      0.0359 secs
  Average:      0.0852 secs
  Requests/sec: 111.4817

Detailed Report:

        DNS+dialup:
                Average:        0.0004 secs
                Fastest:        0.0000 secs
                Slowest:        0.0050 secs

        DNS-lookup:
                Average:        0.0002 secs
                Fastest:        0.0000 secs
                Slowest:        0.0043 secs

        Request Write:
                Average:        0.0001 secs
                Fastest:        0.0000 secs
                Slowest:        0.0010 secs

        Response Wait:
                Average:        0.0836 secs
                Fastest:        0.0350 secs
                Slowest:        0.1980 secs

        Response Read:
                Average:        0.0011 secs
                Fastest:        0.0001 secs
                Slowest:        0.0071 secs

Status code distribution:
  [200] 100 responses

Response time histogram:
  0.036 [1]     |∎∎
  0.053 [22]    |∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.069 [16]    |∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.086 [20]    |∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.103 [23]    |∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
  0.120 [7]     |∎∎∎∎∎∎∎∎∎∎∎∎
  0.136 [1]     |∎∎
  0.153 [0]     |
  0.170 [0]     |
  0.187 [4]     |∎∎∎∎∎∎∎
  0.203 [6]     |∎∎∎∎∎∎∎∎∎∎


Latency distribution:
  10% in 0.0450 secs
  25% in 0.0567 secs
  50% in 0.0800 secs
  75% in 0.0969 secs
  90% in 0.1770 secs
  95% in 0.1941 secs
  99% in 0.2035 secs
```

**Comment by matiwinnetou** [comment]
I decided to turn up the heat as well. My pool is max 20 v8s for the moment:

![image](https://user-images.githubusercontent.com/335933/27197507-b5b6893e-520e-11e7-8348-deb1ae28dc5d.png)

**Comment by matiwinnetou** [comment]
I have a question though:
What is anticipated cost to java memory and native memory for each V8 instance (empty without any variables)? Is also native memory taken (outside of JVM?)

**Comment by matiwinnetou** [comment]
![image](https://user-images.githubusercontent.com/335933/27479000-35d459d0-5812-11e7-8823-2e7cc6dc807a.png)
