### ISSUE TITLE
Deadlock in new locker functionality

### ISSUE THREAD

**Issue by irbull** [eclipsesource/J2V8#277]
It appears the V8 Locker uses a counting semaphore instead of a binary semaphore like I assumed. The Java version I wrote `V8Locker` uses a binary semaphore. This can quickly lead to a deadlock. 

Here is a testcase that demonstrates the problem.
```
    @Test
    public void testMultiThread() throws InterruptedException {
        v8.getLocker().acquire();
        v8.getLocker().release();
        // I assumed the instance is released, but it's not. It's count is now at 1 :-(
        Thread t = new Thread(new Runnable() {

            @Override
            public void run() {
                v8.getLocker().acquire();
            }
        });
        t.start();
        t.join();
    }
```

**Comment by matiwinnetou** [comment]
+1, I would appreciate to push a SNAPSHOT so I can test this tomorrow on our QA machine.
