### ISSUE TITLE
Issue calling functions in variable?

### ISSUE THREAD

**Issue by vtec11001** [eclipsesource/J2V8#282]
Hello I currently have a function that I am trying to call/execute in java via J2V8. I have provided the code below:
`var runner_variable = 
{
	runner : function (input_var)
	{
		return eval(input_var); 
	}
}//this is the js code`

here is the java code

 `		runtime.executeScript(js_script); 
		V8Object test_object = runtime.getObject("runner_variable");
		test_object.executeJSFunction("runner", "jsonata"); 

		
		V8Array array = new V8Array(runtime).push("jsonata"); 
		System.out.println(test_object.executeStringFunction("runner", array)); `

my question is how exaclty would I get the internal js function (mapped to runner) to run. I ask this because when I try to run my java code I get a undefined error for the function. I understand the funciton is anonymous, but I assumed that because it is mapped to an object (similar to the getting started guides)  that it would run fine. 

I was wondering if I could get input on how to get this funciton to run. Also if I have a sitation where I am trying to run a function  mapped to nothing such as this

var input_data = (function() {

--code--

})(); 
 

I am currently unsure how to call this line of code as this funciton is not mapped to anything. Any help is appreciated, thanks.

**Comment by irbull** [comment]
I don't really understand the problem. This works for me:
```
        String jsCode = "var runner_variable = { runner : function (input_var) { return eval(input_var); } }";
        v8.executeScript(jsCode);
        V8Object test_object = v8.getObject("runner_variable");
        V8Array array = new V8Array(v8).push("'foo' + 'bar'");
        System.out.println(test_object.executeStringFunction("runner", array));
        test_object.release();
        array.release();
```

As for accessing functions directly, you can use a `V8Function`.
```
        String jsCode = "var runner_variable = { runner : function (input_var) { return eval(input_var); } }";
        v8.executeScript(jsCode);
        V8Function runner = (V8Function) v8.executeScript("runner_variable.runner");
        V8Array array = new V8Array(v8).push("'foo' + 'bar'");
        System.out.println(runner.call(null, array));
        runner.release();
        array.release();
```

**Comment by irbull** [comment]
I'm going to close this. @vtec11001 If that didn't answer your question, or you still believe there is a bug, please let me know.

**Comment by vtec11001** [comment]
Hi sorry for the delay, turns out or issue is due to something in our JS file. I got sidetracked with another task and thus the lack of response. Thank you.
