### ISSUE TITLE
How can I limit cpu and memory quota for script with j2v8?

### ISSUE THREAD

**Issue by phenrigomes** [eclipsesource/J2V8#290]

**Comment by matiwinnetou** [comment]
I don't think you can do this, at least would be hard to imagine how this could work. The only thing you can do is to run j2v8 in a docker, lxc or some other container and then limit resources per *WHOLE* j2v8 JVM process.

AFAIK, the functionality you are asking is not even available for JVM. At most one can change priorities for JVM threads.

**Comment by phenrigomes** [comment]
I need an way to run a custom code. I tried nashorn, but j2v8 has is faster with V8. I am trying a way to avoid endless loop and to add cpu quota with j2v8.

Does anyone know if I can run a NodeJS code but blocking require for http packages and block access to the file system?

I think nashorn a good choice for this, but I want to know about j2v8.

**Comment by irbull** [comment]
You can't do this with J2V8. But the more important question is, can you do this with V8 (J2V8 is just a wrapper around V8, so it can only do as much as V8 can do)? If you can find a V8 API that does this, I'd be happy to expose this through J2V8. If you know of the V8 API, please re-open this issue, and we can add this to the plan.
