### ISSUE TITLE
V8ObjectUtils.toList() returns V8PropertyMap which is not an API class

### ISSUE THREAD

**Issue by GrahamBorland** [eclipsesource/J2V8#291]
If I call `V8ObjectUtils.toList(v8Array)` on a `V8Array` whose members are `V8Object`s, then the resulting list contains objects of type `V8PropertyMap`.

I can't do anything with these objects, since `V8PropertyMap` is a package-private class.

How are we supposed to use these objects?

**Comment by GrahamBorland** [comment]
OK, I can just treat the returned objects as being instances of `Map<String, ? super Object>`. Sorry for the noise.

**Comment by irbull** [comment]
Yep, just treat them as a map. The reason for this is because `HashMaps` don't allow for self containment, a common pattern in JavaScript Objects.
