### ISSUE TITLE
How can I debug on version 4?

### ISSUE THREAD

**Issue by phenrigomes** [eclipsesource/J2V8#293]
I am using eclipse for development and I want debug the JS code. Is there an way to debug remotely?

**Comment by irbull** [comment]
V8 has dropped support for their debug agent, so Eclipse debugging is no longer possible. There is an API for debugging, but you'd have to build your own debugger client either from scratch, or using an existing technology such as [http://facebook.github.io/stetho/](http://facebook.github.io/stetho/).
