### ISSUE TITLE
WebSockets / Socket.io

### ISSUE THREAD

**Issue by WolfieWerewolf** [eclipsesource/J2V8#294]
Hi, nice project.  I just wondered if anyone had any luck using it for websocket client side communication?  I just did a very simple test; the socket.io demo chat app will do.  I just called a simple script that consumes the socket.io-client (latest) library and connects to a node.js back end over http and it failed silently.  Executing the same script via node.js on the terminal works and also running the script interactively via the REPL.  I'm on OSX.  I've attempted using both the latest maven build as well as compiling from source 64 bit build (32 bit wouldn't link on my machine for some reason).  I didn't attempt with maven 32 bit.
Thanks for any ideas or suggestions in advance.
Kind Regards

**Comment by irbull** [comment]
I don't have any experience with this. Since nobody else has been able to help I'm going to close this issue. Maybe someone on StackOverflow can help. Sorry :(
