### ISSUE TITLE
Support for Linux/ARM

### ISSUE THREAD

**Issue by brucej72** [eclipsesource/J2V8#295]
Given there is already support for Linux/x86 and also ARM/Android, it doesn't seem like a huge stretch to make the changes necessary to support Linux/ARM. 

Node.js is already portable to Linux/ARM and there are many environments (RPi, for example) where this would be super-useful.

**Comment by matiwinnetou** [comment]
RPi can barely run such a resource hog like java...

**Comment by matiwinnetou** [comment]
I see no business relevance to this personally except pet projects.

**Comment by matiwinnetou** [comment]
@irbull opinions?

**Comment by Mizumi** [comment]
This would be an excellent feature/platform to have on hand. Having the ability to embed a scripted runtime on a device like the RPi + Java opens a few interesting doors, and I was considering running a cross-compile of ARM a while back for this exact reason.

**Comment by irbull** [comment]
I'm closing this as out of scope. Sorry, but I'm barely able to build/maintain the Android platforms. If someone does want to maintain these builds, please let me know.
