### ISSUE TITLE
Question: how do I proxy a Java method as a JS property

### ISSUE THREAD

**Issue by kipz** [eclipsesource/J2V8#297]
I Java land, I have a bunch of Java classes that I can't change the signature of. 

Some of those classes have no-arg methods which I'd like to expose as properties of the corresponding object in V8. I can call the Java method upfront and add a V8Object containing the result.

However, I'd really rather not eagerly call all these no-arg Java methods if the properties might not be accessed from JavaScript, especially if those methods are expensive.

Is there a way of doing this? Perhaps by extending V8Value somehow?

I think what I'd really like is the ability to register a `JavaPropertyCallback` much like we do for method callbacks, basically giving the Java side an opportunity to set a property value in response to a callback. I expect this would be useful for other use cases too.

Any suggestions or guidance would be much appreciated.

**Comment by kipz** [comment]
After some more googling, it looks like I might be able to use ES6 Proxies or getters/setters to achieve this. Anybody got any experience doing this with J2V8?

**Comment by ewized** [comment]
Yeah using ES6 proxies will get what you want, I currently have both Java and Js use proxies to dynamically call function/method from each side.

**Comment by kipz** [comment]
Perfect. Thanks. I'll do that for sure! :)
