### ISSUE TITLE
Attempting to call functions within functions

### ISSUE THREAD

**Issue by vtec11001** [eclipsesource/J2V8#298]
Hello I have a question in regards to calling functions within functions. Below is a rough sketch of the JS script I am calling with J2V8:

`var jsonTest = function()
{

      function jsonTest(input)
      {
         return 
         {
            evaluate : function (input)
                   { .....
                    }
          }
      }
  jsonTest.parser = parser; 
}`

I essentially need to call execute script with the j2V8 runtime and first execute the jsonTest function. Then from that output I need to then execute the evaluate function. Currently when I do this (after calling the main executeScript function in java with the runtime) I use the runtime.getObject("jsonTest") to try to get jsonTest variable so I can call the respective functions on it but upon doing so the getObject does not return the jsonTest variable but rather the parse object that is shown near the end of the code which has nothing to do with what I want at the moment. I was wondering how I could circumvent this and simply just run my execuate script and then call the jsonTest funciton and then get/run the evaluteFunction from that output. Thank you.

**Comment by ewized** [comment]
Are you calling the jsonTest() function? Your description sounds like you are just executing the script but then getting the instance of jsonTest but never executing it.

**Comment by irbull** [comment]
@ewized Is right, it doesn't sound like you're calling the function. When you call `runtime.getObject("jsonTest")` you should be able to cast that to `V8Function` and `call()` it. Then get the object returned from that function and get `evaluate` from there.

**Comment by vtec11001** [comment]
ok I tried to emulate what you said but it keeps calling the jsonTest.parser here is my code:

`
		V8Array arrayJsonata = new V8Array(runtime).push(jsonPath[0]); 		
		V8Object jsonTest = runtime.getObject("jsonTest"); 
		
		
		V8Function jsontestFunction = (V8Function)jsonTest; 
		V8Object evaluate = (V8Object) jsontestFunction.call(null, arrayJsonata); 
		V8Function evaluateFunction = (V8Function)evaluate; 
		System.out.println(evaluateFunction.call(null, arrayJsonata));




`

the place of fault is happenening at jsontestFunction call, I am still new to j2v8 so any help is appreciated.

**Comment by irbull** [comment]
Honestly, I'm not entirely sure what the JS code you have is supposed to do. You have a function called `jsonTest`, and in the body of that function you define a function called `jsonTest`. And in the body of that function you return an object with a properties `evaluate` and a value of another function.

But here is a small snippet that shows how you can call one function that returns an object, and then you can get a property from that object (that is another function) and cal that:
```
    @Test
    public void test() {
        MemoryManager memoryManager = new MemoryManager(v8);
        String script = "var jsonTest = function(input) {\n"
                + "return { evaluate: function() { return input; }};\n"
                + "}";
        v8.executeScript(script);
        V8Function function = (V8Function) v8.get("jsonTest");
        V8Array parameters = new V8Array(v8).push("foo");
        V8Object outterResult = (V8Object) function.call(null, parameters);
        V8Function innerFunction = (V8Function) outterResult.get("evaluate");
        String result = (String) innerFunction.call(null, null);
        assertEquals("foo", result);
        memoryManager.release();
    }
```

**Comment by vtec11001** [comment]
@irbull thank you. So I think I found the issue and it is that when I do v8.get("jsonTest") instead of pulling the jsonTest variable it is pulling the a line of code (menionted in my intial post see near the end of the variable block) jsonTest.parse. J2V8 is treating jstonTest as a key to this parse variable. I was wondeirng if there is any way to avoid this confusion without possibly changing the internal code? I understand the code is rather complicated but I have been told to avoid having to change it/modify it. Thank you.

**Comment by vtec11001** [comment]
@irbull  please ignore my previous comment, I apologize but I think I may have misread the error on my eclipse console I think the error may perhaps be in the script I am running. I will notify of any updates thank you for your help

**Comment by irbull** [comment]
I'm going to close this issue. If you can post a snippet (or better yet, a test case) that demonstrates a problem, that would be great!
