### ISSUE TITLE
Trying to run Jsonata via J2V8 (similar issue posted preivously)

### ISSUE THREAD

**Issue by vtec11001** [eclipsesource/J2V8#299]
Hello I previously made an issue similar to this that was closed and it was noted that a better sample/test case of code would help. I have this now and would like to better demonstrate the problem:

1. I am attempting to use J2v8 to run the jsonata.js script from the jsonata project (it can be found here: https://github.com/jsonata-js/jsonata). With this open source code we are attempting to call the Jsonata function, and use its result to call the evaluate function in it. Currently my team has done this via nashorn. Our code via nashorn is presented below:

`
        Invocable inv = (Invocable) scriptEngine;
        scriptEngine.put("input", jsonString);
        Object inputjson = scriptEngine.eval("JSON.parse(input);");

        // query the data
        Object expr = inv.invokeFunction("jsonata", jsonPath);
        Object resultjson = inv.invokeMethod(expr, "evaluate", inputjson);

        // JSON.stringify the result
        scriptEngine.put("resultjson", resultjson);
        result = scriptEngine.eval("JSON.stringify(resultjson);");
`

We wanted to use J2V8 as we understand this is the fastest library for running JS via Java. In previous issues it was brought to my attention that to run this code I would need to follow a format similar to this in J2V8:

`
		V8Function jsonataFunction = (V8Function)runtime.getObject("jsonata"); 
				
		V8Array arrayJsonata = new V8Array(runtime).push(jsonPath[0]); 
		//jsonPath[0] is basically a string 

		V8Object jsonataResult = (V8Object) jsonataFunction.call(null, arrayJsonata);
		
		V8Function evaluateFunction = (V8Function) jsonataResult.get("evaluate"); 
		System.out.println(evaluateFunction.call(null, null)); 

`
However when we run this we get an error saying java is not defined: 

`
Exception in thread "main" undefined:3390: ReferenceError: java is not defined
            throw err;
            ^
    ReferenceError: java is not defined
        at post_parse (<anonymous>:1033:29)
       at post_parse (<anonymous>:1016:38)
       at post_parse (<anonymous>:1005:40)
       at post_parse (<anonymous>:999:41)
       at post_parse (<anonymous>:999:41)
       at post_parse (<anonymous>:999:41)
       at parser (<anonymous>:1171:16)
       at jsonata (<anonymous>:3386:19)
   com.eclipsesource.v8.V8ScriptExecutionException
	at com.eclipsesource.v8.V8._executeFunction(Native Method)
	at com.eclipsesource.v8.V8.executeFunction(V8.java:1000)
	at com.eclipsesource.v8.V8Function.call(V8Function.java:80)
	at poc_jtov8.NewRunner.main(NewRunner.java:44)

`
When we run the analogus code in nashorn we get no error and the code executes fine this is not the case in J2v8 even though I think we are following the J2v8 format. 

With this said I was wondering what the best way to run this code via J2V8 would be given our current Nashorn code shown above as we keep getting this reference error in our j2v8 implementation. In my previous postings I did not provide a clear sample  of code (the jsonata.js file is present in the github link to the project) but I hopefully have here. Any help is appreciated, thank you!

**Comment by irbull** [comment]
Nashhorn problem injects additional properties into the runtime. I guess it has something called `java`. J2V8 does not inject anything. I think this is out of scope for J2V8.
