### ISSUE TITLE
capturing node.js file output to java variable

### ISSUE THREAD

**Issue by vtec11001** [eclipsesource/J2V8#301]
Hello I had a quick question regarding capturing node.js output to a java variable. We are currently calling this node.js script: 

`

var jsonataFile = require('jsonata');
var fs = require("fs");
//var contents = fs.readFileSync("activity.json");

var data = {
    example: [
        {value: 4},
        {value: 7},
        {value: 13}
    ]
};

var expression = jsonataFile("$sum(example.value)");
var result = expression.evaluate(data);
console.log(result);
return result; 
`

The result is 24 which is echoed in the console. We are then calling it with this Java code:
`	public static JSObject createFS(NodeJS node) throws IOException
	{
		V8Object export = node.require(new File("node_jsonanta.js file directory")); 
		
		
		try
		{
			return new JSObject(export); 
		}
		
		finally
		{
			export.release(); 
		}
}
		
----Main method-----	

	        private static NodeJS nodeJS; 

		nodeJS = NodeJS.createNodeJS();
		
		JSObject fs = createFS(nodeJS); 
//create/run js file 

`

We are essentially just trying to capture the output of the file/result variable and save it to a variable in java but we cant. The most we can do is embedded a console.output(result) in our node.js which will then be echoed in our eclipse/java console. I was wondering if there was anyway we could directly access the result variable after setting it to a V8object in java as right now we cannot. When we try to do a getObject or getKeys we get undefined/null/indexOutofBounds (for getKeys()). I should note we are using the opensource jsonata script from IBM. Any help is appreciated, thank you!

**Comment by vtec11001** [comment]
This issue has been solved.

**Comment by jonasdebeukelaer** [comment]
Hi there, I'm wondering the same thing as you here. Would you mind sharing how you got a value returned? Thanks!

**Comment by vtec11001** [comment]
Sure! As a preface however the way we implemented this was perhaps not the cleanest way..but at the time this is the best we could do. We were essentially trying to run a robust JSON path parsing library known as JSONATA, but should work with other formats/file types as well. Here is our code below:

`V8 v8 = V8.createRuntime(); 
v8.executeScript(--our script file--)
//read in js file that has you js code including functions that you plan on using. 
//Read your file as bytes and then convert to string. 

String result = v8.executeJSFunction("initJsonata", jsonString, jsonPath).toString();
//jsonata is the name of a function in our script
//jsonString and jsonPath are input parameters to the function. 

`
Essentially we just created a runner function in our input script (which is sent as a string to executeScript) js known as initJsonata which itself calls 2 functions known as jsonata and evaltuate (which are part of the JSONATA script), I would explain these in detail but I feel it might detract from the explanation read more here (https://github.com/jsonata-js/jsonata). We call this runner function using  executeJSFunction function which attempt to return a standard java Object. You can then cast that object to any specific object type you wish (in our case a string). 

The takeaway from this is that if you have a really complex function it might be better to simply do your logic in a runner function in JS and then call that runner function there. Please message if you have any questions as I understand I may have not explained this well enough.

**Comment by jonasdebeukelaer** [comment]
Thanks for taking the time to explain. So you switched over from using the NodeJS Class to the V8 class, so you could use the _excecuteJSFunction_ function? 

After a bit of thought, I think I might be able to avoid this issue all together, as I'm trying to create a PDF using node-d3, given some data sourced from Java. If I can run a function as you did then I won't need to return any data.

Side note: I had a look at the source code and it looks like you should be able to get data back from the nodejs exec using:
```Java
NodeJS nodejs = NodeJS.createNodeJS();
nodejs.exec(new java.io.File("node_script.js"));
V8Object obj = nodejs.getRuntime();
Object result = obj.getObject("node_js_object"));
```
given a variable in the node script called node_js_object. However I've been getting `undefined` for `result` using this method.

Cheers

**Comment by vtec11001** [comment]
In response to the top level question you asked, yes we switched to V8 over node because we could better extract our data by using the executeJSFunction. In regards to your point about node, we tried this method as well and had some issues bringing the Node.js result to a V8 object as you did. I am currently working on another task now but if I recall when we brought over our result to a normal V8 runtime or object it either gave a similar result such as undefined or it would not recognize the "require" keyword in nodejs (I believe this is when we tried to bring our Nodejs runtime to a standard V8 one.) Really our primary reason for using Node was because with Node.js we can easily import modules (normal JS dosent allow us to easily do this) and Jsonata can be pulled as a Node.js module. Again if you would like any clarification on the matter please feel free to ask, I will try to look at going a Node.js route again..

**Comment by jonasdebeukelaer** [comment]
Ok thanks. Yeah we're in the same boat regarding needing NodeJS functionality. If we do figure out the `undefined` issue I'll be sure to let you know.
Cheers
