### ISSUE TITLE
Can V8 class be extended?

### ISSUE THREAD

**Issue by spacelan** [eclipsesource/J2V8#316]
I want to implement one class that inherit from V8. And then I can use the instance of this class to construct V8Object...

**Comment by irbull** [comment]
They are not final, so technically, they can be, but I wouldn't suggest this. Each V8Object has a corresponding native resource (C++ Object) associated with it. If you extend V8Object, you'll have to ensure that you are properly handing the construction and deconstruction of these objects. I would instead wrap the V8Object if you can.
