### ISSUE TITLE
V8Object#toString throws exception when object is released

### ISSUE THREAD

**Issue by mpost** [eclipsesource/J2V8#317]
V8Object#toString throws exception when object is released

**Comment by irbull** [comment]
We use the native implementation of `toString()` which is why we the object handle to still exist. We can add a special case here, but we will just have to hard-code a result. Any suggestions on what to return when `toString()` is called on a released object?

**Comment by irbull** [comment]
Fixed with 53ef3df92bf77febf10f6abfad01669617538f06.
