### ISSUE TITLE
JSON support

### ISSUE THREAD

**Issue by angelozerr** [eclipsesource/J2V8#32]
I create this issue because I would like to  implement tern server with J2V8.

The tern server works with JSON for request/response. In tern.java the JSON object is created by using https://github.com/ralfstx/minimal-json. 

How to do that : 

 * transform com.eclipsesource.json.JsonObject to a com.eclipsesource.v8.V8 instance?
 * or call JsonObject .toString() and call V8 engine with this string?

Perhaps I need to create a V8 <-> JsonObject binding?

Sorry for my naive question, I don't know how to V8 works.

**Comment by angelozerr** [comment]
I close this issue. In my case I work with String : 

 * for request parameter, I convert my JsonObject to a (json) String and call the JS function generated with a string
 * this function returns a (json) String to load the JsonObject.

**Comment by irbull** [comment]
I'd like to re-open it. I do think it would be worth having a utility (like we have with V8Objects -> Map & Lists) to convert to JSON.

**Comment by angelozerr** [comment]
It exists a lot of Java JSON API (minimal-json, etc), so I don't know how you could provide this utilities class without adding dependencies?

I had tried to create this utility class, but code was a little complex and I had to call release method for each field. It was very easy to do like I have explained. See https://github.com/angelozerr/tern.java/blob/master/core/tern.server.j2v8/src/tern/server/j2v8/J2V8TernServer.java#L77

**Comment by irbull** [comment]
I agree. Closing.
