### ISSUE TITLE
V8 can lose current Isolate

### ISSUE THREAD

**Issue by irbull** [eclipsesource/J2V8#321]
After lots of trial and error looking at #313, I've finally managed to get a test that sort of resembles this problem. The following crashes the JVM:
```
    @Test
    public void testLosesCurrentIsolate() {
        final V8 v8 = V8.createV8Runtime();
        v8.registerJavaMethod(new JavaCallback() {

            @Override
            public Object invoke(final V8Object receiver, final V8Array parameters) {
                V8.createV8Runtime().getLocker().release();
                throw new RuntimeException();
            }
        }, "foo");
        Object s = v8.executeFunction("foo", null);
        v8.release(false);
    }
```
There is no reason for this to crash the VM. 

If we watch the `Isolate::CurrentIsolate`, it starts with one Isolate, and after `V8.createV8Runtime()`, then `Isolate::CurrentIsolate` returns the second one. This all makes sense. However, when we throw the RuntimeException(), it's the second isolate that tries to manage this exception, even though it is handled in the `executeFunction` from the first isolate. 

I think this is related to the root cause of #313.

**Comment by matiwinnetou** [comment]
👍 amazing work.
