### ISSUE TITLE
V8 Thread access

### ISSUE THREAD

**Issue by liz3** [eclipsesource/J2V8#322]
Hello,

this question might be duplicated, so inform me if it is, but i was not able to find a solution.
 
I need to make actions on the v8 thread, but the invoke is coming from another thread, sadly a cannot change this.
So my question is, has this library some kind of run on?
The JavaFX equivalent for example is: `Platform.runLater` which takes a Runnable as parameter.

Kind Regards,

Liz3(Yann HN)

**Comment by Mizumi** [comment]
Hi Liz3!

Please check out the [ConcurrentV8](https://github.com/eclipsesource/J2V8/blob/master/src/main/java/com/eclipsesource/v8/utils/ConcurrentV8.java) class which does almost exactly what you're describing.  Here's an example of using it:

```
ConcurrentV8 v8 = new ConcurrentV8();
v8.run(new V8Runnable() {
    @Override
    public void run(V8 v8) {
        v8.executeVoidScript("var i = 3000;");
    }
});
```

Hope this helps,

Brandon

**Comment by liz3** [comment]
@Mizumi Jep that solved the problem, thank you very much!

Kind Regards,
Liz3
