### ISSUE TITLE
NodeJS module functions usage

### ISSUE THREAD

**Issue by parizene** [eclipsesource/J2V8#324]
Is it correct that to call js function multiple times from module I should first create `NodeJS` on start and release it on end in every method call?
```java
    public Object[] search(@NonNull String query) {
        Object[] searchResults = null;
        
        NodeJS nodeJs = NodeJS.createNodeJS();
        V8 runtime = nodeJs.getRuntime();
        V8Object core = nodeJs.require(new File("node-modules-folder-path", "node-js-core-module"));
        
        V8Function callback = new V8Function(runtime, (receiver, parameters) -> {
            final V8Object errorObj = parameters.getObject(0);
            if (errorObj != null) {
                String message = errorObj.getString("message");
                errorObj.release();
            } else {
                V8Object searchResultsObj = parameters.getObject(1);
                searchResults = convert(runtime, searchResultsObj);
                searchResultsObj.release();
            }
            return null;
        });

        core.executeJSFunction("search", query, callback);

        while (nodeJs.isRunning()) {
            nodeJs.handleMessage();
        }

        callback.release();

        core.release();
        try {
            nodeJs.release();
        } catch (IllegalStateException e) {
        }
        
        return searchResults;
    }
```
If I create `NodeJS` only once, and call same `search()` method next time, `nodeJs.isRunning()` is never `true`, so callback never called. Am I missing something?

**Comment by matiwinnetou** [comment]
NodeJS is non blocking, your method call is blocking. How possibly this could even work?

**Comment by parizene** [comment]
@matiwinnetou yes, it works, it is implemented according to the tutorial in article, so how it should be done to support multiple calls?

**Comment by bergi9** [comment]
so, how i do call the call-method asynchronously without wait for the while loop?

**Comment by bergi9** [comment]
@parizene call `nodeJs.handleMessage()` before you enter into the while loop.

**Comment by parizene** [comment]
@bergi9 thanks! don't know why, but it works now. can you please explain why do I need it before loop?

**Comment by bergi9** [comment]
@parizene at `NodeJS.createNodeJS();` will set the `isRunning` flag on `true` (on JNI). After calling `nodeJs.handleMessage();` (if the loop is done) the `isRunning` flag is set to `false`. On the next call of `nodeJs.isRunning()` it's still `false`.
I reviewed my code above and set it to
```
do {
    nodeJs.handleMessage();
} while (nodeJs.isRunning())
```
No need to call `nodeJs.handleMessage();` before entering the `while` loop anymore.
It doesn't care if the eventloop is still running or not and you call the `nodeJs.handleMessage()`.
