### ISSUE TITLE
Multithread support

### ISSUE THREAD

**Issue by dipacs-ds** [eclipsesource/J2V8#33]
I know that javascript isn't support multiple threads, and what I need is creating multiple V8 engine instances on different threads and access this engine instances parallel. 

At this time, i can create multiple V8 engine instances, all the instances can be accessed from one single thread, because the V8 class stores the thread which created the first instance in a static field called thread, and later every method call the checkThread() method.

I want to use V8 in a server environment where every request creates a new V8 instance and execute some script in it and after kill it. And every request has a separated thread. But now I can't do this.

**Comment by irbull** [comment]
This is because of debug is supported. The version of V8 uses and old debug protocol, but it cannot support multiple threads (it holds a global singleton to the V8 thread). We ensure that all V8 calls are done on the same thread. This will require us to update the version of V8, and then update the debug support (See Issue #35 ).

**Comment by angelozerr** [comment]
@irbull for ternjs server, I need to create a V8 class per Eclipse project which have tern nature. Indeed I create an instance of ternjs per project because each project have some dirrent configs and dosn't host the same JS files.

Have you an idea how to I can do that? Create one V8 instance and in my JS create a JS Array which stores the whole instance of ternjs instance server?

**Comment by angelozerr** [comment]
@irbull I have started implementation of tern server with J2V8. See https://github.com/angelozerr/tern.java/tree/master/core/tern.server.j2v8

You will see that I have a problem with multi-thread. In tern.java I have a thread which create the tern server implementation and when completion is executed, it executes the tern server in another thread and I have this problem

```
java.lang.Error: Invalid V8 thread access.
	at com.eclipsesource.v8.V8.checkThread(V8.java:246)
	at com.eclipsesource.v8.V8.executeStringScript(V8.java:187)
	at com.eclipsesource.v8.V8.executeStringScript(V8.java:183)
	at tern.server.j2v8.J2V8TernServer.request(J2V8TernServer.java:79)
	at tern.server.j2v8.J2V8TernServer.request(J2V8TernServer.java:69)
	at tern.server.protocol.TernResultsProcessorsFactory.makeRequestAndProcess(TernResultsProcessorsFactory.java:36)
	at tern.eclipse.ide.internal.core.resources.IDETernServerAsyncReqProcessor.run(IDETernServerAsyncReqProcessor.java:104)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:53)
```

It should be cool if you could support multi thread. Thanks!

**Comment by Joe118** [comment]
Here's a vote-up for multithreading support.

**Comment by irbull** [comment]
Looking at this now.

**Comment by gorkem** [comment]
What is the plan here? Use v8::Locker? I have experimented a bit with that looks like it may work but have not tested the hard cases

**Comment by irbull** [comment]
I'll publish something later today, but my experiments have been to continue to use CheckThread but bind them to the V8 Runtime. That is, you each access to a single runtime (V8.createRuntime) must come from the same thread, as opposed to all runtimes must come from the same thread. 

To stress test this I created a merge sort that would split the array in two. Each half would then create a new thread (and new runtime) and call merge sort on that. And then I ran 10 of these in parallel. This should allow for the implementation of web workers.

**Comment by irbull** [comment]
Here is the initial work on this. It's been pushed to a V8_3_0 branch. https://github.com/eclipsesource/J2V8/commit/0eee3215dbcac229525ef70c32008cfb8f07b850

**Comment by irbull** [comment]
3.0.0-SNAPSHOT builds are now available. Here is some more information http://eclipsesource.com/blogs/2015/05/12/multithreaded-javascript-with-j2v8/

With this change, you only the thread that created the V8Runtime can interact with it. We could consider a Locker that would allow one thread to relinquish control. If this is interesting for someone, please file a bug.

**Comment by angelozerr** [comment]
> 3.0.0-SNAPSHOT builds are now available

where can I find it please?

```xml
 <dependencies>
    <dependency>
      <groupId>com.eclipsesource.j2v8</groupId>
      <artifactId>j2v8_win32_x86</artifactId>
      <version>3.0.0-SNAPSHOT</version>
      <scope>compile</scope>
    </dependency>
  </dependencies>
```

doesn't work for me -(

**Comment by irbull** [comment]
It's in the snapshot repository. Let me know if this helps.
````
      <repositories>
       <repository>
         <id>snapshots-repo</id>
         <url>https://oss.sonatype.org/content/repositories/snapshots</url>
         <releases><enabled>false</enabled></releases>
         <snapshots><enabled>true</enabled></snapshots>
       </repository>
     </repositories>
````

**Comment by angelozerr** [comment]
> Let me know if this helps.

Yes thanks!

**Comment by irbull** [comment]
I'll update the blog post

**Comment by angelozerr** [comment]
@irbull your fix doesn't resolve my problem with tern server.

> All interactions with a V8Runtime must be from the thread that instantiates the Runtime.

This restriction is a big problem for me. In my case I have, the thread which must execute JavaScript changes every time : I create a tern server JavaScript variable in a Thread, and when completion is executed, a new Thread is created to use this tern server.

Have you an idea how I could fix my problem? Many thank's for your help!

**Comment by irbull** [comment]
Yep, I put that in bold because I thought that might be a problem for you
:-). Your problem should be the easy problem to solve. Instead of checking
that all interactions come from the same thread I'll create a locker, and
then we'll check that all interactions come from the thread with the
locker. The locker can be acquired and released. With this approach you can
release the locker after you create the JavaScript variable, and then
acquire it in the new thread before you use it.

Can you file a bug and mark it 3.0? I should be able to get it together
later this week.

On Tue, May 12, 2015 at 11:51 PM, Angelo <notifications@github.com> wrote:

> @irbull <https://github.com/irbull> your fix doesn't resolve my problem
> with tern server.
>
> All interactions with a V8Runtime must be from the thread that
> instantiates the Runtime.
>
> This restriction is a big problem for me. In my case I have, the thread
> which must execute JavaScript changes every time : I create a tern server
> JavaScript variable in a Thread, and when completion is executed, a new
> Thread is created to use this tern server.
>
> Have you an idea how I could fix my problem? Many thank's for your help!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipsesource/J2V8/issues/33#issuecomment-101538165>.
>



-- 
R. Ian Bull | EclipseSource Victoria | +1 250 477 7484
http://eclipsesource.com | http://twitter.com/eclipsesource

**Comment by angelozerr** [comment]
> Yep, I put that in bold because I thought that might be a problem for you:-).

Ok:)

> Can you file a bug and mark it 3.0? I should be able to get it together later this week.

Done https://github.com/eclipsesource/J2V8/issues/46 but I cannot select the millestson (no right to do that)

It should be very cool if 3.0.0 could support : 

 * Java6. See https://github.com/eclipsesource/J2V8/issues/38
 * Osgify J2v8. See https://github.com/eclipsesource/J2V8/issues/37

Thank's for your support!

**Comment by irbull** [comment]
I'm going to close this as this work is done. I have put the locker work on the 3.0 plan.

**Comment by Joe118** [comment]
Thank you, this is an important improvement!

**Comment by dipacs-ds** [comment]
Thank you very much. You are awesome.

**Comment by angelozerr** [comment]
@irbull could you ping me please when 3.0.0-SNAPSHOT will be available with your changes to support multi threading with locker. It should be cool too if you could fix https://github.com/eclipsesource/J2V8/issues/37

Thanks!

**Comment by terwer** [comment]
> instantiates the Runtime.

Thanks，it worked for me
