### ISSUE TITLE
Multi threading issue

### ISSUE THREAD

**Issue by OoZe1911** [eclipsesource/J2V8#330]
Dear all,

I am not able to use J2V8 while calling it from a Java thread.

Here is a simple example :
My main class :

	package testV8;

	public class Test {

		public static void main(String[] args) {
			String script = new String();
			script = "var Field57a=\"@TEST@\";\n";
			script = script + "(Field57a.search(/@DUMMYTEST@/)  != -1)";

			Testthread t = new Testthread(script);
			t.start();
		}
	}

And the Testthread class :

	package testV8;

	import com.eclipsesource.v8.V8;

	public class Testthread extends Thread {
		public V8 v8 = V8.createV8Runtime();
		public String script=new String();

		public Testthread(String script) {
			this.script=script;
		}

		public void run() {
			System.out.println("Result = " + v8.executeBooleanScript(script));
		}
	}
-------------------------------
When running the main class :
Exception in thread "Thread-0" java.lang.Error: Invalid V8 thread access
	at com.eclipsesource.v8.V8Locker.checkThread(V8Locker.java:56)
	at com.eclipsesource.v8.V8.checkThread(V8.java:676)
	at com.eclipsesource.v8.V8.executeBooleanScript(V8.java:530)
	at com.eclipsesource.v8.V8.executeBooleanScript(V8.java:514)
	at testV8.Testthread.run(Testthread.java:14)

Maybe I did something wrong somewhere...but I do not know where ;)
Thanks for your help.
Fabrice

**Comment by matiwinnetou** [comment]
You need to lock a v8 instance for particular thread in order to use it.

**Comment by matiwinnetou** [comment]
https://github.com/eclipsesource/J2V8/blob/master/src/main/java/com/eclipsesource/v8/V8Locker.java

**Comment by matiwinnetou** [comment]
If your usecase is totally fine using only one V8, then it is best to use ConcurrentV8.java wrapper/helper.

**Comment by OoZe1911** [comment]
Thanks for your answer, but this is not clear for me yet. Based on the Javadoc, when calling createV8Runtime(),  the current thread is given the lock to this runtime. So no need to lock the v8 instance because it is already done for this thread.
My usecase is to run multiple threads, each thread having its own runtime. I do not want runtime sharing because I need to run multiple script at the same time.

**Comment by irbull** [comment]
In Java a `Thread` is not created until `start()` is called. So in your case, you're actually creating the V8Runtime on the `main` thread (because it's the thread that instantiates `Testthread`). Then you try to use J2V8 on the new thread you started. 

There is a `V8Thread` class you can use that will create a runtime and run a script for you, that might help. Otherwise create the runtime in the `start()` method.

**Comment by OoZe1911** [comment]
Thanks for your help !

Here is the corrected class :

	package testV8;

	import com.eclipsesource.v8.V8;

	public class Testthread extends Thread {
		private V8 v8 = null;
		public String script=new String();

		public Testthread(String script) {
			this.script=script;
		}

		public void run() {
			v8 = V8.createV8Runtime();
			System.out.println("Result = " + v8.executeBooleanScript(script));
		}
	}

and now this is working perfectly ! ;)

**Comment by irbull** [comment]
This looks much better!

Another thing to consider, you should release v8 in a finally block. If your `executeScript` throws an exception, you will blow your stack and `release` will never be called.

**Comment by OoZe1911** [comment]
Thanks, noted ;)
In fact I am using J2V8 in a much much complex use casse where exceptions are handled so the release is at the correct place ;) The previous class was only the smallest example I could wrote.

Thanks again for your help !
