### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by dipacs-ds** [eclipsesource/J2V8#34]
I can't find the 32 and 64 bit linux versions. Is there any plan to support these os versions?

**Comment by irbull** [comment]
I have 64 bit linux, but I've not tested it yet. I will make that available.

**Comment by Joe118** [comment]
I'm also very interested in a Linux version. Thanks!

**Comment by cwash** [comment]
I'd like to try it out as well -- thanks!

**Comment by magro** [comment]
+1 - there's really no linux version?! ;-)

**Comment by dgolovin** [comment]
I have locally built jar for linux x86_64 [here](https://github.com/dgolovin/j2v8forjsdt/tree/linux-gtk-x86_64/org.jboss.tools.jst.j2v8.linux.gtk.x86_64/lib) and it seems to work for me

**Comment by irbull** [comment]
x86_64 is now in the snapshot repo for J2V8 3.0. 
```
    <repositories>
       <repository>
         <id>snapshots-repo</id>
         <url>https://oss.sonatype.org/content/repositories/snapshots</url>
         <releases><enabled>false</enabled></releases>
         <snapshots><enabled>true</enabled></snapshots>
       </repository>
     </repositories>
```
```
<dependency>
  <groupId>com.eclipsesource.j2v8</groupId>
  <artifactId>j2v8_linux_x86_64</artifactId>
  <version>3.0.0-SNAPSHOT</version>
</dependency>
```
