### ISSUE TITLE
Reloading J2V8 library in OSGi

### ISSUE THREAD

**Issue by schaefa** [eclipsesource/J2V8#352]
Hi

We are using J2V8 in Apache Sling which uses Felix OSGi underneath. When I try to install J2V8 library:

<groupId>com.eclipsesource.j2v8</groupId>
<artifactId>j2v8_macosx_x86_64</artifactId>
<version>4.6.0</version>

one, use it and the load it again Java will complain that the Dynamic Library is already loaded with another class loader.

To fix that I added this line to the MANIFEST.MF of the artifact / bundle:

Bundle-NativeCode: libj2v8_macosx_x86_64.dylib; osname = MacOSX; process
 or = x86_64

This fixes the issue in question but causes the JVM to crash:

#   
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x000000013ac0f02a, pid=86799, tid=66307
#
# JRE version: Java(TM) SE Runtime Environment (8.0_31-b13) (build 1.8.0_31-b13)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.31-b07 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [libj2v8_macosx_x86_64.dylib+0x7902a]  v8::HandleScope::Initialize(v8::Isolate*)+0x5a
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/schaefa/Development/sling/9/peregrine-sling/hs_err_pid86799.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
Abort trap: 6

I have MacOS Sierra 10.12.6, JDK 1.8.0_31 and Apache Sling 9.

Thanks - Andreas Schaefer Sr.

**Comment by irbull** [comment]
Unfortunately, we have to reduce the scope of this project to Android targets. Others may be supporting other targets in downstream projects, but we haven't released OSGi bundles for a while now and I think it's better to be honest about the state of the project. Please see #441 for more information.
