### ISSUE TITLE
You have not accepted the license agreements of the following SDK components

### ISSUE THREAD

**Issue by DukeLee1989** [eclipsesource/J2V8#358]
Download https://jcenter.bintray.com/org/codehaus/plexus/plexus-container-default/1.0-alpha-30/plexus-container-default-1.0-alpha-30.jar
Download https://jcenter.bintray.com/org/codehaus/plexus/plexus-classworlds/1.2-alpha-9/plexus-classworlds-1.2-alpha-9.jar
Download https://jcenter.bintray.com/org/jacoco/org.jacoco.core/0.7.5.201505241946/org.jacoco.core-0.7.5.201505241946.jar
Download https://jcenter.bintray.com/org/jacoco/org.jacoco.report/0.7.5.201505241946/org.jacoco.report-0.7.5.201505241946.jar
Download https://jcenter.bintray.com/com/android/tools/common/25.2.2/common-25.2.2.jar
Download https://jcenter.bintray.com/com/android/tools/ddms/ddmlib/25.2.2/ddmlib-25.2.2.jar
Download https://jcenter.bintray.com/com/android/tools/annotations/25.2.2/annotations-25.2.2.jar
Download https://jcenter.bintray.com/commons-codec/commons-codec/1.4/commons-codec-1.4.jar
File /root/.android/repositories.cfg could not be loaded.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'temp'.
> You have not accepted the license agreements of the following SDK components:
  [Android SDK Build-Tools 24.0.3, Android SDK Platform 14].
  Before building your project, you need to accept the license agreements and complete the installation of the missing components using the Android Studio SDK Manager.
  Alternatively, to learn how to transfer the license agreements from one workstation to another, go to http://d.android.com/r/studio-ui/export-licenses.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

@irbull please help me，thank you

**Comment by DukeLee1989** [comment]
the root project "temp" where?

**Comment by DukeLee1989** [comment]
@irbull please help me，thank you

**Comment by zhutoulwz** [comment]
I also met the problem, how to fix ?

**Comment by zhutoulwz** [comment]
I had fixed the problem. The problem occurs because not accepted the licenses in your docker containers. So the solution is copying the accepted licenses folder from Android sdk Home folder to your docker containers.

Modify the file `docker/android/Dockerfile`, find the line 
> `RUN mkdir -p $ANDROID_HOME/licenses && echo -e "\8933bad161af4178b1185d1a37fbf41ea5269c55\n" > $ANDROID_HOME/licenses/android-sdk-license`, and modify it to this:
 > RUN mkdir -p $ANDROID_HOME/licenses && echo -e "\8933bad161af4178b1185d1a37fbf41ea5269c55\nd56f5187479451eabf01fb78af6dfcb131a6481e\n" > $ANDROID_HOME/licenses/android-sdk-license

**Comment by DukeLee1989** [comment]
@zhutoulwz  how much you generate aar ？

**Comment by zhutoulwz** [comment]
Exactly 8505621 bytes of j2v8-debug.aar.

**Comment by aleppos** [comment]
@zhutoulwz thanks.

> 8933bad161af4178b1185d1a37fbf41ea5269c55
> d56f5187479451eabf01fb78af6dfcb131a6481e
>

**Comment by irbull** [comment]
We have a new build system. Issue #40 is being used to track that we have the docs up-to-date. This particular issue doesn't seem to be a problem with the new build system.
