### ISSUE TITLE
where can I find the v4.8 windows releases?

### ISSUE THREAD

**Issue by jan4984** [eclipsesource/J2V8#359]
https://mvnrepository.com/artifact/com.eclipsesource.j2v8

there are linux and android version 4.8 releases, but missing windows and mac.

**Comment by SJava1** [comment]
Are there any plans for a windows release for 4.8.0 in the near future?  Trying to set up the build and build the code for windows is not quite working. :(

**Comment by hurol02** [comment]
I need the same: J2V8 4.8.0 for Windows 64 bits.
Essentially to be able to use a more recent version of NodeJS, in turn compatible with a more recent version of the V8 engine that supports es6.

It is not available in Maven public repositories (only much older 4.6.0 is, which fails to run modern NodeJS based app service layer written in TypeScript).

My attempts to build J2V8 from sources have failed:

- Instructions in BUILDING.md are incomplete (missing info about build dependencies such as Depot_Tools, CMake, MS Build Tools v14.0, Signtool, ... )  Would be a good idea to add those considerations to the doc, so people won't have to proceed by try-and-error.
 
- No idea where to find the certificate for Signtool...

- Choice #9 of build -i results in hundreds of warnings, a lot of them looking rather concerning for 64 bit system support, and ends up in error, as log extract below shows.

Any chance to get updated, complete build instructions or a jar file for J2V8 4.8.0 on Windows 64 bits?
This is a great library, and I am sorry I can't use it as it stands...

Thank you!
  -- OHM.
 

C:\Dev\J2V8>build -i

entering interactive mode...

[0] android-x86 @ Docker
[1] android-arm @ Docker
[2] alpine-linux-x64 @ Docker
[3] linux-x64
[4] linux-x64 @ Docker
[5] linux-x86 @ Docker
[6] macosx-x64
[7] macosx-x64 @ Vagrant
[8] macosx-x86 @ Vagrant
[9] windows-x64
[10] windows-x64 @ Docker
[11] windows-x64 @ Vagrant

Select a predefined build-configuration to run: 9
Building: windows-x64

Override build-steps ? (leave empty to run pre-configured steps):
Checking Node.js builtins integration consistency...
--------------------------------------------------
V8:      5.4.500.45 (candidate: False)
Node.js: 7.4.0 (release: True)
--------------------------------------------------
Caching Node.js artifacts...
>>> Node.js build-cache used: win32.x64

Microsoft Windows [Version 6.1.7601]
Updating Maven configuration (./docker/shared/pom.xml)...
SHELL building win32@x64 => nodejs
Looking for Visual Studio 2015
Found Visual Studio 2015
configure  --dest-cpu=x64 --tag= --enable-static
creating icu_config.gypi
* Using ICU in deps/icu-small
Using version-specific floating patch tools/icu/patches/58/source/i18n/digitlst.
cpp
creating icu_config.gypi
{ 'target_defaults': { 'cflags': [],
                       'default_configuration': 'Release',
                       'defines': [],
                       'include_dirs': [],
                       'libraries': []},
  'variables': { 'asan': 0,
                 'coverage': 'false',
                 'debug_devtools': 'node',
                 'force_dynamic_crt': 0,
                 'host_arch': 'x64',
                 'icu_data_file': 'icudt58l.dat',
                 'icu_data_in': '..\\..\\deps/icu-small\\source/data/in\\icudt58
l.dat',
                 'icu_endianness': 'l',
                 'icu_gyp_path': 'tools/icu/icu-generic.gyp',
                 'icu_locales': 'en,root',
                 'icu_path': 'deps/icu-small',
                 'icu_small': 'true',
                 'icu_ver_major': '58',
                 'node_byteorder': 'little',
                 'node_enable_d8': 'false',
                 'node_enable_v8_vtunejit': 'false',
                 'node_install_npm': 'true',
                 'node_module_version': 51,
                 'node_no_browser_globals': 'false',
                 'node_prefix': '/usr/local',
                 'node_release_urlbase': '',
                 'node_shared': 'false',
                 'node_shared_cares': 'false',
                 'node_shared_http_parser': 'false',
                 'node_shared_libuv': 'false',
                 'node_shared_openssl': 'false',
                 'node_shared_zlib': 'false',
                 'node_tag': '',
                 'node_target_type': 'static_library',
                 'node_use_bundled_v8': 'true',
                 'node_use_dtrace': 'false',
                 'node_use_etw': 'true',
                 'node_use_lttng': 'false',
                 'node_use_openssl': 'true',
                 'node_use_perfctr': 'true',
                 'node_use_v8_platform': 'true',
                 'openssl_fips': '',
                 'openssl_no_asm': 0,
                 'shlib_suffix': 'so.51',
                 'target_arch': 'x64',
                 'v8_enable_gdbjit': 0,
                 'v8_enable_i18n_support': 1,
                 'v8_inspector': 'true',
                 'v8_no_strict_aliasing': 1,
                 'v8_optimized_debug': 0,
                 'v8_random_seed': 0,
                 'v8_use_snapshot': 'true',
                 'want_separate_host_toolset': 0,
                 'want_separate_host_toolset_mkpeephole': 0}}
creating config.gypi
creating config.mk
Project files generated.
  cares.vcxproj -> C:\Dev\J2V8\node\Release\lib\cares.lib
  libuv.vcxproj -> C:\Dev\J2V8\node\Release\lib\libuv.lib
[...]
SignTool Error: No certificates were found that met all the given criteria.
Signing Release\node.exe failed using http://tsa.starfieldtech.com
Could not sign Release\node.exe using any available timeserver
Failed to sign exe

Microsoft Windows [Version 6.1.7601]
Updating Maven configuration (./docker/shared/pom.xml)...
SHELL building win32@x64 => j2v8cmake
-- The C compiler identification is MSVC 19.0.24210.0
-- The CXX compiler identification is MSVC 19.0.24210.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio
14.0/VC/bin/amd64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio
14.0/VC/bin/amd64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studi
o 14.0/VC/bin/amd64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studi
o 14.0/VC/bin/amd64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Java version 1.8.0.144 found!
Using Java-Root: C:\Program Files\Java\jdk1.8.0_144
--------------------------------------------------
J2V8_LIB_ARCH_NAME     = x86_64
J2V8_LIB_VENDOR_NAME   =
J2V8_LIB_PLATFORM_NAME = windows
J2V8_TARGET_ARCH       = x86_64
J2V8_BUILD_X64         = TRUE
--------------------------------------------------
J2V8_NODE_ENABLED      = TRUE
--------------------------------------------------
Linking against static MSVCRT
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Dev/J2V8/cmake.out/win32.x64

Microsoft Windows [Version 6.1.7601]
Updating Maven configuration (./docker/shared/pom.xml)...
SHELL building win32@x64 => j2v8jni
WARNING: Could not find V8.class file at path: ./target/classes/com/eclipsesourc
e/v8/V8.class
JNI Header generation will be skipped...

Microsoft Windows [Version 6.1.7601]
Updating Maven configuration (./docker/shared/pom.xml)...
SHELL building win32@x64 => j2v8cpp
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

Building the projects in this solution one at a time. To enable parallel build,
please add the "/m" switch.
Build started 11/14/2017 1:27:14 PM.
Project "C:\Dev\J2V8\cmake.out\win32.x64\j2v8.sln" on node 1 (default targets).
C:\Dev\J2V8\cmake.out\win32.x64\j2v8.sln.metaproj : error MSB4126: The specifie
d solution configuration "Release|X86" is invalid. Please specify a valid solut
ion configuration using the Configuration and Platform properties (e.g. MSBuild
.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those
properties blank to use the default solution configuration. [C:\Dev\J2V8\cmake.
out\win32.x64\j2v8.sln]
Done Building Project "C:\Dev\J2V8\cmake.out\win32.x64\j2v8.sln" (default targe
ts) -- FAILED.


Build FAILED.

"C:\Dev\J2V8\cmake.out\win32.x64\j2v8.sln" (default target) (1) ->
(ValidateSolutionConfiguration target) ->
  C:\Dev\J2V8\cmake.out\win32.x64\j2v8.sln.metaproj : error MSB4126: The specif
ied solution configuration "Release|X86" is invalid. Please specify a valid sol
ution configuration using the Configuration and Platform properties (e.g. MSBui
ld.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave thos
e properties blank to use the default solution configuration. [C:\Dev\J2V8\cmak
e.out\win32.x64\j2v8.sln]

    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.07
Traceback (most recent call last):
  File "build.py", line 13, in <module>
    interactive.run_interactive_cli()
  File "C:\Dev\J2V8\build_system\build_interactive.py", line 58, in run_interact
ive_cli
    bex.execute_build(build_params)
  File "C:\Dev\J2V8\build_system\build_executor.py", line 306, in execute_build
    execute_build_step(target_compiler, target_step)
  File "C:\Dev\J2V8\build_system\build_executor.py", line 222, in execute_build_
step
    build_system.build(build_step)
  File "C:\Dev\J2V8\build_system\build_structures.py", line 83, in build
    self.exec_build(config)
  File "C:\Dev\J2V8\build_system\shell_build.py", line 27, in exec_build
    self.exec_cmd(shell_str, config)
  File "C:\Dev\J2V8\build_system\build_structures.py", line 96, in exec_cmd
    self.__exec_cmd_core(cmd, config, config.build_cwd)
  File "C:\Dev\J2V8\build_system\build_structures.py", line 105, in __exec_cmd_c
ore
    utils.execute(cmd, cwd)
  File "C:\Dev\J2V8\build_system\build_utils.py", line 157, in execute
    raise subprocess.CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command 'cd C:/Dev/J2V8 && cd ./cmake.out/win32.x
64/ && msbuild j2v8.sln /property:Configuration=Release' returned non-zero exit
status 1
C:\Dev\J2V8>

**Comment by hurol02** [comment]
I apologize for the format of previous message.  Should have put that log extract in an attachment to avoid markdown parser breakdown...

Another question:  Is there any way to direct J2V8 to use an external install of NodeJS rather than the embedded one (which may not be adequately versioned to run the user program, as in my use case)?

Thanks,

  -- OHM.

**Comment by SJava1** [comment]
@irbull would appreciate your help with this issue very much. We are kind of stuck unable to build on windows and if a build for Windows 64 bit is made available for 4.8.0 that will will be very helpful for us.

**Comment by matiwinnetou** [comment]
I never needed windows build so I cannot help but when you are building make sure to build master. 4.8.0 has serious bugs at least were visible for my use case: ReactJS on the JVM -> https://suchen.mobile.de/fahrzeuge/einfache-suche

**Comment by hurol02** [comment]
@matiwinnetou - Danke für Ihren Rat!

**Comment by irbull** [comment]
Proper support for platforms other than Android hasn't really existed, so in the interest of setting honest expectations, I'm reducing the scope of this project to V8 on Android. See #441 for more information. If someone would like to build/maintain windows binaries, I'd be happy, but I don't have the cycles to do that. I'm closing this as out of scope.
