### ISSUE TITLE
Provide Eclipse Update site for J2V8

### ISSUE THREAD

**Issue by angelozerr** [eclipsesource/J2V8#36]
It should be very good if you could provide an update site for J2V8 which install the well J2V8 plugins according the OS. 

tern.java provides this feature for node.js install. See https://github.com/angelozerr/tern.java/tree/master/eclipse/embed

It install the well node.js according the OS by using `Eclipse-PlatformFilter`. See https://github.com/angelozerr/tern.java/blob/master/eclipse/embed/tern.eclipse.ide.server.nodejs.embed.win32.win32.x86_64/META-INF/MANIFEST.MF#L12

See https://github.com/angelozerr/tern.java/blob/master/thirdparties/j2v8/j2v8_win32_x86_64/META-INF/MANIFEST.MF#L12 for my custom J2V8

**Comment by irbull** [comment]
J2V8 3.1 (3.1.6 since it took me a few tries to get the build working properly) are now available in a p2 site at http://github.eclipsesource.com/j2v8-osgi/
