### ISSUE TITLE
`V8.release()` not clear `functionRegistry` which may cause memory leak

### ISSUE THREAD

**Issue by jan4984** [eclipsesource/J2V8#363]
https://github.com/eclipsesource/J2V8/blob/0e83e34d1ce77245473f41c2e43260829f652a6d/src/main/java/com/eclipsesource/v8/V8.java#L383-L388

after v8 runtime release, the `MethodDescriptor` reference still in the `functionRegistry` hash map.

**Comment by kokog78** [comment]
This is just an opinion. I think that after release, you will not use the V8 instance anymore, so the garbage collector will collect it after a while - with the non-empty HashMap too. So maybe this is not a big problem, the native method descriptors are released.

**Comment by jan4984** [comment]
seems good
