### ISSUE TITLE
android aar is too big and old

### ISSUE THREAD

**Issue by oakpip** [eclipsesource/J2V8#365]
The version currently being used on Android is as follows:  api 'com.eclipsesource.j2v8:j2v8_android:3.0.5@aar'
       
 Is there any newest version for Android only, I need to control the size of the apk, just to support android's latest and smallest aar.

                                                                                                                                                  please help me

**Comment by AlexTrotsenko** [comment]
I don't know if I am doing it right, but latest version from maven works fine for me:

```
compile 'com.eclipsesource.j2v8:j2v8:4.8.0@aar'
```

**Comment by AlexTrotsenko** [comment]
On the other had mac os version is a bit old - 4.6.0 - I don't see any reason why it's [not updated](https://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.eclipsesource.j2v8%22%20AND%20a%3A%22j2v8_macosx_x86_64%22).

**Comment by irbull** [comment]
At one point the artifact name did change. 4.8.0 is available as `com.eclipsesource.j2v8:j2v8:4.8.0@aar`.

I am reducing the scope of this project and I'll only be producing Android (`aar`) builds. If others have cycles and would like to build/maintain other platforms, please let me know. Please see #441 for more information. Sorry, but I just don't have the cycles to build/test/maintain all these different platforms.
