### ISSUE TITLE
Problom with "nodejs git clone"

### ISSUE THREAD

**Issue by lsmobile** [eclipsesource/J2V8#366]
Hello, connoisseurs!

When I try to execute the `nodejs git clone` command, the system gives an error:

 ```
 File "nodejs.py", line 51
    print "[flush-cache]"
                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "[flush-cache]")?
```

What can be done? Thank you in advance!

**Comment by SJava1** [comment]
I saw that with Python version 3.6. x.  as there are syntax differences.  I believe this issue is not seen with Python 2.7.x.

**Comment by lsmobile** [comment]
Thank you @SJava1. It worked!
