### ISSUE TITLE
ndk error(j2v8 version:3.0.2)

### ISSUE THREAD

**Issue by fifiand1** [eclipsesource/J2V8#368]
When I was testing my APP, I got this:

11-30 15:03:25.855 F/DEBUG (13831): Build fingerprint: 'HONOR/PRA-AL00/HWPRA-H:7.0/HONORPRA-AL00/C00B190:user/release-keys'
11-30 15:03:25.855 F/DEBUG (13831): Revision: '0'
11-30 15:03:25.855 F/DEBUG (13831): ABI: 'arm'
11-30 15:03:25.855 F/DEBUG (13831): pid: 10757, tid: 10757, name: om.sunline.cimb >>> com.sunline.cimb <<<
11-30 15:03:25.855 F/DEBUG (13831): r0 00000000 r1 00002a05 r2 00000006 r3 00000008
11-30 15:03:25.855 F/DEBUG (13831): r4 ec7a258c r5 00000006 r6 ec7a2534 r7 0000010c
11-30 15:03:25.855 F/DEBUG (13831): r8 ffa59888 r9 ffa59884 sl ffa59c38 fp ffa59878
11-30 15:03:25.855 F/DEBUG (13831): ip 0000000c sp ffa597c0 lr ebf43e17 pc ebf46680 cpsr 600f0010
11-30 15:03:25.864 F/DEBUG (13831):
11-30 15:03:25.864 F/DEBUG (13831): backtrace:
11-30 15:03:25.865 F/DEBUG (13831): #00 pc 0004a680 /system/lib/libc.so (tgkill+12)
11-30 15:03:25.865 F/DEBUG (13831): #01 pc 00047e13 /system/lib/libc.so (pthread_kill+34)
11-30 15:03:25.865 F/DEBUG (13831): #02 pc 0001d8b5 /system/lib/libc.so (raise+10)
11-30 15:03:25.865 F/DEBUG (13831): #03 pc 00019401 /system/lib/libc.so (__libc_android_abort+34)
11-30 15:03:25.865 F/DEBUG (13831): #04 pc 000170e4 /system/lib/libc.so (abort+4)
11-30 15:03:25.865 F/DEBUG (13831): #05 pc 00457b04 /data/app/com.sunline.cimb-1/lib/arm/libj2v8.so (_ZN2v88internal2OS5AbortEv+24)
11-30 15:03:25.865 F/DEBUG (13831): #06 pc 001c5908 /data/app/com.sunline.cimb-1/lib/arm/libj2v8.so (_ZN2v85Utils16ReportApiFailureEPKcS2_+96)
11-30 15:03:25.865 F/DEBUG (13831): #07 pc 001c5aec /data/app/com.sunline.cimb-1/lib/arm/libj2v8.so (_ZN2v88internal2V823FatalProcessOutOfMemoryEPKcb+328)
11-30 15:03:25.865 F/DEBUG (13831): #08 pc 002da17c /data/app/com.sunline.cimb-1/lib/arm/libj2v8.so (_ZN2v88internal7Isolate4InitEPNS0_12DeserializerE+2208)
11-30 15:03:25.865 F/DEBUG (13831): #09 pc 003ddb28 /data/app/com.sunline.cimb-1/lib/arm/libj2v8.so (_ZN2v86Locker10InitializeEPNS_7IsolateE+108)
11-30 15:03:25.865 F/DEBUG (13831): #10 pc 001bcf27 /data/app/com.sunline.cimb-1/lib/arm/libj2v8.so (Java_com_eclipsesource_v8_V8__1createIsolate+78)
11-30 15:03:25.865 F/DEBUG (13831): #11 pc 00a4a3a5 /data/app/com.sunline.cimb-1/oat/arm/base.odex (offset 0xa05000)

**Comment by irbull** [comment]
This is a very old version of J2V8. Please re-open if you see this with newer versions.
