### ISSUE TITLE
OSGify J2V8

### ISSUE THREAD

**Issue by angelozerr** [eclipsesource/J2V8#37]
To consume J2V8 inside Eclipse, it should be very cool if you could OSGify J2V8  by using `Eclipse-PlatformFilter` (see https://github.com/eclipsesource/J2V8/issues/36)

See https://github.com/angelozerr/tern.java/blob/master/thirdparties/j2v8/j2v8_win32_x86_64/META-INF/MANIFEST.MF#L12 for my custom J2V8

**Comment by dgolovin** [comment]
@angelozerr, we have https://github.com/gorkem/j2v8forjsdt to play with j2v8 in eclipse and output of the build for this repository is p2 repository with OSGified j2v8 bundles.

**Comment by angelozerr** [comment]
Thanks @dgolovin for your info. I hope J2V8 will support OSGi and in my case I need to use J2V8 3.0.0 because today I cannot use it because of multi thread problem.

**Comment by angelozerr** [comment]
@irbull I hav eseen that you have spoken about J2V8 & ternjs http://eclipsesource.com/blogs/2015/07/08/j2v8-3-0-released/ that's very cool, thanks!

But today the update site doesn't provide teh capability to install J2V8 because : 

 * I need that J2V8 support OSGi. See https://github.com/eclipsesource/J2V8/issues/37
 * I need update site to install J2V8 according the OS. See https://github.com/eclipsesource/J2V8/issues/36

So I'm waiting for those 2 issues to provide an update site to install J2V8 & ternjs.

Thank's for your help.

**Comment by irbull** [comment]
Yep, I'll get to these. I needed to get the release out so we could test
the new functionality. I should be able to update these pretty easy in a
point release now.

On Wed, Jul 8, 2015 at 5:08 AM, Angelo <notifications@github.com> wrote:

> @irbull <https://github.com/irbull> I hav eseen that you have spoken
> about J2V8 & ternjs
> http://eclipsesource.com/blogs/2015/07/08/j2v8-3-0-released/ that's very
> cool, thanks!
>
> But today the update site doesn't provide teh capability to install J2V8
> because :
>
>    - I need that J2V8 support OSGi. See #37
>    <https://github.com/eclipsesource/J2V8/issues/37>
>    - I need update site to install J2V8 according the OS. See #36
>    <https://github.com/eclipsesource/J2V8/issues/36>
>
> So I'm waiting for those 2 issues to provide an update site to install
> J2V8 & ternjs.
>
> Thank's for your help.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipsesource/J2V8/issues/37#issuecomment-119552936>.
>



-- 
R. Ian Bull | EclipseSource Victoria | +1 250 477 7484
http://eclipsesource.com | http://twitter.com/eclipsesource

**Comment by angelozerr** [comment]
@irbull had you time to work on OSGi support? Many thanks for your answer.

**Comment by angelozerr** [comment]
@irbull I know you are very busy, but do you think you will have time to provide OSGi support? Without that, I cannot provide J2V8 as tern server. Thanks for your help.

**Comment by jonek** [comment]
@angelozerr Do you know https://github.com/gorkem/j2v8forjsdt ? Code over there looks OSGi-ish.

**Comment by irbull** [comment]
I'll be in Karlsruhe this coming week. @jonek maybe if you're around and we have a few minutes we can get this done.

**Comment by angelozerr** [comment]
> Do you know https://github.com/gorkem/j2v8forjsdt ? Code over there looks OSGi-ish.

Thanks @jonek for the info, but I would like to use official J2V8 distribution with maven to build an update site with tern.java. More thoses plugins are not updated since 6 months (I'm not sure that it works with tern.java since @irbull had fixed some problems with multi thread).

**Comment by irbull** [comment]
3.1.2 contains OSGi manifests and Eclipse-platformfilters. This applies to win32_x86, win32_x86_64, macosx_x86_64, and linux_x86_64.

I will create a feature and an update site for this release.

**Comment by angelozerr** [comment]
Many thanks @irbull, I will test that.
