### ISSUE TITLE
Plz add libj2v8.so on arm64-v8a mips64 x86_64 abis

### ISSUE THREAD

**Issue by liao123abc** [eclipsesource/J2V8#371]
Day by day, I login github and check up J2V8 when I wake up, cause I really need its support for arm64-v8a mips64 x86_64 abis on Android.
But...
It hurts my feelings.

**Comment by matiwinnetou** [comment]
I think the maintainer of the project (@irbull) doesn't have much time these days. Your best chance is to actually do it yourself open PR and hope he merges it at some point.

**Comment by AlexTrotsenko** [comment]
I see, that there is PR, but it's nor merged. May be could be useful for somebody to use it as it is or refine and finish it:

**Comment by AlexTrotsenko** [comment]
https://github.com/eclipsesource/J2V8/pull/380

**Comment by irbull** [comment]
I have added both Arm64 and x86_64 for Android. See #384 and (23e370664b616aa30fd691eb1c0958c60a68a7e5). I will be pushing out an `aar` with these platforms later this week. Closing this bug since most of the work happened in #384.

**Comment by ltasquier** [comment]
Hi all, is it possible to have a precompiled `libj2v8.so` version for arm64-v8a and x86_64? Thanks in advance
