### ISSUE TITLE
Exception in thread "Thread-0" undefined:0: TypeError: undefined is not a function TypeError: undefined is not a function com.eclipsesource.v8.V8ScriptExecutionException

### ISSUE THREAD

**Issue by exellian** [eclipsesource/J2V8#373]
If I try to execute a function in my script.js, I always get this ERROR:
Exception in thread "Thread-0" undefined:0: TypeError: undefined is not a function
TypeError: undefined is not a function
com.eclipsesource.v8.V8ScriptExecutionException
I definetly defined my function!
Ho can I execute Functions in node js scripts?

**Comment by nameyangchunhe** [comment]
https://stackoverflow.com/questions/38848274/execute-function-from-js-with-j2v8
