### ISSUE TITLE
java.lang.UnsatisfiedLinkError: com.eclipsesource.v8.V8._acquireLock(J)V

### ISSUE THREAD

**Issue by songshuzhong** [eclipsesource/J2V8#376]
where dose this error come from, how could i fix it?please help.
--------------------------------------------------------------------
java.lang.UnsatisfiedLinkError: com.eclipsesource.v8.V8._acquireLock(J)V
	com.eclipsesource.v8.V8._acquireLock(Native Method)
	com.eclipsesource.v8.V8.acquireLock(V8.java:1029)
	com.eclipsesource.v8.V8Locker.acquire(V8Locker.java:50)
	com.eclipsesource.v8.V8Locker.<init>(V8Locker.java:27)
	com.eclipsesource.v8.V8.<init>(V8.java:270)
	com.eclipsesource.v8.V8.createV8Runtime(V8.java:158)
	com.eclipsesource.v8.V8.createV8Runtime(V8.java:114)
	com.bonc.epm.ui.spring.j2v8.J2V8ReactTemplateView.createRuntime(J2V8ReactTemplateView.java:33)
	com.bonc.epm.ui.spring.j2v8.J2V8ReactTemplateView.renderMergedOutputModel(J2V8ReactTemplateView.java:92)
	org.springframework.web.servlet.view.AbstractView.render(AbstractView.java:303)
	org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1282)
	org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1037)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:980)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:101)
	org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:108)
	org.springframework.boot.web.support.ErrorPageFilter.forwardToErrorPage(ErrorPageFilter.java:183)
	org.springframework.boot.web.support.ErrorPageFilter.handleException(ErrorPageFilter.java:166)
	org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:130)
	org.springframework.boot.web.support.ErrorPageFilter.access$000(ErrorPageFilter.java:59)
	org.springframework.boot.web.support.ErrorPageFilter$1.doFilterInternal(ErrorPageFilter.java:90)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.springframework.boot.web.support.ErrorPageFilter.doFilter(ErrorPageFilter.java:108)

**Comment by wilsonrf** [comment]
Hi,
I was having the same issue.
Because I was coding on two different operating systems (OSX and Linux), I had both linux and OSX dependencies on my build.gradle like this:

`
compile('com.eclipsesource.j2v8:j2v8_linux_x86_64:4.+')
compile('com.eclipsesource.j2v8:j2v8_macosx_x86_64:4.+')
`

To solve the problem I commented the linux dependency (when coding on OSX), and OSX dependency when coding on linux.
e.g.

`
//compile('com.eclipsesource.j2v8:j2v8_linux_x86_64:4.+')
compile('com.eclipsesource.j2v8:j2v8_macosx_x86_64:4.+')
`

Best Regards,

Wilson

**Comment by irbull** [comment]
Closing as it appears to be a setup problem.
