### ISSUE TITLE
Docker build breacks after docker upgrade.

### ISSUE THREAD

**Issue by hsaginor** [eclipsesource/J2V8#378]
After recent upgrade of docker to version "Docker version 17.12.0-ce, build c97c6d6" docker build breaks with a message "Unable to determine docker server platform from version string".

Changing regular expression in the following line in function health_check of docker_build.py
version_match = re.search(r"^ OS/Arch:\s+(.*)$", server_match.group(1), re.MULTILINE)
to "OS/Arch:\s+(.*)$" fixes this.

**Comment by andosw** [comment]
backslash instead of pipe --> `"OS/Arch:\s+(.)$"`

**Comment by irbull** [comment]
This has been fixed as part of our build refactoring. Thanks!
