### ISSUE TITLE
building from source error

### ISSUE THREAD

**Issue by hhiZhous** [eclipsesource/J2V8#387]
Hello.I am building from source in windows and an error occur:

D:\GitHub\J2V8>nodejs.py diff apply
[apply-diff]
Applying Node.js patch: node.patches\7.4.0.diff
error: patch failed: common.gypi:183
error: common.gypi: patch does not apply
error: patch failed: deps/cares/common.gypi:80
error: deps/cares/common.gypi: patch does not apply
error: patch failed: deps/uv/common.gypi:87
error: deps/uv/common.gypi: patch does not apply
error: patch failed: src/node.h:414
error: src/node.h: patch does not apply
Traceback (most recent call last):
  File "D:\GitHub\J2V8\nodejs.py", line 332, in <module>
    cmd_handler.function(sys.argv[3:])
  File "D:\GitHub\J2V8\nodejs.py", line 272, in apply_diff
    utils.execute("git apply " + os.path.join("..", patch_file), "node")
  File "D:\GitHub\J2V8\build_system\build_utils.py", line 157, in execute
    raise subprocess.CalledProcessError(return_code, cmd)
subprocess.CalledProcessError: Command 'git apply ..\node.patches\7.4.0.diff' returned non-zero exit status 1

What can I do please.

**Comment by SCLeoX** [comment]
Same issue

**Comment by matiwinnetou** [comment]
seems like you don't have git installed

**Comment by ddoumeche** [comment]
using the patch shipped with git worked for me

"c:\program files\git\usr\bin\patch" -p1 < ..\node.patches\8.10.1.dif
(Stripping trailing CRs from patch; use --binary to disable.)
patching file common.gypi
(Stripping trailing CRs from patch; use --binary to disable.)
patching file deps/cares/common.gypi
(Stripping trailing CRs from patch; use --binary to disable.)
patching file deps/uv/common.gypi
Hunk #1 succeeded at 87 (offset -6 lines).
(Stripping trailing CRs from patch; use --binary to disable.)
patching file src/node.h

**Comment by irbull** [comment]
Builds are working again. The only officially supported build is building for Android on Linux using Docker. Other builds may work (I use MacOS with Docker).
