### ISSUE TITLE
Create a build without Node

### ISSUE THREAD

**Issue by ewized** [eclipsesource/J2V8#390]
I'm currently trying to create the `.so` file with the latest version of the V8 engine but I don't need any of the Node stuff in the build. There used to be some build instructions to do that but with the addition of the python stuff I can't seem to find it anymore.

Is there a specific command to build the j2v8 with only the V8 engine with a specific version.

**Comment by ewized** [comment]
@drywolf I know you did the build system any simple idea to do this

**Comment by matiwinnetou** [comment]
I was even thinking of forking the project to do exactly that but never had time and enough desire to complete this.

**Comment by drywolf** [comment]
If you only want to build against V8, iirc you can just leave out the `--node-enabled` flag.

**Comment by ewized** [comment]
@drywolf How would I select which version of V8 for it to use? I tried to run the command to see what happens but the build script was saying it could not find node.

**Comment by drywolf** [comment]
The node version is defined in [build_settings.py](https://github.com/eclipsesource/J2V8/blob/master/build_system/build_settings.py)

**Comment by ewized** [comment]
Anyway to build without messing with node at all? Just have the JNI compile only against V8.

**Comment by drywolf** [comment]
IIRC not out of the box ... however, if you provide the necessary V8 binaries and headers in the same locations as the Node build would place them, then it might work just fine.

**Comment by hc-codersatlas** [comment]
Looking for the same thing. Might end up having to do a fork. How hard is it to remove all the node integration? That and there hasn't been a new release for a while.

**Comment by matiwinnetou** [comment]
IMHO this could be a good idea a fork without Node, in many cases this is what somebody may want, just V8...

**Comment by ewized** [comment]
@matiwinnetou I'm actually planing on doing that, just spending time looking in to the JNI and the way V8 works under the hood as the latest V8 release changes a few things. Also was thinking of modeling it like ReactNative where you register modules.

**Comment by crahda** [comment]
@matiwinnetou @ewized @hc-codersatlas We've actually been looking at doing just this over at the V8-Adapter project: https://github.com/alicorn-systems/v8-adapter/issues/17

**Comment by windrunner414** [comment]
@ewized I have successfully built the j2v8 without nodejs and use v8 6.7,it's not difficult,you need modify Android.mk and jni

**Comment by matiwinnetou** [comment]
@windrunner414 can you please share your changes in a fork? Can you see if it would build for other platforms such as linux, osx?

**Comment by irbull** [comment]
Both the latest version of the 5.0 and 4.8 streams are built without any node support. 

In gradle:
`implementation 'com.eclipsesource.j2v8:j2v8:5.0.103@aar'`
`implementation 'com.eclipsesource.j2v8:j2v8:4.8.4@aar'`

or in a maven pom

```
<dependency>
  <groupId>com.eclipsesource.j2v8</groupId>
  <artifactId>j2v8</artifactId>
  <version>4.8.4</version>
  <type>aar</type>
</dependency>
```
or
```
<dependency>
  <groupId>com.eclipsesource.j2v8</groupId>
  <artifactId>j2v8</artifactId>
  <version>5.0.103</version>
  <type>aar</type>
</dependency>
```
The built uses Node to produce the output only because building node was pretty easy. It bulit node, but only linked against the V8 libraries.

Closing this because we now have a Build (4.8.4 and 5.0.103) without node.
