### ISSUE TITLE
java.lang.UnsupportedOperationException: StartNodeJS Not Supported.

### ISSUE THREAD

**Issue by adonnini** [eclipsesource/J2V8#392]
Hi,

When running node.js in my Android app via J2V8, I am getting the following error:

java.lang.UnsupportedOperationException: StartNodeJS Not Supported.

Would you be able to produce an updated aar with 

with 
-D NODE_COMPATIBLE=1 
option?

Thanks,

Alex Donnini

**Comment by DenBond7** [comment]
Please see #216

**Comment by irbull** [comment]
We are reducing the scope of this project to better server JS on Android (see #441) and better set honest expectations. However, Node will not be supported (it never worked on Android), but V8 on Android with J2V8 has been pretty stable for our use cases. I'm closing this as out-of-scope.

**Comment by adonnini** [comment]
Hi Ian,

Thank you very much for your response.

What you say and plan on doing makes perfect sense.

Actually, this is good news for me, I think.

Now, I need to figure out how to run a JS driver (Bigchaindb) in my Android app 
written in Java using J2V8.

Do you think I should be able to do this?

Thanks,

Alex Donnini

Ian Bull wrote:

**Comment by irbull** [comment]
I don't know what Bigchaindb is, but as long as you can get all your dependencies loaded, this should be possible. We've run some pretty big JS apps on J2V8 without problems. But if they rely on the Node.js APIs, this won't work (unless you can provide shims for them).

**Comment by adonnini** [comment]
Thanks Ian. I'll start working on this. I hope you won't mind if I ask questions 
as I go along (via GitHub).

Thanks,

Alex

Ian Bull wrote:
