### ISSUE TITLE
How to reference multi module script 

### ISSUE THREAD

**Issue by adonnini** [eclipsesource/J2V8#393]
Hi,

I have a js script composed of a number of modules. Currently it is packaged for web applications.

This means that if I try to use it via executeScript, the app crashes as the file is just one huge string which Android tries to execute..

How can I execute a multi-module script from J2V8?

The multi-module script I am referring to is https://github.com/bigchaindb/js-bigchaindb-driver

Thanks for your help.

Alex Donnini

**Comment by ewized** [comment]
Not possible right now since the current version of node does not support
that in j2v8

**Comment by adonnini** [comment]
Thanks. I think I can work around that. However, I am having the following problem with executeScript.

1) I define the following string
		String INDEX_SCRIPT = "export Ed25519Keypair from './Ed25519Keypair';\n"
				+ " export Connection from './connection';\n"
				+ "export Transaction from './transaction';\n"
				+ "export ccJsonLoad from './utils/ccJsonLoad';\n"
				+ "export ccJsonify from './utils/ccJsonify';\n";

2) I upload it successfully using the following:

		try {
			File script = createTemporaryScriptFile(INDEX_SCRIPT, "indexScript.js");
		} catch (IOException e6) {
			// TODO Auto-generated catch block
			e6.printStackTrace();
		}

private static File createTemporaryScriptFile(final String script, final String name) throws IOException {
	File tempScriptFile = new File("/sdcard/bigchaindbdriver-js/", name);
	tempScriptFile.createNewFile();
	PrintWriter writer = new PrintWriter(tempScriptFile, "UTF-8");
	try {
		writer.print(script);
	} finally {
		writer.close();
	}
	return tempScriptFile;
	
}

Everything works as expected so far.

When I try

		try {
			File script = createTemporaryScriptFile(INDEX_SCRIPT, "indexScript.js");
		} catch (IOException e6) {
			// TODO Auto-generated catch block
			e6.printStackTrace();
		}

the app crashes with the following error:

04-11 16:41:43.180: D/AndroidRuntime(13117): Shutting down VM
04-11 16:41:43.182: E/AndroidRuntime(13117): FATAL EXCEPTION: main
04-11 16:41:43.182: E/AndroidRuntime(13117): Process: com.android.commmanager, PID: 13117
04-11 16:41:43.182: E/AndroidRuntime(13117): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.commmanager/com.android.commmanager.ApLocationCowPaths}: undefined:1: SyntaxError: Unexpected token export
04-11 16:41:43.182: E/AndroidRuntime(13117): export Ed25519Keypair from './Ed25519Keypair';
04-11 16:41:43.182: E/AndroidRuntime(13117): ^^^^^^
04-11 16:41:43.182: E/AndroidRuntime(13117): com.eclipsesource.v8.V8ScriptCompilationException
04-11 16:41:43.182: E/AndroidRuntime(13117): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2826)
04-11 16:41:43.182: E/AndroidRuntime(13117): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2904)
04-11 16:41:43.182: E/AndroidRuntime(13117): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
04-11 16:41:43.182: E/AndroidRuntime(13117): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1596)
04-11 16:41:43.182: E/AndroidRuntime(13117): 	at android.os.Handler.dispatchMessage(Handler.java:105)
04-11 16:41:43.182: E/AndroidRuntime(13117): 	at android.os.Looper.loop(Looper.java:164)
04-11 16:41:43.182: E/AndroidRuntime(13117): 	at android.app.ActivityThread.main(ActivityThread.java:6600)
04-11 16:41:43.182: E/AndroidRuntime(13117): 	at java.lang.reflect.Method.invoke(Native Method)
04-11 16:41:43.182: E/AndroidRuntime(13117): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
04-11 16:41:43.182: E/AndroidRuntime(13117): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:772)
04-11 16:41:43.182: E/AndroidRuntime(13117): Caused by: undefined:1: SyntaxError: Unexpected token export
04-11 16:41:43.182: E/AndroidRuntime(13117): export Ed25519Keypair from './Ed25519Keypair';
04-11 16:41:43.182: E/AndroidRuntime(13117): ^^^^^^
04-11 16:41:43.182: E/AndroidRuntime(13117): com.eclipsesource.v8.V8ScriptCompilationException
04-11 16:41:43.182: E/AndroidRuntime(13117): 	at com.eclipsesource.v8.V8._executeScript(Native Method)
04-11 16:41:43.182: E/AndroidRuntime(13117): 	at com.eclipsesource.v8.V8.executeScript(V8.java:1061)
04-11 16:41:43.182: E/AndroidRuntime(13117): 	at com.eclipsesource.v8.V8.executeScript(V8.java:668)
04-11 16:41:43.182: E/AndroidRuntime(13117): 	at com.eclipsesource.v8.V8.executeScript(V8.java:651)
04-11 16:41:43.182: E/AndroidRuntime(13117): 	at com.android.commmanager.continuouslocationtrackingservice.UserAndPoiProcessing.<init>(UserAndPoiProcessing.java:922)
04-11 16:41:43.182: E/AndroidRuntime(13117): 	at com.android.commmanager.ApLocationCowPaths.onCreate(ApLocationCowPaths.java:908)
04-11 16:41:43.182: E/AndroidRuntime(13117): 	at android.app.Activity.performCreate(Activity.java:6975)
04-11 16:41:43.182: E/AndroidRuntime(13117): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
04-11 16:41:43.182: E/AndroidRuntime(13117): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2779)
04-11 16:41:43.182: E/AndroidRuntime(13117): 	... 9 more

What am I doing wrong?

Thanks,

Alex Donnini
