### ISSUE TITLE
Building from source code error! 

### ISSUE THREAD

**Issue by yorsen** [eclipsesource/J2V8#400]
/usr/bin/ld: /home/admin/windows2/J2V8/node/out/Release/obj.target/cares/deps/cares/src/ares__close_sockets.o: relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/admin/windows2/J2V8/node/out/Release/obj.target/cares/deps/cares/src/ares_create_query.o: relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/admin/windows2/J2V8/node/out/Release/obj.target/cares/deps/cares/src/ares_destroy.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/admin/windows2/J2V8/node/out/Release/obj.target/cares/deps/cares/src/ares_expand_name.o: relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/admin/windows2/J2V8/node/out/Release/obj.target/cares/deps/cares/src/ares_expand_string.o: relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /home/admin/windows2/J2V8/node/out/Release/obj.target/cares/deps/cares/src/ares_free_string.o: relocation R_X86_64_32 against `.text' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[2]: *** [libj2v8-linux-x86_64.so] Error 1
make[1]: *** [CMakeFiles/j2v8.dir/all] Error 2
make: *** [all] Error 2

what can I do please?

environment:
gcc          4.9.2
cmake     3.6.0
gmake     3.81
libstdc++
 GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBC_2.3
GLIBC_2.2.5
GLIBC_2.3.2
GLIBCXX_FORCE_NEW
GLIBCXX_DEBUG_MESSAGE_LENGTH

**Comment by irbull** [comment]
Builds appear to be working again. We only officially support Android builds on Linux using Docker. Other builds are known to work (for example I use MacOS without a problem).
