### ISSUE TITLE
we need newer version of v8 in j2v8!

### ISSUE THREAD

**Issue by pboymt** [eclipsesource/J2V8#403]
async/await was supported in V8 5.5. It's very useful!

**Comment by gosp** [comment]
you can build j2v8(nodejs 8.2.1) by yourselves.
please visit: https://github.com/matiwinnetou/J2V8/tree/nodejs8

**Comment by matiwinnetou** [comment]
https://transfer.sh/7O5dh/j2v8_macos_x86_64-nodejs-8.2.1-SNAPSHOT.jar
https://transfer.sh/Y0ZTi/j2v8_linux_x86_64-nodejs-8-2-1-SNAPSHOT.jar

**Comment by pboymt** [comment]
@matiwinnetou Could I compile it for Android?

**Comment by matiwinnetou** [comment]
@pboymt probably you could but I did not try, didn't need it back then.

**Comment by gengjiawen** [comment]
@matiwinnetou Any plan to bump nodejs version to 8.11.1 ?

**Comment by sgopi93** [comment]
@pboymt @irbull http://hn.premii.com/#/article/17648139 please refer this. The new V8 engine got lot faster.

**Comment by irbull** [comment]
This bug and similar ones like it have been opened many times. I'm going to track this in #433. Closing this as a duplicate so we can track this in one spot.
