### ISSUE TITLE
Java setTimeout

### ISSUE THREAD

**Issue by tanpuer** [eclipsesource/J2V8#406]
v8.registerJavaMethod(new JavaVoidCallback() {
            @Override
            public void invoke(final V8Object receiver, final V8Array parameters) {
                           if (parameters.length() == 2){
                    final Object timeout =  parameters.get(1);
                    final Object callback =  parameters.get(0);
                    if (!(timeout instanceof Integer) || !(callback instanceof V8Function)){
                        return;
                    }
//                    ((V8Function)callback).call(receiver, null);
                    new Handler().postDelayed(new Runnable() {
                        @Override
                        public void run() {
                            ((V8Function)callback).call(receiver,null);
                        }
                    },(int)timeout);
                }
            }
        },"setTimeout");

if i call the v8Function immediately, it did work. But if i call the function after some time, the V8Function will be released automatically. Can I hold the v8Function and release it later myself?

**Comment by carl1990** [comment]
+1 
face same problem

**Comment by huhuang03** [comment]
Same issue, any idea?

**Comment by Unicellular-SU** [comment]
use v8Function.twin()

**Comment by SamukaDEV** [comment]
how? @Unicellular-SU 

you can explain? or send an example?
