### ISSUE TITLE
Windows 64bit build fails, dll name mismatch naming convention assumed by Java code

### ISSUE THREAD

**Issue by aragozin** [eclipsesource/J2V8#408]
I'm trying to build 64 bit windows version from master branch.

Build generates dll named `libj2v8-windows-x86_64.dll` though it seems that `LibraryLoader.java` expects dll to be named `libj2v8_win32_x86_64.dll`. As a result JUnit tests are failing unable to load native library.

When I have change dll name by hand from `libj2v8-windows-x86_64.dll` -> `libj2v8_win32_x86_64.dll` and rebuild jar, tests have been passed.

**Comment by irbull** [comment]
We are limiting the scope of this project to V8 on Android only. I don't have the cycles to support all the different platforms. See #441 for more information. If someone would like to submit a PR for windows builds (that doesn't break the Android builds), I can apply it, but I won't be providing windows binaries.
