### ISSUE TITLE
Calling a JavaScript function in script

### ISSUE THREAD

**Issue by Anatidae-Project** [eclipsesource/J2V8#41]
I'm sorry for opening an issue on this, but I can't seem to find any documentation on this.

I have a Javascript library that I'd like to keep in memory and run functions on it from time to time. It also might make callbacks to my methods I register. 

I am assuming that I don't release the v8 runtime until I'm done with my libraries. But how do I call "someFunction(args)" in my Javascript code from Java?

Using Rhino, it looks like this:
```java
Context rhino = Context.enter(); // Rhino context
rhino.setOptimizationLevel(-1);

scope = rhino.initStandardObjects();
obj = scope.get("someFunction", scope);
if (obj instanceof Function) {
    Function jsFunction = (Function) obj;
    // Set params
    Object [] params = new Object [] {arg1, arg2};
    // Call the function with params
    Object jsResult = jsFunction.call(rhino, scope, scope, params);
}
```

Hoping to find the J2V8 equivalent. Thank you for the library.

**Comment by irbull** [comment]
You should be able to do something like:
   public void testIntFunction() {
        v8.executeVoidScript("function add(x, y) {return x+y;}");
        V8Array parameters = new V8Array(v8);
        parameters.push(7);
        parameters.push(8);

        int result = v8.executeIntFunction("add", parameters);

        assertEquals(15, result);
        parameters.release();
    }

In this case there is a function "add" in the global scope that takes two parameters and returns a 32bit int.  You can call this by calling v8.executeIntFunction(functionName, parameters). 

I'm working on some docs, but for now the best source of examples is the JUnit tests.
