### ISSUE TITLE
How do I deep copy the runtime data from one V8Object to another?

### ISSUE THREAD

**Issue by nsinghal90** [eclipsesource/J2V8#410]
I am using the eclipsesource J2V8 library to communicate with the Node JS Script. One of the requirements is to catch the exceptions thrown by V8Object's execute*Function methods, log it to our log store and then throw the exception back for the app to handle.

To do that I am overriding the V8Object class' aforementioned methods and in the constructor I am passing the V8Object which had already been created (I can not use my "wrapper" class where the original V8Object object was created). My constructor looks like:

```
public V8ObjectWrapper(V8Object _v8Object)
{
  super(_v8Object.getRuntime());
  super.setPrototype(_v8Object);
}
```

The first line is to give the v8RuntimePointer to my wrapper object and the prototype method call is to copy the prototype of the object to my wrapper object.

All this runs fine. The wrapper object has the right methods and the registered callbacks. The nodeJS object, being represented by this wrapper object, however tends to lose the information stored in the `this` variable. How do I correctly copy the original V8Object so that I have all the information in the wrapper object?

Apologies as this might not really be an issue but a clarification question.

**Comment by irbull** [comment]
I'm not sure you can. I think you'd have to go through all the properties and copy them to the new object.

**Comment by irbull** [comment]
Closing as there isn't anything J2V8 can do to help here.
