### ISSUE TITLE
I don't want to release manually

### ISSUE THREAD

**Issue by Kelvely** [eclipsesource/J2V8#413]
Use a wrapper class and implement `finalize()` might help.

**Comment by irbull** [comment]
Feel free to use a `finalize` method if it works for you. However, the contract for `finalize` gives no guaranteed it will be called. There may be some Java implementations where it is guaranteed, and if that works for you, great! But in the core, we can't rely on that.

I'm looking at adding `AutoCloseable` support. This may help. There is also the `MemoryManager` in the utils package that may help.
