### ISSUE TITLE
Include 64-bit ARM native libraries in Android builds

### ISSUE THREAD

**Issue by JessHolle** [eclipsesource/J2V8#431]
Google is going to start requiring that any new app version on the Play Store that contains native code contains 64-bit native binaries, not just 32-bit ones.

Their deadline is August 2019, but clearly it would be best not to wait until the last minute on this.

**Comment by DenBond7** [comment]
I think it's a duplicate of #384

**Comment by JessHolle** [comment]
Ah, yes, you're 100% correct.
