### ISSUE TITLE
Update dependencies overall

### ISSUE THREAD

**Issue by JessHolle** [eclipsesource/J2V8#433]
Update to latest (stable LTS) versions of all dependencies, including:
- Node
- V8
- Android NDK
- And so on...

**Comment by JessHolle** [comment]
I just managed to build J2V8 (for Android myself), but unfortunately it is beyond me how to move J2V8 forward in this fashion or to add a 64-bit ARM view or pretty much anything on the native side of J2V8.

I guess I'm crazy to expect a top-level build.gradle for Android that directly delegates to CMake and builds 32 and 64-bit ARM binaries -- on any platform with Android Studio without the latest Android NDK and without requiring Docker.

**Comment by irbull** [comment]
I've updated some of these. However, the V8 Debug API has completely changed. So if we updated to a new version of Node/V8 we will have to remove (or rebuild) debug support. 

The debug support wasn't great anyway, so this might be ok. I'm trying to find someone to work on this.

**Comment by irbull** [comment]
From #403, V8 is much faster now: http://hn.premii.com/#/article/17648139

**Comment by irbull** [comment]
Actually, #334 has much more information so I'm going to use as the main issue.

Regarding other things mentioned here, I have updated the NDK version and we have other issues for updating the Java version and Maven version. I think this particular issue can be closed and we can use the other ones to track the work. Thanks!
