### ISSUE TITLE
NoSuchMethodException in registerJavaMethod()

### ISSUE THREAD

**Issue by altuncu** [eclipsesource/J2V8#442]
Actually, I'm not sure if this is a bug of J2V8. I have a Kotlin class in my Android project for console methods as follows:

    import android.util.Log

    interface Console {
        fun error(msg: String)
        fun warn(msg: String)
        fun debug(msg: String)
        fun log(msg: String)
    }

    class LogConsole : Console {
        private val TAG = LogConsole::class.simpleName

        override fun error(msg: String) {
            Log.e(TAG, msg)
        }

        override fun warn(msg: String) {
            Log.w(TAG, msg)
        }

        override fun log(msg: String) {
            Log.i(TAG, msg)
        }

        override fun debug(msg: String) {
            Log.d(TAG, msg)
        }
    }

So, I'm trying to use these methods with `registerJavaMethod()` in another class as follows:

    ...
    private val v8 = V8.createV8Runtime()
    val console = LogConsole()
    val v8Console = V8Object(v8)
    v8.add("console", v8Console)
    v8Console.registerJavaMethod(console, "log", "log", arrayOf<Class<*>>(String::class.java))
    v8Console.registerJavaMethod(console, "error", "error", arrayOf<Class<*>>(String::class.java))
    v8Console.registerJavaMethod(console, "debug", "debug", arrayOf<Class<*>>(String::class.java))
    v8Console.registerJavaMethod(console, "warn", "warn", arrayOf<Class<*>>(String::class.java))
    v8Console.release()
    ...

However, this gives a runtime error like this:

    E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.app1, PID: 17154
    java.lang.IllegalStateException: java.lang.NoSuchMethodException: log [class java.lang.String]
        at com.eclipsesource.v8.V8Object.registerJavaMethod(V8Object.java:637)
        at com.eclipsesource.v8.V8Object.registerJavaMethod(V8Object.java:612)
    ...

Normally, I can access the console methods in the class I'm trying to use `registerJavaMethod()`. But, registering didn't work for me. Am I doing something wrong or is it a bug?

**Comment by JessHolle** [comment]
I'm no Kotlin expert, but I believe you're trying to pass a String[] to a method that expects a String.
