### ISSUE TITLE
Add support for Debug when multiple threads are used

### ISSUE THREAD

**Issue by irbull** [eclipsesource/J2V8#45]
V8 3.26 only supports debugging from a single thread. If we add multi-thread support, we need to address this issue. This blocks issue #33.

**Comment by gorkem** [comment]
I was actually running j2v8 against V8 4.x stream and basically everything but debugging works there. On 4.x debug server implementation is removed. I guess if j2v8 moves to 4.x it either needs to drop debugging or implement the debug server itself. In any case it is an opportunity to solve this problem.

**Comment by irbull** [comment]
You also need to create and manage the 'Platform' on 4.x. I've pushed some
code for this to [1]. As for Debug, I agree. They have completely removed
the debug port and just have the API.

[1] https://github.com/eclipsesource/J2V8/tree/v8_4x

On Wed, Apr 29, 2015 at 1:40 PM, Gorkem Ercan <notifications@github.com>
wrote:

> I was actually running j2v8 against V8 4.x stream and basically everything
> but debugging works there. On 4.x debug server implementation is removed. I
> guess if j2v8 moves to 4.x it either needs to drop debugging or implement
> the debug server itself. In any case it is an opportunity to solve this
> problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipsesource/J2V8/issues/45#issuecomment-97578500>.
>



-- 
R. Ian Bull | EclipseSource Victoria | +1 250 477 7484
http://eclipsesource.com | http://twitter.com/eclipsesource

**Comment by irbull** [comment]
Debug support works again. If we move to 4.x we will need to revisit this.
