### ISSUE TITLE
UnsatisfiedLinkError: Unsupported arch: armv7l

### ISSUE THREAD

**Issue by ancientloregames** [eclipsesource/J2V8#455]
Hi. Recently, I've built the library for the Android with the following parameters: 
```
j2v8 v5.0.100-SNAPSHOT
v8 v5.5
node-js v7.9
Architectures: armeabi-v7a, arm64-v8a, x86_32, x86_64
```
All seems well on the emulator and most of the testing devices. However, there is an issue on some of them. Specifically:
```
Samsung Galaxy Tab3 8.0
LG G2
LENOVO A536
```
All of them are based on **Android 4.4 KitKat**.
Here is the stacktrace:
```
Fatal Exception: java.lang.UnsatisfiedLinkError
Unsupported arch: armv7l
com.eclipsesource.v8.PlatformDetector$Arch.getName (PlatformDetector.java:43)
com.eclipsesource.v8.LibraryLoader.computeLibraryShortName (LibraryLoader.java:42)
com.eclipsesource.v8.V8.checkNativeLibraryLoaded (V8.java:252)
com.eclipsesource.v8.V8.createV8Runtime (V8.java:153)
com.eclipsesource.v8.V8.createV8Runtime (V8.java:114)
```
The method normalizeArch in PlatformDetector doesn't count this arch indeed and I also have found an unittest in the sources, which suppose this crash in PlatformDetectorTest:
```
@Test(expected = UnsatisfiedLinkError.class)
    public void testGetArcharmv7l() {
        System.setProperty("os.arch", "armv7l");

        PlatformDetector.Arch.getName();
}
```
Does this means, that you don't support this architecture? I wasn't able to find much info on armv7l and how it differs to armeabi-v7a.
Also, this error didn't occur on the previous version of the j2v8, witch was v4.8.

**Comment by JessHolle** [comment]
I have not been able to discern how this regression arose, but PlatformDetector seems to be clearly broken.

The "os.arch" result will be armv7* and armv8* for current Android devices, but PlatformDetector then considers those "unknown" and an UnsatisfiedLinkError results.

Yet a quick patch to PlatformDetector to interpret such os.arch results as 32 and 64-bit ARM, respectively results in a working J2V8 library.

**Comment by thomashoef** [comment]
@JessHolle Which "quick patch" did you perform?

**Comment by JessHolle** [comment]
See https://github.com/JessHolle/J2V8/tree/jmh-quick-fixes
