### ISSUE TITLE
ES version

### ISSUE THREAD

**Issue by talhairfanbentley** [eclipsesource/J2V8#457]
what is the ES version that can j2v8 engine can run?
I can run es5 based javascript code easily but cannot run ES2017

@mpost

**Comment by JessHolle** [comment]
J2V8 currently uses a fairly old version of V8.

There are existing issues noting the need/desire for it to use a recent V8 version, thus supporting the latest JS/ES features.

**Comment by ahmadov** [comment]
The newer version of the J2V8 fairly uses a new version of the V8 (see: https://github.com/eclipsesource/J2V8/pull/482 and https://v8.dev/blog/v8-release-74). The new V8 is from the last year and probably supports ES2017.
