### ISSUE TITLE
Building a full android AAR

### ISSUE THREAD

**Issue by artcodex** [eclipsesource/J2V8#458]
Could not find a way to build an Android AAR that includes both x86 and arm. Is there a way with new build system?

**Comment by JessHolle** [comment]
I know @irbull took down a documentation (etc) issue to explain how to do such things.

I didn't care about x86, but I think the same applies as for 32 and 64-bit ARM, i.e. for now:
1. Hack out some build config if it's not present to build for each platform of interest
2. Smash the resulting AARs together into a single "fat" AAR (e.g. by hand)

**Comment by artcodex** [comment]
@JessHolle thanks I was hoping there was something to build full aar, but sounds like it's a good bet for now just to build individual targets and put them together by hand

**Comment by JessHolle** [comment]
So I had built a 32 + 64-bit ARM AAR for Android from latest master, but...

Then I got distracted and didn't test it.

Problem #1: PlatformDetector cannot handle an os.arch value of the form armv8*.  I don't see a recent change here, but something is now causing this to kill things early on.

So after I resolve that, then I get Problem #2:

     Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "uv_default_loop" referenced by "/data/app/com.ptc.vuforiaview-BNCQ7Ds_l4Nf6S2eJ0QrDQ==/lib/arm/libj2v8.so"...

That's for the 32-bit build!  I won't bother chasing 64-bit until the 32-bit works.

**Comment by JessHolle** [comment]
I filed https://github.com/eclipsesource/J2V8/issues/459 on these latest issues.

**Comment by artcodex** [comment]
@JessHolle the dlopen issue is something to do with node support and use of libuv. I didn't need it for my project (I'm just embedding V8) so I turned off the node support.

**Comment by JessHolle** [comment]
Ah... so another hack to turn off node (which I also don't need) and I might be in business?  I'll try that...

**Comment by artcodex** [comment]
@JessHolle Well you should avoid the dlopen issue at least the code using that call is wrapped in defines for the node usage

**Comment by JessHolle** [comment]
Yes, disabling node support gets me a working build -- once I patch PlatformDetector's issues in detecting ARM7 and ARM8 platforms.

**Comment by JessHolle** [comment]
Oh, problem #2 above has already been filed as https://github.com/eclipsesource/J2V8/issues/455

**Comment by irbull** [comment]
Please see the .gitlab-ci.yml file for details on how we build. We build all 4 platforms (arm, arm64, x86, x86_64) without node and keep the artifacts from each build. That way, when they are all done, all 4 platforms are included. I've the library loading issue (#455).

I also have official AARs for both the 5.0 and 4.8 streams:

In gradle:
`implementation 'com.eclipsesource.j2v8:j2v8:5.0.103@aar'`
`implementation 'com.eclipsesource.j2v8:j2v8:4.8.4@aar'`

or in a maven pom
```
<dependency>
  <groupId>com.eclipsesource.j2v8</groupId>
  <artifactId>j2v8</artifactId>
  <version>4.8.4</version>
  <type>aar</type>
</dependency>
```
or
```
<dependency>
  <groupId>com.eclipsesource.j2v8</groupId>
  <artifactId>j2v8</artifactId>
  <version>5.0.103</version>
  <type>aar</type>
</dependency>
```
All those builds contain the binaries for x86, x86_64, arm and arm64. If you call
`v8.getSCMRevision();` in your application, you'll see the commit hash that the artifact was built against. For 4.8.4 it's 8a79c8b and for 5.0.103 it's e6ac51a.

**Comment by hyb1996** [comment]
Same issue to me:
```
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "uv_default_loop" referenced by "/data/app/com.ptc.vuforiaview-BNCQ7Ds_l4Nf6S2eJ0QrDQ==/lib/arm/libj2v8.so"
```
I try to build J2V8 **with Node.js** for android (arm) but all efforts failed.
