### ISSUE TITLE
Issues building J2V8 from latest master

### ISSUE THREAD

**Issue by JessHolle** [eclipsesource/J2V8#459]
So I had built a 32 + 64-bit ARM AAR for Android from latest master (by smashing a 32 and 64-bit AAR together), but...

Then I got distracted and didn't test it.

Problem #1: PlatformDetector cannot handle an os.arch value of the form armv8*. I don't see a recent change here, but something is now causing this to kill things early on.

So after I resolve that, then I get Problem #2:

Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "uv_default_loop" referenced by "/data/app/com.ptc.vuforiaview-BNCQ7Ds_l4Nf6S2eJ0QrDQ==/lib/arm/libj2v8.so"...

That's for the 32-bit binary! I won't bother chasing 64-bit until the 32-bit works.

**Comment by JessHolle** [comment]
As per @artcodex it is clear the uv_default_loop issue can be worked around by disabling node support in the build config.

Problem #1 also occurs for 32-bit ARM, by the way, where os.arch results in armv7* strings.  A trivial patch to PlatformDetector seems to address the issue.

**Comment by JessHolle** [comment]
Oh, problem #1 above has already been filed as https://github.com/eclipsesource/J2V8/issues/455

**Comment by irbull** [comment]
Please see the `.gitlab-ci.yml` file for details on how we build. We build all 4 platforms (arm, arm64, x86, x86_64) without node and keep the artifacts from each build. That way, when they are all done, all 4 platforms are included. I've fixed #455 so that's no longer a problem. Thanks for reporting that!
