### ISSUE TITLE
Support for armv8l

### ISSUE THREAD

**Issue by thomashoef** [eclipsesource/J2V8#463]
Hi,

I have built the aar for J2V8 for all archs (android) and the binary is running fine on e.g. a Samsung Galaxy S8. But on devices like a Samsung A3, I have an exception saying armv8l is not supported. Can we build J2V8 for this architecture?

Thanks
Thomas

**Comment by JessHolle** [comment]
This is https://github.com/eclipsesource/J2V8/issues/455

**Comment by JessHolle** [comment]
See discussion on https://github.com/eclipsesource/J2V8/issues/461

**Comment by irbull** [comment]
Fixed in b844374d8e0f6d1794cef8b29a597f816b276d12

**Comment by thomashoef** [comment]
@irbull thanks for the fix!
