### ISSUE TITLE
Any plan to remove node js dependency and add V8 directly?

### ISSUE THREAD

**Issue by sgopi93** [eclipsesource/J2V8#469]

**Comment by irbull** [comment]
Yes.

A bit of history here. When we first started building V8 was a pain, and it turned out that building Node and taking the V8 bits was easier. I think building V8 is much easier now, and if that's the case, then yes, we will move towards that model.

**Comment by irbull** [comment]
This was a question, so I'll close this issue. There are other issues related to updating the build.
