### ISSUE TITLE
Use V8 inspector protocol for debugging

### ISSUE THREAD

**Issue by ahmadov** [eclipsesource/J2V8#478]
The old `V8` debugger API has been removed from `V8`. It was replaced by the more modern inspector API which is more powerful and makes it easy to interact between `ChromeDevTools (CDT)` and `V8`.

The `CDT` uses a WebSocket to connect to anything that speaks the [V8 inspector protocol](https://v8.dev/docs/inspector). The `J2V8` project itself does not need to implement a WebSocket server. Instead, the Java application that embeds `J2V8` can provide the WebSocket. Therefore, the `J2V8 API` has to be extended.

- relay inspector protocol messages between `CDT` and the `V8` inspector in both directions (incoming and outgoing)
- forwarding events from `V8` inspector to `CDT`

**Comment by irbull** [comment]
This is a completely different API from what we have now, right?

**Comment by ahmadov** [comment]
yes, it's a different API than old `v8-debug`. A new inspector API supports and handles all [ChromeDevTool](https://chromedevtools.github.io/devtools-protocol/tot/) protocol messages for `Debugger`, `Runtime`, `Profile` and other domains.
