### ISSUE TITLE
I want to use the returned java object (ActiveSheet) here. What should I do?? Please Help.

### ISSUE THREAD

**Issue by sahnvn** [eclipsesource/J2V8#480]
I want to use the returned java object (ActiveSheet) here. What should I do?? Please Help.
         
            class ActiveSheet {			
			private V8 engine;
			ActiveSheet(V8 engine) {
				this.engine = engine;
			}
			
			public V8Object getRange() {
				Map<String, Object> rangeObject = new HashMap<String, Object>();
				rangeObject.put("range", new Range());
				return V8ObjectUtils.toV8Object(engine, rangeObject);
			}
		}
		
		class ActiveWorkbook {
			private V8 engine;
			private Map<String, Object> model;
			public ActiveWorkbook(V8 engine) {
				this.engine = engine;
			}
						
			public V8Object getSheet() {
				Map<String, Object> sheet = new HashMap<String, Object>();
				sheet.put("sheet", new ActiveSheet(this.engine));
				return V8ObjectUtils.toV8Object(engine, sheet);
			}
		}
			
		
		V8 engine = V8.createV8Runtime();
		ActiveWorkbook schema = new ActiveWorkbook (engine);
		Method[] methods = schema.getClass().getDeclaredMethods();
		for (Method m : methods) {
			engine.registerJavaMethod(schema, m.getName(), m.getName(), m.getParameterTypes());
		}	
		
		ActiveSheet schema1 = new ActiveSheet (engine);
		Method[] methods1 = schema1.getClass().getDeclaredMethods();
		for (Method m : methods1) {
			engine.registerJavaMethod(schema1, m.getName(), m.getName(), m.getParameterTypes());
		}	
		
		String script = "var sheet = ActiveWorkbook.getSheet(\"Sheet1\");"
				+ "var range = sheet.getRange()";
		engine.executeScript(script);

_Originally posted by @sahnvn in https://github.com/eclipsesource/J2V8/issues/251#issuecomment-539333949_

**Comment by Shujito** [comment]
I too have this issue, @sahnvn did you figure out a way to do so?
