### ISSUE TITLE
Can't use universal J2V8

### ISSUE THREAD

**Issue by Pexien** [eclipsesource/J2V8#490]
I am working on a project which utilizes J2V8, and the project needs to be available on all the main platforms (Windows, Linux, MacOS) for it to be put in to production. J2V8 doesn't work when the dependencies is added to maven using
```
<dependencies>
        <dependency>
            <groupId>com.eclipsesource</groupId>
            <artifactId>j2v8</artifactId>
            <version>5.0.103</version>
        </dependency>
    </dependencies>
```
and only works when adding the dependency of the system architecture it will be running on. (IDE doesn't even recognize `com.eclipsesource.v8` when using above stated dependency)
```
<dependencies>
        <dependency>
            <groupId>com.eclipsesource.j2v8</groupId>
            <artifactId>j2v8_win32_x86_64</artifactId>
            <version>4.6.0</version>
        </dependency>
    </dependencies>
```
This also means that I have to use an older version of J2V8, which lacks some more modern features, which would be nice to have

If anyone has any idea of how to potentially solve this, it would be most welcome, because weather I am doing something wrong, or I am just missing something, I would be thankful for any input. Thank You.

**Comment by Cretezy** [comment]
Hello, did you solve this? I'm currently also experiencing the same issue.
