### ISSUE TITLE
“libplatform/libplatform.h”: No such file or directory

### ISSUE THREAD

**Issue by panxiaoqin** [eclipsesource/J2V8#493]
win10 x64 
nodejs(8、9、12)
jdk 1.8
Python 2.7.16
vs 2019

**Comment by panxiaoqin** [comment]
nodejs tried multiple versions
j2v8 tried master and v8-7.4.288-build branch
Compiling with Developer Command Prompt for VS 2019 fails
I have also used mac and wsl but both are libplatform.h not found

**Comment by panxiaoqin** [comment]
I'm ready to use graalvm.js instead

**Comment by MinePlay96** [comment]
Hello,
i have the same problem, i'm trying to build J2V8 for windows
my goal is to have a version whose node js version is at least 6, 13 would be best :D
i would also take a previously built version.

thanks for the help in advance
