### ISSUE TITLE
May support v8 lite mode?

### ISSUE THREAD

**Issue by liangchenhe55** [eclipsesource/J2V8#494]
My target devices have very low RAM, and I've noticed v8 lite mode may be more suitable for embedded devices.

I'm sorry I don't know enough about V8, is there any way to enable lite mode?

**Comment by Cretezy** [comment]
https://v8.dev/blog/v8-lite

If you read, you see that lite mode was merged into V8 itself. There's no such thing as "lite mode" really

**Comment by ahmadov** [comment]
I haven't tried myself but this should be supported with the latest version (6.0.0) of J2V8, the lite mode has been introduced from V8 7.3 and the latest version of J2V8 uses V8 7.4.288. 

You only need to pass an argument `--lite-mode` to V8 like:
```java
V8.setFlags("--lite-mode");
````

Please let me whether it works or not.

**Comment by liangchenhe55** [comment]
Yes, it's works. Thanks very much.
