### ISSUE TITLE
Maven Update

### ISSUE THREAD

**Issue by gleno** [eclipsesource/J2V8#499]
Is there going to be a Maven update for the throwing functions issue? I would love to give 6 a try, but can't get it to build.

**Comment by ahmadov** [comment]
Hi @gleno , yes, we are planning to release a new version with throwing function fix. Unfortunately, I can not say the time right now, but soon.

**Comment by gleno** [comment]
Thanks. I got it to build from repo anyway, was a weird issue on my end. Cheers.

**Comment by ahmadov** [comment]
The new version 6.1.0 has been published to Maven central.
