### ISSUE TITLE
Add a universal 'get' method

### ISSUE THREAD

**Issue by irbull** [eclipsesource/J2V8#50]
Since we allow executing scripts / functions with unknown return values, we should also add a 'get(key)' that returns an Object.

**Comment by djMax** [comment]
This would definitely help me a bunch too as I have various code gen processes that know what they're going to get, but now are more complex because my get method name and return type have to vary.

**Comment by irbull** [comment]
Checkout the V8ObjectUtils.java, it may help as it has methods that will
convert results to Lists and Maps.

On Tue, May 19, 2015 at 6:45 PM, Max Metral <notifications@github.com>
wrote:

> This would definitely help me a bunch too as I have various code gen
> processes that know what they're going to get, but now are more complex
> because my get method name and return type have to vary.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipsesource/J2V8/issues/50#issuecomment-103717482>.
>



-- 
R. Ian Bull | EclipseSource Victoria | +1 250 477 7484
http://eclipsesource.com | http://twitter.com/eclipsesource

**Comment by irbull** [comment]
Fixed with 8519a6a72278d3dc8f5a1e69489405a28f2fd68c.
