### ISSUE TITLE
As a Nashorn Replacement

### ISSUE THREAD

**Issue by yuvalp-k2view** [eclipsesource/J2V8#508]
This library is pretty amazing and I'm trying to evaluate it as a replacement for nashorn.

In Nashorn we use a callback feature where upon meeting an unknown variable, a callback is called and Java can supply the value.

So our users can write arbitrary variable names and they will be picked out automatically from the application state.

For instance they can write "appState.abc + 5" and   at runtime Nashorn would invoke Java to find out the value of appState. In java we can return a Map and than Nashorn would get ['abc'] out of the map (I get that I will have to copy my Map to a V8Object in any case).

Any leads / ideas on how we can get somehow close to this behaviour with j2v8?

**Comment by yuvalp-k2view** [comment]
That is certainly an option although the js implementor will need to call f(‘someStateObjext’) instead of simply referring to it as an existing variable.

I was looking for a way to make the callback more implicit

On 18 May 2020, at 19:57, Claudio Comandini <notifications@github.com> wrote:

﻿

I am not involved in the J2V8 development but, did you take a look at callbacks?
https://eclipsesource.com/blogs/2015/06/06/registering-java-callbacks-with-j2v8/<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Feclipsesource.com%2Fblogs%2F2015%2F06%2F06%2Fregistering-java-callbacks-with-j2v8%2F&data=02%7C01%7Cyuval.perlov%40k2view.com%7C2a203935f6684fc129ae08d7fb4c8e39%7C994f176e677549549f9e0c719b5e9ca0%7C1%7C0%7C637254178526232726&sdata=fcgJwtvABEt0rE0%2B8x2VaKOdR9%2B9b7YKoIjq%2FgvnW6M%3D&reserved=0>
Seems you are looking for them.

If you wanna some stupid examples I wrote some of them here
https://github.com/ccomandini/j2v8PetPrj<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fccomandini%2Fj2v8PetPrj&data=02%7C01%7Cyuval.perlov%40k2view.com%7C2a203935f6684fc129ae08d7fb4c8e39%7C994f176e677549549f9e0c719b5e9ca0%7C1%7C0%7C637254178526242681&sdata=GKN3scaDGm%2FVsdtfx6YZZxmJz%2BQ5oqVR8532sE450xM%3D&reserved=0>

**Comment by ahmadov** [comment]
@yuvalp-k2view this is not supported natively, because V8 engine throws an error when it hits undefined variable. Although I don't recommend that but you can achieve the same with the following implementation:

```java
V8 v8 = V8.createV8Runtime();
Object result = null;		
Map<String, Object> HM = new HashMap<String, Object>() {
  {
    put("foo", 2);
  }
};

Pattern pattern = Pattern.compile(" ([a-zA-Z_]+[A-Za-z0-9]*).*");
Matcher matcher;

Stack<String> executeScriptStack = new Stack<String>();
executeScriptStack.add("a = b.foo + 5; a");
while (!executeScriptStack.empty()) {
  String scriptToExecute = executeScriptStack.peek();
  executeScriptStack.pop();
  try {
    result = v8.executeScript(scriptToExecute);
    break;
  } catch (V8ScriptExecutionException ex) {
    if (!ex.getJSMessage().startsWith("ReferenceError:")) {
      throw ex;
    }
    matcher = pattern.matcher(ex.getJSMessage());
    if (!matcher.find()) {
      throw ex;
    }
    String variableName = matcher.group(1);
    switch (variableName) {
      case "b":
        V8Object value = V8ObjectUtils.toV8Object(v8, HM);
        v8.add(variableName, value);
        executeScriptStack.add(scriptToExecute);
        break;
      default:
        throw ex;
    }
  }
}

System.out.println("Script result: " + result);
```
This prints `Script result: 7`

**Comment by yuvalp-k2view** [comment]
That's very creative! This approach should run multiple times though, until all variables are resolved, right?

**Comment by ahmadov** [comment]
@yuvalp-k2view  yes that's right
