### ISSUE TITLE
Question about J2V8 version

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/J2V8#515]
Hi, Thanks for your great work
 I have a question I'd like to ask, please.
If I am not mistaken J2V8 6.0 is based on V8 version 7.4.288
dated March 2019.
My question is why such a delay (more than a year) with the current version of V8 (8.3) which dates from May 2020?

**Comment by ahmadov** [comment]
Hi @ishigo1987,
There is a PR for upgrading V8 version: https://github.com/eclipsesource/J2V8/pull/512
It will be released as soon as possible.

**Comment by ishigo1987** [comment]
Thank you very much for your answer @ahmadov
