### ISSUE TITLE
Docker build android jar?

### ISSUE THREAD

**Issue by djMax** [eclipsesource/J2V8#52]
I see the docker build builds the v8 stuff, but could we do similar to build the actual jar? Right now it's not clear how I can just get a jar with the current status of the repo.

**Comment by irbull** [comment]
Yep, it's something I want to do, just haven't got to that yet.

On Tue, May 19, 2015 at 9:40 AM, Max Metral <notifications@github.com>
wrote:

> I see the docker build builds the v8 stuff, but could we do similar to
> build the actual jar? Right now it's not clear how I can just get a jar
> with the current status of the repo.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/eclipsesource/J2V8/issues/52>.
>



-- 
R. Ian Bull | EclipseSource Victoria | +1 250 477 7484
http://eclipsesource.com | http://twitter.com/eclipsesource

**Comment by djMax** [comment]
How does one build after the docker bit anyhow? mvn compile package doesn't seem to do it for android at least.

**Comment by irbull** [comment]
It's possible to build android `aar` files. We need to review our build docs. This is covered in #40. Closing this.
