### ISSUE TITLE
a/libc: fatal signal 5 (sigtrap), code 1 (trap_brkpt), fault addr 0x72833c68c8 in tid 3643 (.tachikoma.demo), pid 3643 (.tachikoma.demo)

### ISSUE THREAD

**Issue by zongxiaomi** [eclipsesource/J2V8#538]
background：
We introduced j2v8, and also referenced the j2v8-debugger library, to debug it, but we will encounter such an error
![image](https://user-images.githubusercontent.com/14845843/106114169-3eaf7780-618a-11eb-8c0b-5c4c4333b112.png)
![image](https://user-images.githubusercontent.com/14845843/106114218-496a0c80-618a-11eb-968f-84bd3b02ab70.png)

It always reports an error after setBreakPointUrl

**Comment by zongxiaomi** [comment]
![image](https://user-images.githubusercontent.com/14845843/106239076-fac97a80-623c-11eb-8c0d-8f810daf434a.png)

**Comment by zongxiaomi** [comment]
it is my error

**Comment by vijayakumar52** [comment]
Did anyone find a solution for this? I'm also facing the same problem.

**Comment by caoccao** [comment]
> Did anyone find a solution for this? I'm also facing the same kind of problem.

Did you get the SIG while your app was closing V8 runtime?
