### ISSUE TITLE
Update to V8 8.9

### ISSUE THREAD

**Issue by ishigo1987** [eclipsesource/J2V8#541]
Hello, i want to know when the J2V8 update to the V8 8.9 version happen

**Comment by newk5** [comment]
For anyone else looking for a Windows/Linux alternative  to J2V8, check out https://github.com/caoccao/Javet it's actively maintained and allows you to embed a full node runtime. It's also up to date to the most recent node/V8 versions.

**Comment by ahmadov** [comment]
This issue can be closed with #559. The latest version of J2V8 uses the V8 version 9.3.345.11
