### ISSUE TITLE
Native crash signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0x74d53ce8c8

### ISSUE THREAD

**Issue by overtherain** [eclipsesource/J2V8#558]
Hi, 
     I get this crash by my app with j2v8, I create a v8 runtime to running a script for a long time, after some minutes later, there is a crash. I can't find the reason, please help me, thanks!
 

05-26 10:20:30.187 26111 26111 I crash_dump64: obtaining output fd from tombstoned
05-26 10:20:30.188   777   777 I /system/bin/tombstoned: received crash request for pid 25430
05-26 10:20:30.189 26111 26111 I crash_dump64: performing dump of process 25430 (target tid = 25532)
05-26 10:20:30.189 26111 26111 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-26 10:20:30.189 26111 26111 F DEBUG   : Build fingerprint: 'HUAWEI/BZT-AL10/HWBZT:8.0.0/HUAWEIBZT-AL10/231(C990):user/release-keys'
05-26 10:20:30.189 26111 26111 F DEBUG   : Revision: '0'
05-26 10:20:30.189 26111 26111 F DEBUG   : ABI: 'arm64'
05-26 10:20:30.189 26111 26111 F DEBUG   : pid: 25430, tid: 25532, name: J2V8RuntimeThre  >>> com.commonrail.mft.decodertest <<<
05-26 10:20:30.189 26111 26111 F DEBUG   : signal 5 (SIGTRAP), code 1 (TRAP_BRKPT), fault addr 0x74d53ce8c8
05-26 10:20:30.189 26111 26111 F DEBUG   :     x0   0000000000000000  x1   0000000000000000  x2   0000000000000000  x3   000000000000000a
05-26 10:20:30.189 26111 26111 F DEBUG   :     x4   00000000000000aa  x5   00000074be4b40a1  x6   000000000000000a  x7   000000000000000a
05-26 10:20:30.189 26111 26111 F DEBUG   :     x8   0000000000000001  x9   0000000000000001  x10  0000000000004001  x11  0000000000000000
05-26 10:20:30.189 26111 26111 F DEBUG   :     x12  0000007506814ef8  x13  0a63373965653535  x14  0000007506815254  x15  0000000000000000
05-26 10:20:30.189 26111 26111 F DEBUG   :     x16  00000074d59d80d0  x17  00000074d53ce8b0  x18  00000074d6193284  x19  00000074d5782dc1
05-26 10:20:30.189 26111 26111 F DEBUG   :     x20  0000000000000000  x21  00000074d57ab2da  x22  0000007506835788  x23  ffffff80ffffffd8
05-26 10:20:30.189 26111 26111 F DEBUG   :     x24  00000074d6193f70  x25  00000074d6193ca0  x26  00000074d6193c70  x27  0000000000000005
05-26 10:20:30.189 26111 26111 F DEBUG   :     x28  0000000000000001  x29  00000074d6193be0  x30  00000074d53cb544
05-26 10:20:30.189 26111 26111 F DEBUG   :     sp   00000074d6193be0  pc   00000074d53ce8c8  pstate 0000000080000000
05-26 10:20:30.199 26111 26111 F DEBUG   : 
05-26 10:20:30.199 26111 26111 F DEBUG   : backtrace:
05-26 10:20:30.199 26111 26111 F DEBUG   :     #00 pc 0000000000a0c8c8  /data/app/com.commonrail.mft.decodertest-WQBCz8RPlEuQBTsVcInyTw==/lib/arm64/libj2v8.so (_ZN2v84base2OS5AbortEv+24)
05-26 10:20:30.199 26111 26111 F DEBUG   :     #01 pc 0000000000a09540  /data/app/com.commonrail.mft.decodertest-WQBCz8RPlEuQBTsVcInyTw==/lib/arm64/libj2v8.so (_Z8V8_FatalPKciS0_z+372)
05-26 10:20:30.199 26111 26111 F DEBUG   :     #02 pc 00000000005cfc28  /data/app/com.commonrail.mft.decodertest-WQBCz8RPlEuQBTsVcInyTw==/lib/arm64/libj2v8.so (_ZN2v88internal13GlobalHandles28InvokeFirstPassWeakCallbacksINS1_4NodeEEEmPNSt6__ndk16vectorINS4_4pairIPT_NS1_22PendingPhantomCallbackEEENS4_9allocatorISA_EEEE+276)
05-26 10:20:30.199 26111 26111 F DEBUG   :     #03 pc 00000000005cfaf0  /data/app/com.commonrail.mft.decodertest-WQBCz8RPlEuQBTsVcInyTw==/lib/arm64/libj2v8.so (_ZN2v88internal13GlobalHandles28InvokeFirstPassWeakCallbacksEv+20)
05-26 10:20:30.199 26111 26111 F DEBUG   :     #04 pc 00000000005ef364  /data/app/com.commonrail.mft.decodertest-WQBCz8RPlEuQBTsVcInyTw==/lib/arm64/libj2v8.so (_ZN2v88internal4Heap24PerformGarbageCollectionENS0_16GarbageCollectorENS_15GCCallbackFlagsE+2344)
05-26 10:20:30.199 26111 26111 F DEBUG   :     #05 pc 00000000005ed924  /data/app/com.commonrail.mft.decodertest-WQBCz8RPlEuQBTsVcInyTw==/lib/arm64/libj2v8.so (_ZN2v88internal4Heap14CollectGarbageENS0_15AllocationSpaceENS0_23GarbageCollectionReasonENS_15GCCallbackFlagsE+1316)
05-26 10:20:30.199 26111 26111 F DEBUG   :     #06 pc 00000000005ec908  /data/app/com.commonrail.mft.decodertest-WQBCz8RPlEuQBTsVcInyTw==/lib/arm64/libj2v8.so (_ZN2v88internal4Heap15HandleGCRequestEv+172)
05-26 10:20:30.199 26111 26111 F DEBUG   :     #07 pc 00000000005b96e8  /data/app/com.commonrail.mft.decodertest-WQBCz8RPlEuQBTsVcInyTw==/lib/arm64/libj2v8.so (_ZN2v88internal10StackGuard16HandleInterruptsEv+184)
05-26 10:20:30.199 26111 26111 F DEBUG   :     #08 pc 0000000000c2c978  /data/app/com.commonrail.mft.decodertest-WQBCz8RPlEuQBTsVcInyTw==/lib/arm64/libj2v8.so (_ZN2v88internal18Runtime_StackGuardEiPmPNS0_7IsolateE+72)
05-26 10:20:30.199 26111 26111 F DEBUG   :     #09 pc 000000000097c230  /data/app/com.commonrail.mft.decodertest-WQBCz8RPlEuQBTsVcInyTw==/lib/arm64/libj2v8.so

**Comment by overtherain** [comment]
I used j2v8 version is v6.1.0

**Comment by ishigo1987** [comment]
try the 6.2.0 version

**Comment by overtherain** [comment]
> try the 6.2.0 version

Thanks, the 6.2.0 version has already fix it
