### ISSUE TITLE
Block-scoped declarations not yet supported outside strict mode

### ISSUE THREAD

**Issue by ThatBlockyPenguin** [eclipsesource/J2V8#563]
I noticed that if I try to use a block-scoped declaration such as `let`, J2V8 throws me this error:
```
Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
```
I find this strange, as V8 itself changed this back in 2016 [(reference)](https://v8.dev/blog/v8-release-49#91%25-ecmascript-2015-(es6)-support)

I find myself wondering what version of V8 J2V8 uses, and whether it's likely to be updated to a more modern version any time soon.

**Comment by ahmadov** [comment]
Hello @ThatBlockyPenguin,

Which version do you refer?

The latest version (v6.2.1) of J2V8 already uses the V8 v9.2 which is released on Aug 9, 2021.

**Comment by ThatBlockyPenguin** [comment]
@ahmadov thank you for your reply,
I'm using version 4.6.0, which might explain it - it's the latest version for Windows 64-bit on maven central. Do I no longer need to specify the platform?

**Comment by caoccao** [comment]
So far there is no official Windows build newer than v4.6.0. You may try a private build of v6.2.0 at this [link](https://github.com/caoccao/Javet/releases/tag/0.6.2.0).

**Comment by ThatBlockyPenguin** [comment]
@caoccao Ah, that looks interesting, thank you. I'll use that for now then. Closing the issue.
