### ISSUE TITLE
Issue with react server side script JS

### ISSUE THREAD

**Issue by kdesineedi** [eclipsesource/J2V8#567]
Hi all,

I am using the below version of J2V8.If I load a simple javascript things work fine however if I use a much larger file for server side rendering, the java code terminates without throwing any error at the V8.executeScript(<String version of the server side ReactJs file>))
```
              <dependency>
			<groupId>com.eclipsesource.j2v8</groupId>
			<artifactId>j2v8_win32_x86_64</artifactId>
			<version>2.2.1</version>
		</dependency>
```
Can you please let me know what the issue could be or how to debug this as there is no error message thrown.

**Comment by caoccao** [comment]
The latest Windows build v4.6.0 was released in 2016 and there seems to have been no official support for many years. Please refer to [Reduce the scope of the J2V8 project](https://github.com/eclipsesource/J2V8/issues/441) for detail.

For server side rendering, e.g. reactjs, I recommend [Javet](https://github.com/caoccao/Javet).

**Comment by kdesineedi** [comment]
Thanks @caoccao .Could you please share any example on how you are loading a react server side rendering script using Javet, evaluate it and then use it for invoking functions within that script?

I tried to go through the Javet documentation but could not find one. Apologies if I missed it but please guide?

**Comment by caoccao** [comment]
> Thanks @caoccao .Could you please share any example on how you are loading a react server side rendering script using Javet, evaluate it and then use it for invoking functions within that script?
> 
> I tried to go through the Javet documentation but could not find one. Apologies if I missed it but please guide?

It has a genuine Node.js embedded. So, you just do what you normally do in the embedded Node.js. You may start with the simple [tutorial](https://www.caoccao.com/Javet/tutorial/basic/hello_javet.html).

**Comment by kdesineedi** [comment]
Awesome.Thanks!
