### ISSUE TITLE
September 2021 Windows and Linux build

### ISSUE THREAD

**Issue by mrinalsharma** [eclipsesource/J2V8#568]
Is this library still support Windows and Linux?
Where can we download Windows and Linux binaries?

**Comment by caoccao** [comment]
So far there has been no such builds since 2017.

I managed to create a [private build](https://github.com/caoccao/Javet/releases/tag/0.6.2.0) with V8 v8.3.110.9 for Windows and Linux. I stopped building new versions though now V8 v9.4 is the stable one for various reasons. You are welcome taking a try.

**Comment by mrinalsharma** [comment]
Thank you for replying, do you know why there have been no official builds? Is there any other library recommended for this Java/Node integration?

Are you planning to do V8 v9.4 build?

**Comment by caoccao** [comment]
> Thank you for replying, do you know why there have been no official builds? Is there any other library recommended for this Java/Node integration?

Please refer to [Reduce the scope of the J2V8 project](https://github.com/eclipsesource/J2V8/issues/441) for detail.

Node.js support has been absent for years. If you are keen on Node.js, so far, the only option is [Javet](https://github.com/caoccao/Javet).

> Are you planning to do V8 v9.4 build?

No. Building J2V8 takes extraordinary effort. I won't do that again unless I'm well-funded 😜.

**Comment by mrinalsharma** [comment]
Thanks again. This my be a stupid question. Is there a way to enable nodejs support?

**Comment by caoccao** [comment]
> Thanks again. This my be a stupid question. Is there a way to enable nodejs support?

Not possible in J2V8, because Node.js support was removed long time ago.

But Javet supports genuine Node.js well.
