### ISSUE TITLE
getString on null shouldn't throw

### ISSUE THREAD

**Issue by djMax** [eclipsesource/J2V8#59]
```{nullString:null}```

v8object.getString("nullString") throws V8ResultUndefined. I really don't think it should. The result is very defined. :)

**Comment by irbull** [comment]
Thanks for the bug report. Marking for 3.0. Should be easy to fix.

**Comment by irbull** [comment]
This is fine for getString (getObject and getArray), but for getInteger, getDouble, and getBoolean we will still need to throw the exception because we cannot return null in those cases.

**Comment by djMax** [comment]
totally agree.

**Comment by irbull** [comment]
Fixed with 1a8a8759caf1fafc0cc2a734eb3f9ed13219d1c2
