### ISSUE TITLE
Update V8 engine

### ISSUE THREAD

**Issue by Lampotrias** [eclipsesource/J2V8#596]
Hi everyone.

Can you update J2V8 with new version of V8 engine?

Thanks a lot!

**Comment by k4k7us23** [comment]
I have just built a fork with 16kb page size alignment and V8's version updated to 13.9.205.21. Updated V8 engine works way faster than 9.3.345.11, which is used in the main repo’s latest version. Feel free to try the fork and provide feedback.

https://github.com/k4k7us23/J2V8

```groovy
dependencies {
    implementation 'io.github.k4k7us23:j2v8:1.0'
}
```
