### ISSUE TITLE
Maven central link says 'invalid'

### ISSUE THREAD

**Issue by irbull** [eclipsesource/J2V8#65]
@angelozerr Any idea why the maven central image says "invalid"?

**Comment by angelozerr** [comment]
Stupid error, sorry.
See https://github.com/eclipsesource/J2V8/pull/66

**Comment by irbull** [comment]
Sorry, I should have noticed that. Thanks!

**Comment by angelozerr** [comment]
Sory it was my fault.

It should be very cool if you could add travis. I don't know if it will work with your build, but I can create a PR if you wish.
