### ISSUE TITLE
Create build output that is more easily consumable on Android

### ISSUE THREAD

**Issue by mpost** [eclipsesource/J2V8#77]
Currently the project produces a single .jar that is not easily consumable on Android when requiring 64bit support. In addition the monolithic jar does not allow to create individual Android .apks for each architecture from the standard gradle build.

We should consider create a custom maven artifact like J2V8-android that is an Android library project containing the correct folder structure to make it easier to consume J2V8.

This repackaging could be done in the build process but we might need to update the loading mechanism of the native artifact inside J2V8 a bit.

**Comment by irbull** [comment]
I don't really understand what you mean by a "custom maven artifact" and I don't know what the "correct folder structure" is. Can you elaborate on these two things?

**Comment by mpost** [comment]
After thinking about it some more maybe it doesn't have to be its own maven artifact. But it has to be an android library project. We could probably tell the build to use that as "aar" instead of the default "jar". eg in gradle that would be: `compile 'com.eclipsesource.j2v8:j2v8_android:3.0.0@aar'`

The correct folder structure would be one which contains the jniLibs folder structure so that the android build could pick the correct native binary or at runtime the android device could pick the correct binary.

The structure looks like this:

```
app
   |
   src
      |
      jniLibs
             |
             armeabi
             |     |
             |     your_lib.so
             |
             armeabi-v7a
             |         |
             |         your_lib.so
             |
             x86
               |
               your_lib.so
```

**Comment by lidord** [comment]
The aar sounds like a nice solution,
Anyway, for now we just add the x86_64.so and it works (also on the Asus
devices with the x86_64 processor - the one that it crashed on before we
add the x86_64 lib),
In our code its looks like this:

[image: Inline image 1]

Thanks a lot for your quick response and the effort!!

Lidor

**Comment by mpost** [comment]
@lidord That is good to hear. The image doesn't work btw.

**Comment by lidord** [comment]
The image attached, hope you can open it
Thanks!

**Comment by mpost** [comment]
@lidord I guess when you answer to an issue with an email, the attachment does not get converted correctly. But nevermind since your problem is solved, all is good.

**Comment by zhm** [comment]
What is the correct folder structure to get maximum compatibility? I couldn't see the attachment that @lidord uploaded. Are you using the maven dependency?

`compile 'com.eclipsesource.j2v8:j2v8_android:3.0.0`

Being a bit of a noob with JNI/NDK, it's unclear what compatibility this results in when using the `V8 context = V8.createV8Runtime("", getActivity().getApplicationInfo().dataDir);` pattern to load the library. I've read that there are differences between `System.load` and `System.loadLibrary` in how they can detect and load 32bit on 64bit hardware. I'm not looking for a real 64bit binary, but I'd like our app to not crash on an arm64 device :) Unfortunately I don't have an arm64 device to test with yet so I was wondering if anyone could offer some info on the best practice to get maximum device compatibility with this awesome library! Is it best to use the maven dependency and then also side-load the `.so` files into the project so they don't have to be unpacked at runtime and use hardcoded load paths? If so, what would the exact dir structure be and files in those directories?

**Comment by lidord** [comment]
Hi, The new .so file reduce the crashes but there are still few issues:
1. Adding .so to jniLibs increasing the apk size in about 5M :(
2. There are still some crashes on some devices in production (mainly Asus devices)  - though, most 64bit devices are working ok.

It will help if you will find a solution to it. We realy love your work and this is the only issue that makes us problems. 

Anyway, @zhm , the structure under jniLibs is:
armeabi-v7a (folder)
-------------- libj2v8_android_armv7l.so
x86 (folder)
-------------- libj2v8_android_x86.so
-------------- libj2v8_android_x86_64.so

Thanks

**Comment by zhm** [comment]
@lidord thanks for the response! I appreciate it.

**Comment by irbull** [comment]
J2V8 now ships as an *aar* file. Please see [this post](http://eclipsesource.com/blogs/2015/11/04/shipping-j2v8-as-an-aar/) for details. This should make consumption must easier on android. Thanks to @mpost for doing the hard work here!
