### ISSUE TITLE
Issue with 64 bit processor

### ISSUE THREAD

**Issue by achaudhry** [eclipsesource/J2V8#78]
Hello,

I'm having an issue on my 64 bit phone (Samsung s6 Egde). If you look at the error message below "libj2v8_android_armv7l.so is 32-bit instead of 64-bit" seems to be the key. I'm using the latest jar (v3.0). Any guidance is much appreciated!

Thanks in advance!

### Stack Trace
Caused by: java.lang.UnsatisfiedLinkError: Could not load J2V8 library. Reasons:
dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.myapp-2/base.apk"],nativeLibraryDirectories=[/vendor/lib64, /system/lib64]]] couldn't find "libj2v8_android_armv7l.so"
dlopen failed: "/data/data/com.myapp/libj2v8_android_armv7l.so" is 32-bit instead of 64-bit
at com.eclipsesource.v8.LibraryLoader.loadLibrary(LibraryLoader.java:71)
at com.eclipsesource.v8.V8.load(V8.java:69)
at com.eclipsesource.v8.V8.createV8Runtime(V8.java:131)

PS: I posted a message a few days ago in [another thread] (https://github.com/eclipsesource/J2V8/issues/76) but didn't get a response so I'm logging a separate issue. Sorry for duplicate posts!

**Comment by noear** [comment]
反馈：8月份的新代码，同样没有改善对64位手机的兼容。

**Comment by irbull** [comment]
Please try to consume J2V8 as a *aar* file now. See [this post](http://eclipsesource.com/blogs/2015/11/04/shipping-j2v8-as-an-aar/) for details.

**Comment by irbull** [comment]
I've heard that things are working better with the aar. Closing. Please re-open if are you still having problems.
