### ISSUE TITLE
Long value is treated as int when converting in V8ObjectUtils

### ISSUE THREAD

**Issue by mpost** [eclipsesource/J2V8#83]
The class `com.eclipsesource.v8.utils.V8ObjectUtils` converts long values to int and thereby the value loses precision:

In j2v8 3.0 - V8ObjectUtils.java:376

```java
result.push((int) (long) (Long) value);
```

**Comment by irbull** [comment]
JS only has one numerical type 'number'. V8 has some optimizations for 32 bit integers. In this case, storing a Java long as an integer is clearly wrong, but the only other option is as a double precision `number`.  This means that if you write a large long, you may not get back exactly what you had, but you should be able to retrieve it within a small delta.

```
@Test
public void testCreateV8ArrayFromMaxValueLong() {
  List<Long> list = new ArrayList<Long>();
  list.add(Long.MAX_VALUE);

  int size = registerAndRelease("result", list);

  assertEquals(1, size);
  assertEquals(Long.MAX_VALUE, v8.executeDoubleScript("result[0]"), 0.00001);
}
```
