### ISSUE TITLE
J2V8 based apps can not be installed on Android Marshmallow 64bit emulator

### ISSUE THREAD

**Issue by mpost** [eclipsesource/J2V8#87]
The apk can not be installed using the <code>Intel x86 Atom_64</code> Android 6.0 (API 23) emulator image. The error message states: <code>INSTALL_FAILED_NO_MATCHING_ABIS</code>. We have used the trick to package the .so manually but that didn't help here. Not sure if it is a general Marshmallow problem.

**Comment by Yavor** [comment]
I've tested it with `Intel x86 Atom_64 System Image` too and it's worked for me.

I have the three `.so` libs in `jniLibs` as suggested by @irbull in [Add support to 64 bit devices for Android #76] (https://github.com/eclipsesource/J2V8/issues/76) and in the build file I've put `compile 'com.eclipsesource.j2v8:j2v8_android:3.0.2'`. Hope this helps.

**Comment by mpost** [comment]
@Yavor You are right. It also works on Marshmallow when copied correctly. Thanks for the hint.
