### ISSUE TITLE
 In its native application of Windows, when you call the v8.executeScript() method, JVM to crash.

### ISSUE THREAD

**Issue by yososs** [eclipsesource/J2V8#93]
Native applications of Windows is a JavaFX application that you created in javapackeger.

 #
 # A fatal error has been detected by the Java Runtime Environment:
 #
 #  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffb5e48048d, pid=9280, tid=432
 #
 # JRE version: Java(TM) SE Runtime Environment (8.0_60-b27) (build 1.8.0_60-b27)
 # Java VM: Java HotSpot(TM) 64-Bit Server VM (25.60-b23 mixed mode windows-amd64 compressed oops)
 # Problematic frame:
 # C  [j2v8_win32_x86_64.dll+0x53048d]
 #
 # Failed to write core dump. Minidumps are not enabled by default on client versions of Windows
 #
 # If you would like to submit a bug report, please visit:
 #   http://bugreport.java.com/bugreport/crash.jsp
 # The crash happened outside the Java Virtual Machine in native code.
 # See problematic frame for where to report the bug.
 #

---------------  T H R E A D  ---------------

Current thread (0x00000019ff060000):  JavaThread "pool-2-thread-1" [_thread_in_native, id=10544, stack(0x0000001990530000,0x0000001990630000)]

siginfo: ExceptionCode=0xc0000005, reading address 0xffffffff914c6080

Registers:
RAX=0xffffffff914c6080, RBX=0x0000001997429c98, RCX=0x00000019ff0601f8, RDX=0x00000000914c6080
RSP=0x0000001990629660, RBP=0x0000001990629918, RSI=0x0000000000000000, RDI=0x0000001990629690
R8 =0xffffffff914c6080, R9 =0x0000000000000000, R10=0x00000019d8f06eef, R11=0x0000000054e89440
R12=0x0000000000000000, R13=0x0000001997429c98, R14=0x0000001990629968, R15=0x00000019ff060000
RIP=0x00007ffb5e48048d, EFLAGS=0x0000000000010282

Top of Stack: (sp=0x0000001990629660)
0x0000001990629660:   cccccccccccccccc cccccccccccccccc
0x0000001990629670:   cccccccccccccccc cccccccccccccccc
0x0000001990629680:   ffffffff914c6080 cccccccccccccccc
0x0000001990629690:   0000001990629870 00007ffb5e475eb9
0x00000019906296a0:   00000019ff0601f8 cccccccc914c6080
0x00000019906296b0:   cccccccccccccccc cccccccccccccccc
0x00000019906296c0:   cccccccccccccccc cccccccccccccccc
0x00000019906296d0:   cccccccccccccccc cccccccccccccccc
0x00000019906296e0:   cccccccccccccccc cccccccccccccccc
0x00000019906296f0:   cccccccccccccccc cccccccccccccccc
0x0000001990629700:   cccccccccccccccc cccccccccccccccc
0x0000001990629710:   cccccccccccccccc cccccccccccccccc
0x0000001990629720:   cccccccccccccccc cccccccccccccccc
0x0000001990629730:   cccccccccccccccc cccccccccccccccc
0x0000001990629740:   cccccccccccccccc cccccccccccccccc
0x0000001990629750:   cccccccccccccccc cccccccccccccccc 

Instructions: (pc=0x00007ffb5e48048d)
0x00007ffb5e48046d:   07 08 00 48 8b 4c 24 40 e8 d6 fe ff ff 33 c0 eb
0x00007ffb5e48047d:   12 48 63 44 24 48 48 89 44 24 20 48 8b 44 24 20
0x00007ffb5e48048d:   48 8b 00 48 83 c4 30 5f c3 cc cc cc cc cc cc cc
0x00007ffb5e48049d:   cc cc cc 48 89 4c 24 08 57 48 83 ec 20 48 8b fc 

Register to memory mapping:

RAX=0xffffffff914c6080 is an unknown value
RBX={method} {0x0000001997429ca0} '_executeScript' '(JILjava/lang/String;Ljava/lang/String;I)Ljava/lang/Object;' in 'com/eclipsesource/v8/V8'
RCX=0x00000019ff0601f8 is an unknown value
RDX=0x00000000914c6080 is an unknown value
RSP=0x0000001990629660 is pointing into the stack for thread: 0x00000019ff060000
RBP=0x0000001990629918 is pointing into the stack for thread: 0x00000019ff060000
RSI=0x0000000000000000 is an unknown value
RDI=0x0000001990629690 is pointing into the stack for thread: 0x00000019ff060000
R8 =0xffffffff914c6080 is an unknown value
R9 =0x0000000000000000 is an unknown value
R10=0x00000019d8f06eef is at code_begin+911 in an Interpreter codelet
method entry point (kind = native)  [0x00000019d8f06b60, 0x00000019d8f07580]  2592 bytes
R11=0x0000000054e89440 is an unknown value
R12=0x0000000000000000 is an unknown value
R13={method} {0x0000001997429ca0} '_executeScript' '(JILjava/lang/String;Ljava/lang/String;I)Ljava/lang/Object;' in 'com/eclipsesource/v8/V8'
R14=0x0000001990629968 is pointing into the stack for thread: 0x00000019ff060000
R15=0x00000019ff060000 is a thread

Stack: [0x0000001990530000,0x0000001990630000],  sp=0x0000001990629660,  free space=997k
Native frames: (J=compiled Java code, j=interpreted, Vv=VM code, C=native code)
C  [libj2v8_win32_x86_64.dll+0x53048d]
C  [libj2v8_win32_x86_64.dll+0x525eb9]
C  0x00000019d8f06f1b

Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  com.eclipsesource.v8.V8._executeScript(JILjava/lang/String;Ljava/lang/String;I)Ljava/lang/Object;+0
j  com.eclipsesource.v8.V8.executeScript(JILjava/lang/String;Ljava/lang/String;I)Ljava/lang/Object;+9
j  com.eclipsesource.v8.V8.executeScript(Ljava/lang/String;Ljava/lang/String;I)Ljava/lang/Object;+17
j  com.eclipsesource.v8.V8.executeScript(Ljava/lang/String;)Ljava/lang/Object;+4

---------------  S Y S T E M  ---------------

OS: Windows 10.0 , 64 bit Build 10240 (10.0.10240.16384)

CPU:total 8 (4 cores per cpu, 2 threads per core) family 6 model 60 stepping 3, cmov, cx8, fxsr, mmx, sse, sse2, sse3, ssse3, sse4.1, sse4.2, popcnt, avx, avx2, aes, clmul, erms, lzcnt, ht, tsc, tscinvbit, bmi1, bmi2

Memory: 4k page, physical 33428956k(28378168k free), swap 33428956k(26986272k free)

vm_info: Java HotSpot(TM) 64-Bit Server VM (25.60-b23) for windows-amd64 JRE (1.8.0_60-b27), built on Aug  4 2015 11:06:27 by "java_re" with MS VC++ 10.0 (VS2010)

**Comment by irbull** [comment]
I assume this is Windows 10 (since it says that in the crash log). Can you:
 1. Provide a snippet or junit test that shows this problem
 2. Tell me what version of J2V8 you are using
 3. Is this the fully crash log?

**Comment by yososs** [comment]
(1) OK
To reproduce, you will need an installer that was generated by the Javapackager.
Please wait for a while because think how to provide.

(2) the latest v3.0.1 (from maven repo)

(3) is the main part of the mini-crash dump. I will retaken the dump in a small test code.

**Comment by yososs** [comment]
As a result of trial I found v.3.0.2 with maven, This crash problem no longer occurs.

**Comment by irbull** [comment]
Yes, I pushed 3.0.2 to maven central because of a 64 bit pointer issue on Windows (issue #90). It looks like it might be the same problem, which is good.

Thank-you for reporting this. I'll close this issue.
