### ISSUE TITLE
Math.pow(NaN, -1) crashes on 64-bit Windows on AWS

### ISSUE THREAD

**Issue by ccantill** [eclipsesource/J2V8#95]
(continued from https://github.com/eclipsesource/J2V8/issues/90)

The following code crashes the JVM when run on our AWS hosted Windows 2007 server:

```
     V8 runtime = V8.createV8Runtime();
     runtime.executeScript("Math.pow(NaN, -1)");
```

I can only reproduce this on the AWS server running 64-bit Windows 2007 Server SP2. Tried it with multiple versions of the JRE (1.7.0_79, 1.8.0_60, 1.8.0_40) and they all give the same result. However, I can not reproduce it on my own Linux machine or on my colleagues Windows 7 laptop with any of those versions of the JRE.

There is no crash log, so the only extra bit of information is the logging from the Event Viewer: https://gist.github.com/ccantill/c1c008d824d289eca991

**Comment by irbull** [comment]
In order to help move this project forward, we are scoping it. We will only be supporting Android. Others are free to build a downstream project and support other platforms, but I don't have the cycles. See #441 for more information.
