### ISSUE TITLE
Supporting multiple arch types

### ISSUE THREAD

**Issue by achaudhry** [eclipsesource/J2V8#96]
Hello,

We're using J2v8 in our application and came across an issue which caused a lot of crashes and I'd like to propose a solution for it.

#### Issue (2 parts):
1. The so files that are bundled with j2v8 are named differently for each architecture type. For example, *libj2v8_android_x86.so* and *libj2v8_android_x86_64.so* which by the way are the same exact files, just named differently. 

2. The application using j2v8 crashes in many cases because it can't find the '.so' file for the CPU architecture. The problem I believe is in the *LibraryLoader.getArchSuffix()* method which is used while constructing the file name for the so files. Based on the 'os.arch' this method returns the arch suffix and appends it to the file name. The issue is that it is really hard and probably not ideal to expand / maintain method for all os.arch types. For example, currently this method does not support or check for archv7a which is what most of the new Android devices have (Samsung s6 edge for instance). 

#### Proposed solution:

1.I believe that the so file names should be generic and they should be placed in appropriate jniLibs directory. Then we should trust Android to look in the appropriate directory and load the correct so file. For instance, the structure would look like this:

```
	-> jniLibs
		--> armeabi
			---> libj2v8_android.so
		--> armeabi-v7a
			---> libj2v8_android.so
		--> x86
			---> libj2v8_android.so 
```
2.We can completely get rid of *LibraryLoader.getArchSuffix()* and do not append anything to the filename before loading the library.

Then j2v8 can be distributed as an AAR with the above directory structure, which people will be able to use in their application an an Android library. 

I've tested the above approach and it seems to work fine with most arch's I was having issues with since Android picks up the appropriate so files. Furthermore, this means we'll have less so files and will reduce the size of the APK (for example instead of having x86 and x86_64, we'll just have one file). 

Please let me know what your thoughts are on this. I'm happy to make the changes once we agree on an approach and can create a pull request. I just wanted to run this by you first to see if you agree with the above and if I have missed anything.

Thank you!

Kind regards
Abrar

**Comment by mpost** [comment]
The approach has been outlined in other issues as well. Should be the correct way to properly add Android support.

**Comment by Yavor** [comment]
AAR sounds about the right approach for a library that comes with Android resources. I recommend using [android-native-dependencie] (https://github.com/nhachicha/android-native-dependencies) and remove `LibararyLoader` altogether.

**Comment by irbull** [comment]
We now provide J2V8 as an *aar*. See [this blog](http://eclipsesource.com/blogs/2015/11/04/shipping-j2v8-as-an-aar/) for more details.

**Comment by achaudhry** [comment]
Great news! Thanks, irbull. Will try in our app and let you know how it goes!
