### ISSUE TITLE
J2V8 on Android 6 (Mashmallow) can not be loaded on arm 64bit

### ISSUE THREAD

**Issue by mpost** [eclipsesource/J2V8#97]
We are having issues when loading j2v8 on an Android 6 (Marshmallow) device with a 64bit arm architecture (Nexus 9). Currently it can just not be loaded. The reason for it is the way how the `com.eclipsesource.v8.LibraryLoader` resolves the architecture of the device.

The architecture reported by the device via `System.getProperty("os.arch")` is `armv8l` and the first attempt to find the .so file is to call `System.loadLibrary()` which looks for a library called `j2v8_android_armv8l` that can not be found since it is not placed in any of the jniLibs folders by default. 

Next the `LibraryLoader` tries to find a file called `/data/user/0/com.myapp/libj2v8_android_armv8l.so` (which maps to the root folder of the Android .apk) but again can't find the file.

So the only solution to that problem is the same as has been mentioned before... place the library manually into the folder `armeabi-v7a` with the name `libj2v8_android_armv8l.so`. Thereby the first load attempt via `System.loadLibrary()` succeeds.

This has the side effect that we have to bundle the .so file once more inside the app. The proper solution to dealing with these dependencies on Android has been outlined already in https://github.com/eclipsesource/J2V8/issues/96: The LibraryLoader should not try to infer any information about the architecture and library name and leave that to the Android system which is able to make the right assumption based on the .aar file the gradle build could consume.

**Comment by irbull** [comment]
Can you verify if this is fixed with 3.1.0-SNAPSHOT. It appears to work fine on my Nexus 5 now.

**Comment by mpost** [comment]
With the new .aar support the problem has been resolved.
