### ISSUE TITLE
NEXUS 9 （CPU = Nvidia Tegra K1）会出错

### ISSUE THREAD

**Issue by noear** [eclipsesource/J2V8#98]
NEXUS 9 （CPU = Nvidia Tegra K1）运行会出错。

**Comment by irbull** [comment]
According to Google, this translates to: NEXUS 9 (CPU = Nvidia Tegra K1) run error. Please try the (3.1.0-SNAPSHOT)[http://eclipsesource.com/blogs/2015/11/04/shipping-j2v8-as-an-aar/].
